### ISSUE TITLE
Include new Groundspeak stuff in GPX files (1.0.2 schema)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/okapi#221]
```
http://forums.groundspeak.com/GC/index.php?showtopic=275718
```

Original issue reported on code.google.com by `rygielski` on 14 Apr 2013 at 9:13

**Comment by following5** [comment]
The announced Groundspeak 1.0.2 schema has never been released. See https://github.com/opencaching/gpx-extension-v1/blob/master/all-these-namespaces.md.
