### ISSUE TITLE
Upgrade mysql to mysqli or PDO

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/okapi#297]
```
Newer versions of PHP issue the following warning:

The mysql extension is deprecated and will be removed in the future: use mysqli 
or PDO instead

```

Original issue reported on code.google.com by `rygielski` on 7 Jan 2014 at 6:01

**Comment by wrygiel** [comment]
I'm not really happy doing this, because 1) I am certain that all of my OKAPI code was secured against injection (the "always use `mysql_real_escape_string` rule), and 2) I don't like breaking diffs by huge bulk-replace refactoring operations.

But, on the other hand, `mysql_` is deprecated, so this would be needed sooner or later anyway.

**Comment by wrygiel** [comment]
I'll start off with a commit adding an abstraction layer for all mysql_* functions - a simple regexp bulk-replacing, nothing more. After this, *all* the `mysql_*` functions will be referenced in a single place in the code only: the `Db` class.

**Comment by wrygiel** [comment]
Two errors slipped by. Fixed in c33a46f - some of the refactored files did not use the `Db` class before and were missing the proper `use` declaration.

**Comment by wrygiel** [comment]
@following5, which engine have you chosen for OCDE - PDO or MySQLi?

**Comment by following5** [comment]
OCDE still uses the deprecated old mysql_ interface. Our server is running PHP 5.4 and probably won't be upgraded to anything beyond PHP 5.5 within the next years, so this is fine for now.

Also, the current OCDE developer VM does not support PDO, it cannot be installed. A new VM is under work, it probably will take some more weeks until it is available. Until then, I would have to suspend OKAPI development if it is migrated to PDO now.

**Comment by wrygiel** [comment]
> Also, the current OCDE developer VM does not support PDO, it cannot be installed.

Are you sure? PDO has been introduced in PHP 5.1. That would mean that your VM is over 10 years old.

**Comment by following5** [comment]
The VM has a custom-compiled PHP 5.3. Precompiled PDO binaries from repositories cannot be installed there. And it's not feasible to try an own custom-compilation of some old PDO, as the new VM will be available soon.

**Comment by wrygiel** [comment]
I also don't use PDO in any of my projects - I learned to escape my SQL long time ago, and I am generally fine with that.

But I'm starting to become a little irritated at some people's suggestions that "any usage of `mysql_` is insecure", hence this change proposal. (In fact, this commit doesn't change anything in regard to the security of the platform, but I guess it will make some people complain less.)

**Comment by following5** [comment]
I am PDO-enabled now. :) The setup of all current OCDE sites is CentOS 7, MariaDB 5.5 & PHP 5.4. There also is a new public test site including OKAPI: http://test.opencaching.de

**Comment by wrygiel** [comment]
That's good :) Tomorrow I am leaving for Oslo for the next 5 days. Probably I will merge it after I return.

**Comment by following5** [comment]
acidentially pressed the "merge button"

**Comment by wrygiel** [comment]
Before this can be merged again, this needs to be fixed:

```
OKAPI caught the following exception while executing API method request.
This is an error in OUR code and should be fixed. Please contact the
developer of the module that threw this error. Thanks!

===== ERROR MESSAGE =====
PDO::exec() [<a href='pdo.exec'>pdo.exec</a>]: LOAD DATA LOCAL INFILE forbidden
=========================

--- Stack trace ---
#0 [internal function]: okapi\OkapiErrorHandler::handle(2, 'PDO::exec() [<a...', '/var/www/ocpl/o...', 535, Array)
#1 /var/www/ocpl/okapi/core.php(535): PDO->exec('?              ...')
#2 /var/www/ocpl/lib/mapper_okapi.php(80): okapi\Db::execute('?              ...')
#3 {main}

--- OKAPI method called ---
/lib/mapper_okapi.php
?userid=16925
&z=12
&x=2255
&y=1303
&h_u=false
&h_t=false
&h_m=false
&h_v=false
&h_w=false
&h_e=false
&h_q=false
&h_o=false
&h_owncache=false
&h_ignored=true
&h_own=true
&h_found=false
&h_noattempt=false
&h_nogeokret=false
&h_avail=false
&h_temp_unavail=true
&h_arch=true
&be_ftf=false
&powertrail_only=false
&min_score=-3
&max_score=3
&h_noscore=true
&rand=r0
&searchdata=56d53bb987a5f

--- OKAPI version ---
1151 (743881c590d9d8a70e8cefa10ba0b33faaa7835b)
```

**Comment by wrygiel** [comment]
Possible solution here: http://stackoverflow.com/a/17430025/1010931

**Comment by wrygiel** [comment]
I will attempt to commit this again. My solution to https://github.com/opencaching/okapi/issues/425 will be built on PDO.

**Comment by wrygiel** [comment]
Reverted.

**Comment by wrygiel** [comment]
Still getting `PDO::exec() [<a href='pdo.exec'>pdo.exec</a>]: LOAD DATA LOCAL INFILE forbidden` exceptions on OCPL's production site.

**Comment by wrygiel** [comment]
It works on my new dev server. It doesn't work on OCPL's old 5.3 PHP server. This change will need to wait a bit for OCPL server to be upgraded to PHP 5.6.

**Comment by wrygiel** [comment]
BTW, how Germanish :)

![image](https://cloud.githubusercontent.com/assets/2168535/15519336/496cafc6-2201-11e6-8dca-0e7e5f3e2470.png)

**Comment by wrygiel** [comment]
Anyway, back on topic, OCPL is now on PHP 5.6 so I think this can be finally submitted again. I'll try in a minute.

**Comment by following5** [comment]
What exactly was the problem with the old PHP version on OCPL? May there be problems when I release this to the current PHP 5.4 OC.de site?

**Comment by wrygiel** [comment]
The problem was only in the tilemap backend. You're not using it, so you won't have any problems.

**Comment by wrygiel** [comment]
(Actually, the `LOAD DATA LOCAL INFILE` code which was not executing correctly was on the OCPL's side, not OKAPI's)

**Comment by wrygiel** [comment]
(it used OKAPI's Db::execute, which used PDO, which hadn't supported INFILE statements in old PHP versions)

**Comment by andrixnet** [comment]
OCNL now running PHP-5.6.22
