### ISSUE TITLE
View coordinates history along the "Moved" log types

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/okapi#304]
```
From issue 108:

"""
Is it possible to add the to the log of  type "Moved" additional field with  
new coordinates of the cache?
"""

```

Original issue reported on code.google.com by `rygielski` on 27 Jan 2014 at 9:44

**Comment by following5** [comment]
Are "moved" logs still in use at OCPL? On my makeshift OCPL develsite, I can directly modify cache coordinates, but not post "moved" logs. But that may be due to misconfiguration.

At OCDE there never have been "moved" logs.

**Comment by deg-pl** [comment]
"Moved" logs are allowed only for moving caches and own caches.

**Comment by following5** [comment]
I cannot log "moved" for own caches on my develsite either. Probably something is missing in the static data tables. The database was initialized from docs/sql/data.sql, and then updating table structures and running the "sqlAlters".

So there are two ways to alter OCPL cache coordinates: directly editing the listing, or logging coordinates - right?

**Comment by following5** [comment]
(But "move" logs for moving caches work, that's sufficient for testing this log type.)

**Comment by following5** [comment]
Sorry, I misunderstood "Own caches" as "owned caches" :-). Moving "own" caches works. Don't have those at OCDE.

The move coordinates can easily be added to the methods for retrieving log entries, will implement that.
