### ISSUE TITLE
services/logs/submit: Nonunique UUIDs generated?

### ISSUE THREAD

**Issue by wrygiel** [opencaching/okapi#336]
Quote in Polish (sent to rt@opencaching.pl):

```
Ten błąd wynika z tego, że w bazie pojawił się zduplikowany UUID dla
dwóch różnych wpisów do logów:

mysql> select uuid, count(*) from cache_logs group by uuid having count(*) >= 2;
+--------------------------------------+----------+
| uuid                                 | count(*) |
+--------------------------------------+----------+
| cf285f38-8524-4cd7-a710-965dc44284ae |        2 |
+--------------------------------------+----------+
1 row in set (2.38 sec)

Obydwa logi nie mają ze sobą nic wspólnego, ale obydwa były stworzony
przez OKAPI. Co wskazywałoby na to, że OKAPI ma błędny sposób
generowania UUIDów?

Jeśli macie jakieś inne pomysły z czego to mogło wyniknąć, to dajcie
znać. Póki co, wrzucę do do issue trackera OKAPI.
```

**Comment by following5** [comment]
Besides of the question how this duplicate UUID was generated, it is a database design fault to allow duplicated UUIDs to be inserted into the same table. The `uuid` key for the OC.pl 'cache_logs' table should be changed from KEY to UNIQUE to prevent this (of course, after fixing all duplicate entries). The same is true for the tables 'mp3', 'pictures' and 'user'. All other uuid fields in OC.pl tables are correctly indexed as PRIMARY or UNIQUE.

**Comment by wrygiel** [comment]
BTW, since UUIDs are now corrected in the database, it is no longer critical. This particular issue is related to OKAPI, but you're right that it should be fixed in OCPL repo too.
