### ISSUE TITLE
Unhandled exception if user/by_username ist passed a pipe (|)

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#339]
When services/users/by_username is called with a username parameter containing a pipe char (|), OKAPI will thrown an unhandled exception. Instead, it should report an invalid username error. I will fix this.

**Comment by wrygiel** [comment]
Thanks! I've seen this error before, but never got to fixing it... (I think I should also try to "ban" this character in OCPL usernames, fortunatelly there are not so many of such usernames...)

**Comment by following5** [comment]
Are you sure that there are such usernames in OCPL database? The current OCPL code does not allow them:

clicompatbase.php, line 47:
define('regex_username', '^[a-zA-Z0-9ęóąśłżźćńĘÓĄŚŁŻŹĆŃăîşţâĂÎŞŢÂșțȘȚéáöőüűóúÉÁÖŐÜŰÓÚ@-][a-zA-ZęóąśłżźćńĘÓĄŚŁŻŹĆŃăîşţâĂÎŞŢÂșțȘȚéáöőüűóúÉÁÖŐÜŰÓÚ0-9\.\-=_ @ęóąśłżźćńĘÓĄŚŁŻŹĆŃăîşţâĂÎŞŢÂșțȘȚéáöőüűóúÉÁÖŐÜŰÓÚäüöÄÜÖ=)(\/\\\ -=&*+~#]{2,59}$');

**Comment by wrygiel** [comment]
You're right. There are none. ;)

On Fri, Jul 31, 2015 at 10:05 PM, following5 <notifications@github.com>
wrote:

> Are you sure that there are such usernames in OCPL database? The current
> OCPL code does not allow them:
>
> clicompatbase.php, line 47:
> define('regex_username',
> '^[a-zA-Z0-9ęóąśłżźćńĘÓĄŚŁŻŹĆŃăîşţâĂÎŞŢÂșțȘȚéáöőüűóúÉÁÖŐÜŰÓÚ@-][a-zA-ZęóąśłżźćńĘÓĄŚŁŻŹĆŃăîşţâĂÎŞŢÂșțȘȚéáöőüűóúÉÁÖŐÜŰÓÚ0-9.-=_
> @ęóąśłżźćńĘÓĄŚŁŻŹĆŃăîşţâĂÎŞŢÂșțȘȚéáöőüűóúÉÁÖŐÜŰÓÚäüöÄÜÖ=)(\/\\
> -=&*+~#]{2,59}$');
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencaching/okapi/issues/339#issuecomment-126800225>.
>



-- 
I took an IQ test and the results were negative.
http://rygielski.net/
