### ISSUE TITLE
services/logs/submit comment is required

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#341]
The docs on services/logs/submit state that the `comment` parameter is optional. However, if I omit it, I will receive this:

{ "success": false, "message": "Your have to supply some text for your comment.", "log_uuid": null }

I suggest to change the docs and set this parameter to "required" and state that it must not be an empty string.

**Comment by wrygiel** [comment]
I think that the docs are correct.

The parameter IS optional in a sense that you won't receive HTTP 400 if you don't supply it. However, some OC sites (not all of them) DO require the comment to be present. Hence the HTTP 200 success=false response.

**Comment by following5** [comment]
You are right. I also overlooked that this message only appears for empty logs of type 'Comment'.
