### ISSUE TITLE
Exception handling problem during update

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#342]
If an exception occurs during the OKAPI update process, PHP will produce the warning 'Cannot modify header information - headers already sent ...', which will result in the following error during exception handling (on the new OC.de test server running PHP 5.4):

===== ERROR MESSAGE =====
Uncaught exception 'ErrorException' with message 'Cannot modify header information - headers already sent by (output started at /var/www/centos7/code/htdocs/okapi/views/update.php:57)' in /var/www/centos7/code/htdocs/okapi/core.php:99
Stack trace:
#0 [internal function]: okapi\OkapiErrorHandler::handle(2, 'Cannot modify h...', '/var/www/centos...', 99, Array)
#1 /var/www/centos7/code/htdocs/okapi/core.php(99): header('HTTP/1.0 400 Ba...')
#2 [internal function]: okapi\OkapiExceptionHandler::handle(Object(okapi\InvalidParam))
#3 {main}
  thrown

File: /var/www/centos7/code/htdocs/okapi/core.php
Line: 99

--- OKAPI method called ---
/okapi/update

--- OKAPI version ---
1105 (69bb1a7be72b7a52621532626e5c6813fb26e354)

**Comment by wrygiel** [comment]
Hmm... I'm not sure if I like this fix. If this kind of error will occur only during the update process, wouldn't it be more appropriate to try..catch it during the update process? I will try to look into it later.

**Comment by following5** [comment]
I have just copied the if-condition from a few lines below. Looks like the same problem occured earlier in whatever context, so that you inserted the `if (!headers_sent())` there.

**Comment by wrygiel** [comment]
Probably you're right. Still, I'd like to have a look at the history.

**Comment by wrygiel** [comment]
Okay, I think it's correct. :)
