### ISSUE TITLE
Introduce log_uuids somewhere in generated GPX files

### ISSUE THREAD

**Issue by MavEtJu** [opencaching/okapi#344]
When I submit a log through http://www.opencaching.nl/okapi/services/logs/submit for example, it returns a log_uuid. However, that log_uuid is not reflected in the groundspeak:log id returned in the GPX data.

Returned data:
data: {"success":true,"message":"Your cache log entry was posted successfully.","log_uuid":"3369a85c-cd83-4e24-b3f7-ea733c4a8bb1"}

Later on retrieved GPX file:
<groundspeak:log id="4139">

It would be nice if that number 4139 could be returned by the services/logs/submit function.

Edwin

**Comment by following5** [comment]
You may use the services/logs/entry method to retrieve the ID number which will be returned in the gpx data:

http://www.opencaching.nl/okapi/services/logs/entry?log_uuid=3369a85c-cd83-4e24-b3f7-ea733c4a8bb1&fields=internal_id&consumer_key=...

**Comment by wrygiel** [comment]
This inconsistency is because log IDs in Groundspeaks GPX file need to be integers. We would need to introduce a custom OKAPI XML namespace in the GPX file in order to be able to include UUIDs there. But I'm not sure if anyone would use such extra namespace.

**Comment by following5** [comment]
I like the idea of a custom _Opencaching_ namespace in GPX files, to transport all the OC information which is missing there. This should be a joined effort of OCPL, OCDE and OKAPI developers.

**Comment by wrygiel** [comment]
I was thinking about it when I was making the GPX formatter, but would any client libraries use it? Might be, that would just make our GPX files bigger, for no real reason.

**Comment by following5** [comment]
I think that GSAK may use it. It's a very common tool and already supports the gc_ocde:attrs OConly attribute.

**Comment by following5** [comment]
Meanwhile there is a request at OCDE to include a flag for "log password needed" into GPX files, which then could be evlauated by c:geo.

I will do a sample implementation for an 'opencaching' GPX extension.

**Comment by following5** [comment]
@MavEtJu
The log UUIDs now can be included in GPX files. Set `latest_logs=true` and `ns_oc=true`. You will find the UUIDs in 

```
<wpt>
    <oc:cache>
        <oc:logs>
            <oc:log id="<id>" uuid="<uuid>"
            </oc:log>
        </oc:logs>
    </oc:cache>
</wpt>
```
