### ISSUE TITLE
Implement attrs= gc_ocde:attrs for OCPL

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#346]
OC.pl has [adopted](https://github.com/opencaching/opencaching-pl/commit/9e236bdf8cfe351d4ccfdc32c67e217b3f91caad) the OCDE GPX attribute system for the OC-only-Attribute, which is exported as GPX attribute 106 now by all up-to-date OC installations. This is because _GSAK_ now supports the OConly attribute ID 106.

I suggest to enable the gc_ocde:attrs option for OCPL code, restricted to no. 106 / A1.

**Comment by wrygiel** [comment]
I am indifferent in that matter. I will leave it up to you.

BTW - I am not so sure that OCPL has really adopted the "oc only" attribute. I could not find any reference to in the the GUI.

**Comment by following5** [comment]
Right, this attribute is not available at OC.pl. But according to OKAPI's attribute-definitions.xml it is available at OC.nl. I confused these sites.

**Comment by harrieklomp** [comment]
As far as i know, oc.pl is the only OC site without this "oc-only" attribute. No one ever told me or others why this is?

**Comment by following5** [comment]
Actually, I do not see any refernce to this attribute in the OCPL source code. E.g. there is no oc-only icon [here](https://github.com/opencaching/opencaching-pl/tree/master/images/attributes) or [there](https://github.com/opencaching/opencaching-pl/tree/master/images/cacheatr), and it is not in the [cache-attrib table](https://github.com/opencaching/opencaching-pl/blob/master/docs/sql/static-data/data.sql). So I wonder how this works at all at opencaching.nl. You must have some local extensions to the OCPL code and database ...?

**Comment by harrieklomp** [comment]
When oc.nl started using the Polish code i have added this icon in the cache-attrib table with ID 6. I never notice that oc.pl did not use this attribute.... until a view months ago ;-) . Because i liked our attributes we used before i did edit the links in the cache-attribute table to the nl directory.

**Comment by following5** [comment]
Okay. I think it will be fine to enable this single attribute in GPX files now via gc_ocde:attrs switch. But the implementation is not trivial and I will leave it up to someone else.

**Comment by following5** [comment]
After https://github.com/opencaching/opencaching-pl/issues/1242 has been solved, I would like to enable `gc_ocde:attrs` for OCPL. As this solution will divert from the "+100" scheme and introduce individual mappings, we will need some global table for the `gc_ocde:attrs` mapping.

I think attribute-definitions.xml. E.g. we could add an element which resembles `<groundspeak>`, but contains the OC pseudo-groundspeak IDs. So it could deal with the (very rare) case that Groundspeak adopts an OC attribute.

**Comment by following5** [comment]
Now there are consistent GPX ID/inc mappings defined for all OC attributes. The reference tables are currently [in OCPL code](https://github.com/opencaching/opencaching-pl/blob/84b5cbd1cb240c0f0867fe027e92752a87ae200a/lib/format.gpx.inc.php#L229). I will try to add this information to OKAPI attribute-definitions.xml, so that `gc_ocde:attrs` can be implemented for OCPL (will issue a PR for review).
