### ISSUE TITLE
opencaching.com is gone - update ns_ox

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#347]
The GPX files created by OKAPI refer to the now nonexistent http://www.opencaching.com/xmlschemas/opencaching/1/0/opencaching.xsd, as well as the docs on services/caches/formatters/gpx which have an additional link to http://www.opencaching.com. I assume that the nx_ox extension should not be dropped for compatibity reasons.

The web archive has the XSD: http://web.archive.org/web/20150512043245/http://www.opencaching.com/xmlschemas/opencaching/1/0/opencaching.xsd

**Comment by wrygiel** [comment]
I agree. We could even host the discontinued XSD locally (or use the copy in the web archive, as long as its copy won't disappear).
