### ISSUE TITLE
Search for ignored caches

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#349]
It looks like there is no way in OKAPI to retrieve a list of caches ignored by the user, so it is not possible to provide a "list of caches ignored by me" function within OKAPI clients. This list is useful to verify and maybe discard "ignores".

Did I miss something? Otherwise I would like to add an "ignored_only" option to the search methods.

**Comment by wrygiel** [comment]
You're correct. Note that there's the "exclude_ignored" parameter, which would somewhat clash with the one you want to add. Perhaphs the best option would be to deprecate "exclude_ignored" and introduce a new "ingored_status" parameter similar to the existing "found_status" parameter? It would take one of the following: ingored_only, notignored_only, either (default).

**Comment by following5** [comment]
I think that's a matter of taste. There is no logical contradiction in providing and combining the two boolean fields; it will just (correctly) produce an empty result, like _found_by_ and _not_found_by_ with the same uuid, or min_found > max_founds.

In the OC implementations, these are two separate use cases: exclude_ignored is for searching, ignored_only for maintaining the user's settings. Someone else may combine it into one function. In the OKAPI, it is also just one function.

I would go for deprecation only if is necessary, not for improving the interface style. But I have no strong feelings about this: If you think it should be combined, I can do that.

**Comment by wrygiel** [comment]
I think that improving the interface style is also a valid reason for deprecation. It is natural that over time some parameters, or even whole methods, become old-fashioned. We're not planning on removing deprecated features so there's nothing bad about it. BTW, whenever I deprecate something I also put a `<a>why?</a>` link to the issue describing the reason for the deprecation, to help the users decide if it is still okay to use the deprecated feature.

In that particular case, I just feel a very strong resemblance to the "found_status" parameter, so I'd want all the future boolean flags to be treated in a similar fashion.

**Comment by following5** [comment]
Okay!
