### ISSUE TITLE
search/nearest problem for exakt cache coordinates

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#351]
This Request

> http://www.opencaching.de/okapi/services/caches/search/nearest?consumer_key=$key&format=xmlmap2&center=51.43890|7.464567&radius=0.02&status=Available|Temporarily%20unavailable|Archived

should return OCD346, which exactly has the specified coordinates. Instead, it returns an empty list. The reason is a floating point precision problem in core.php:get_distance_sql():

> $d = "acos(cos($x1) * cos($x2) + sin($x1) * sin($x2) * cos(($lon1-$lon2) * 3.14159 / 180)) * 6371000";

The inner terms can add up to a value which is slightly greater than 1, e.g. 1 + 1e-16, which will produce an acos() result of NULL. I will try to fix it.

**Comment by wrygiel** [comment]
Good catch ;)
