### ISSUE TITLE
Allow utf8mb4 database charset

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#352]
OKAPI as well as current OC code uses the 'utf8' database character set. This is restricted 16-bit Unicode with 1..3 bytes UTF-8 codes.

Since MySQL/MariaDB 5.5, the new charset 'utf8mb4' is supported. This is full 21-bit Unicode with 1..4 bytes UTF-8 codes. Opencaching.DE will migrate to MariaDB 5.5 with utf8mb4 soon. This means:

* The database server ist configured for default utf8mb4 charset and utf8mb4_general_ci collation via my.ini.
* The character set for all databases, tables and text fields is altered to utf8mb4 by dumping tables and re-importing them with 'utf8' replaced by 'utf8mb4'.
* The `SET NAMES 'utf8'` statement for new database connections is changed to `SET NAMES 'utf8mb4'` via a configuration setting.
* Some documentation on db charsets is added.

A similar change is needed for OKAPI, so that it can process utf8mb4 text from the OC database and save utf8mb4 log texts. I suggest the following:

* Add a DB_CHARSET setting, which replaces all database related 'utf8' literals. Default is 'utf8', allowed values are 'utf8' and 'utf8mb4'.
* If someone wants an automatic OKAPI charset migration, he may write some OKAPI update mechanism for that. I don't think it's worth the effort.

Okay?

**Comment by wrygiel** [comment]
Why not simply upgrade OKAPI to utf8mb4?

This won't break anything, even if the rest of OCPL database still uses utf8.

**Comment by wrygiel** [comment]
In other words, I propose to update the `update.php` script so that the next `/okapi/update` call will alter all OKAPI tables and change the charsets and collations. I don't think that any new settings is needed.

I am not 100% sure that won't break anything (should be tested on OCPL before pushing it), but - in theory - it shouldn't.

**Comment by following5** [comment]
> Why not simply upgrade OKAPI to utf8mb4?

It will not work if the database server is older than MySQL 5.5. Whats the DB server version on all the OC.pl developer machines out there? Most OC.de developers still run MySQL 5.0, and have DB update scripts that automatically run OKAPI update.

**Comment by wrygiel** [comment]
Okay, you're right...

I'm a little uneasy about the setting though. Previously, a single "OKAPI database revision" always exactly described a single OKAPI database structure. After your change, it will stop to do that - depending on the timeline of changes of the DB_CHARSET setting, there will be (in theory) 2^N of possible combinations after N database upgrades.

In order to avoid that, we MUST require that every time DB_CHARSET is changes, the user who has changed it MUST alter all OKAPI tables manually and change the charset (and collation). Okay?

Also, please add a reference to this issue in the setting description. :)

**Comment by following5** [comment]
I see that this is a bit tricky. Manual changes are error-prone. Other than I wrote above, it may be wise to implement an automatic charset update mechanism. It could work like this:

At the beginning of the update process, the charset of all OKAPI tables is compared against the DB_CHARSET setting. If they don't match, an upgrade from utf8 to utf8mb4 will be done automatically, while a downgrade request will produce some error message.

**Comment by wrygiel** [comment]
Ok!

**Comment by following5** [comment]
Oh dear, there are columns with different Unicode collations in the same OKAPI tables. This means that besides of the tables' (default) charsets, all fields have to be verified.

**Comment by wrygiel** [comment]
Yes, OKAPI uses `_bin` collations for keys. (In some cases, I also might have used `ascii` charsets, e.g. in case of Consumer Keys or Tokens.) It this a problem?

**Comment by following5** [comment]
No problem, just more work. ;)

**Comment by wrygiel** [comment]
Thanks for your patience :)

**Comment by following5** [comment]
I have run out of time, as the OCDE server migration is scheduled for today and I did not find out yet how to change a table's default charset without resetting the collation of all columns. phpMyAdmin does this somehow. Any workaround like saving the columns collations, then altering the table charset and then changing the columns collations again, looks ugly.

Actually, migrating the OKAPI tables to utf8mb4 would just have one tiny benefit: It would allow Unicode chars > 65535 in consumer names. I don't see any other OKAPI field which would benefit from utf8mb4. So I will go for a simple and quick solution now: Just make the "set names" charset in core.php configurable. This will allow to deal with all utf8mb4 OC database contents. 

There are 'utf8' literals also in SQL statements in by_usernames.php and geocaches.php. I will adjust the first one, while the last one refers to OCPL code only which I currently cannot test. As OCPL sites do not use utf8mb4 yet, this may be changed later.

**Comment by following5** [comment]
Works fine. This issue may be closed for now, as I don't see any need to migrate the OKAPI tables to utf8mb4.

**Comment by wrygiel** [comment]
I agree. I don't think there's a big chance of someone naming their OKAPI app in, say, Chinese. :)

BTW, is there any particular reason you are upgrading OCDE to support the full 4-byte unicode?

**Comment by following5** [comment]
This feature was requested by users who use special Unicode glyphs in mystery listings, like [this](https://www.geocaching.com/seek/cache_details.aspx?wp=GC5E8CD&title=) and [this](https://www.opencaching.de/viewcache.php?cacheid=178634).

**Comment by following5** [comment]
It turned out that Unicode smileys are frequently used in logs, most of them probably via OKAPI.

**Comment by wrygiel** [comment]
Spooky. ;)

**Comment by wrygiel** [comment]
BTW, would submitting this character break the pages? https://en.wikipedia.org/wiki/Right-to-left_mark

**Comment by wrygiel** [comment]
https://www.explainxkcd.com/wiki/index.php/1137:_RTL

**Comment by following5** [comment]
Logs and cache descriptions at OC.de are boxed in "overflow:hidden" `<div>`s, which should prevent that something visible escapes. State changes should theoretically be caught by the HTML Purifier. I did not succeed to insert an RTL mark into a log; you may try [here](https://www.opencaching.de/viewcache.php?cacheid=136478).

If things like RTL may overrun the `</div>`, they could be neutralized by appending appropriate codes to the text.

**Comment by following5** [comment]
Things like [this](http://www.opencaching.de/viewcache.php?cacheid=134903) and [that](http://www.opencaching.de/viewcache.php?cacheid=122621) were produced before purifying.;)

**Comment by wrygiel** [comment]
Right. Forgot about the purifier :)
