### ISSUE TITLE
services/attrs/attribute?acode=invalid&forward_compatible=false produces wrong result

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#354]
Instead of throwing an exception, the result of the `attributes` method for the acode "invalid" is returned, e.g. `{ invalid: { name: null }}`.

Note that the `attributes` method will return `{ invalid: { local_icon_url : null } }` if only this field is requested and either the acode is unknown or the field is not supported by the local installation. Therefore the exception cannot be generated from the result of `attributes`. So I think the case `forward_compatible=false` & invalid acode should be directly caught in attribute.php.

**Comment by wrygiel** [comment]
I think that we need to fix `attributes` method. It should return `{"invalid": null}`, instead of `{"invalid": {"name": null}}`.
