### ISSUE TITLE
Submit logs without time

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#358]
Some time ago, we defined that the time 00:00:00 in a cache log's date (as stored in the OC database) represents "no time specified". However, specifying 00:00:00 in ISO-8601 format is complicated because it needs to be supplied in the *server's* timezone, otherwise the result will be non-null.

I suggest to allow specifying just an ISO-8601 date without time. This will correctly be stored as 00:00:00 in the database by the current OKAPI implementation. So it's just a documentation add-on, explaining how to submit logs without time (e.g. when copying GC logs to OC, or for privacy reasons).

**Comment by following5** [comment]
> Some time ago, we defined that the time 00:00:00 in a cache log's date (as stored in the OC database) represents "no time specified".

See docs of the services/logs/entry "date" field. It says "times truncated to midnight, as in the local timezone", which could be clarified as "... as in the OC installation's local timezone".

**Comment by wrygiel** [comment]
Hmm... previously the developers could assume that whenever they find the string "00:00:00" within, then it's "null". If we allow the server to return values in different timezones, this won't be true. So your suggestions seems a little backwards-incompatible.

**Comment by wrygiel** [comment]
Or, perhaps, I didn't understand what you're proposing exactly.

**Comment by wrygiel** [comment]
Are you suggesting to update the "submit" method or the "logs/entry" method?

**Comment by following5** [comment]
I suggest to update the documentation of the "submit" method and clarify that a date without time may be submitted (which means: the logger did not specify a time).

**Comment by wrygiel** [comment]
Ok, I understand now. You'd like additional information in the "when" parameter. I propose something along these lines:

You MAY skip the time section of the string (yyyy-mm-dd). Note, that some OC servers may add a time of their own in this case (midnight, most probably).

**Comment by following5** [comment]
OKAPI has full control about what time is added, because it directly writes to the OC database: It adds 00:00:00. And no sane OC server will ever tamper with the cache_log dates. The unclear thing is how 00:00:00 will be interpreted by OC servers and clients. Some understand it as "no time given" (as OC.de does), while others show 00:00 (as OC.pl does). So I suggest this:

You MAY omit the time section of the string and just submit a date (yyyy-mm-dd). OKAPI will then add 00:00:00 in the OC server's local time. This may be interpreted by the server and by other client software as midnight or as "no time given".

**Comment by wrygiel** [comment]
The current interpretation of "00:00:00" as "no time given" may change in the future, so I think it's better to not mention it here. It we do, we will need to stick to it, forever.

As far as I remember, we have introduced the "00:00:00 rule" only because we wanted to keep the `date` field (in the log entries) backward compatible. For example, we could introduce a `date2` field later, which would make the time segment optional.

**Comment by wrygiel** [comment]
I didn't think about the problems with the submit method when we first discussed the "00:00:00" problem. :( Now it seems to me that we should address it in a better way. If developers are submitting "00:00:00" just to make the time disappear, then we designed it wrong...

**Comment by following5** [comment]
Well then, what about my proposal in the first posting? To specify "no time", the user shall supply a date without time. I think this will be suffiecently backward compatible, because the current OKAPI specs define *when* as "a date and time string".

This won't need any implementation change, because there is no dedicated "no time" flag in the OC database - the only thing we can do is store 00:00:00.

The reason for this issue is that currently loads of GC logs are inserted with a dummy time of 21:00 into the OC.de database, because the developer had no advice how to handle logs without proper time information (the GC API signals "no time" as "21:00"!)

**Comment by following5** [comment]
We mal also advise to do not submit "00:00:00" for midnight but e.g. "00:00:01", because some server and client implementations will interprete 00:00:00 as "no time specified".

**Comment by wrygiel** [comment]
> Well then, what about my proposal in the first posting? To specify "no time", the user shall supply a date without time.

I agree. But I would also leave all the information about the "00:00:00" problems out.

**Comment by wrygiel** [comment]
Perhaps, simply:

You MAY omit the time section of the string and just submit a date (yyyy-mm-dd).

**Comment by following5** [comment]
What about the sentence "If given, the log will be published with the given date and time." ? It cant's stay this way.

**Comment by wrygiel** [comment]
Ok!

**Comment by following5** [comment]
After lots of more thoughts on this, I think that we may run into timezone related trouble in the future when documenting the 00:00:00, similar to the GC 21:00 which resembles 12:00 Seattle time + a timezone glitch. Here is another proposal:

First paragraph: " ... You MAY and are encouraged to omit the time and just submit a date (yyyy-mm-dd) if the time is unknown or shall not be disclosed."

Second paragraph: "... If only the date is given, OKAPI will publish the log in a way
which most closely resembles "no time given" ([more info](https://github.com/opencaching/okapi/issues/358)).

**Comment by wrygiel** [comment]
> After lots of more thoughts on this, I think that we may run into timezone related trouble in the future when documenting the 00:00:00

Yes, that's exactly what I meant too ;)

> OKAPI will publish the log in a way which most closely resembles "no time given"

And this sounds much better than all the 00-shit. :)
