### ISSUE TITLE
Clean up okapi_stats_hourly

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#361]
Is it safe to clean up old data from this table, e.g. older than a year? It has 10 Mio. recods at OC.de and produces ~ 1 GB of data when being dumped, which I think is half of the whole DB backup amount.

**Comment by wrygiel** [comment]
Before you do that, let's think for a minute.

In general, nothing bad would happen if you did that, but you would have lost all the older statistics. I think it might be better to **convert** these older statistics to a different format.

I was thinking about creating `okapi_stats_monthly` and dumping old stats to this table (e.g. once a month). Implementing this would take me a while. I think it's might be worth waiting though.

**Comment by following5** [comment]
Okay. I would backup the data before, but your solution looks better.

The OKAPI error notifications that you received regarding "Mysql error 23: Out of resources" are mostly related to the huge database dumps, which occupy the database server for too long.

**Comment by wrygiel** [comment]
I have divided the compression task in month-long parts, so it should take ~2 days to complete the task, once the cronjob is installed. The compressed format takes approximately 10 times less space.

**Comment by following5** [comment]
The compression rate at OC.de is 9:1, while the reduction of data amount is just about 50% because 40% of the overall rows were in the last 12-month timespan. Of course it will pay out on the long run.

**Comment by wrygiel** [comment]
If this turns out insufficient:

1. We can drop the user_id column in the monthly stats. In most cases, it will be the consumer stats we need.

2. We can squash fresher data too, e.g. 3 months old.

**Comment by following5** [comment]
Oops, we have a violation of OC.de data privacy terms here. We promise to do no long term recording of user activity, which is very problematic in Germany. Any short-term recording is documented [here](https://www.opencaching.de/articles.php?page=dsb).

So the user_id should be dropped from the monthly stats, and it should be stored in the hourly stats only for a short period. This allows tracking down current technical problems or misusage. User-related statistical evaluation must not be done at all. We have a configuration setting for the number of days user-related data is stored: `$opt['logic']['logs']['purge_userdata']`. It is set to 14 days, which is consistent with the storage time of web server logs.

**Comment by following5** [comment]
Should I open a new issue for this?

**Comment by wrygiel** [comment]
Yes. It seems unrelated to this one.

**Comment by following5** [comment]
OC.de is still struggling with its huge database. I think it would be worth to half the full OKAPI statistics from 12 month to 6 months. Reducing even further would have no significant effect.

**Comment by wrygiel** [comment]
Are you sure the squashing process has already finished? The way I designed it, it would take a couple of days to complete.

**Comment by following5** [comment]
Yes, it has finished some days ago. 22 months were squashed: April 2013 to January 2015.

**Comment by following5** [comment]
But hmm .. if you think the daily statistics for one year is of value, we may continue to look for other solutions. The reduction to 6 month will not give _that_ big save in data amount, and the database is growing at other ends, too. The framwork should be adjusted so that it can handle this.

**Comment by wrygiel** [comment]
You intend to stop using user_id column in OCDE - that should reduce the size of all stats tables 10x or even 100x. Changing 12 months to 6 months wouldn't give you even 2x, I think it's not worth to add a settings for this.

**Comment by following5** [comment]
I was thinking of keeping the user_id just for the last few weeks. But right, that woud still allow to consolidate the horly stats to a fraction of the current number of rows.
