### ISSUE TITLE
Allow user specific log types (disable / archive / ready to search) via OKAPI

### ISSUE THREAD

**Issue by ebillen** [opencaching/okapi#362]
According to the documentation (http://www.opencaching.de/okapi/services/logs/submit.html), the user specific log types (disable / archive / ready to search) are not supported yet.
Clients like c:geo should support these log types, but the OKAPI is a prerequ for that.

See also https://github.com/cgeo/cgeo/issues/4134

**Comment by following5** [comment]
This is a duplicate to issue #260.
