### ISSUE TITLE
Optmize search_nearest

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#363]
The OKAPI method search_nearest produces most of the server load of Opencaching.de. It is rather slow (0,2 seconds per call) because the condition

`$where_conds[] = "$distance_formula <= '".mysql_real_escape_string($radius)."'";`

does not allow any optimization by the SQL server. _All_ caches which meet the other conditions need to be searched. But there is a latitude/longitude index on the ´caches` table which should allow to narrow down the search set for the typical small radiuses.

What about some bounding box condition which is evaluated first? For an 1 km radius in Germany, a simple longitude filter would narrow down the number of caches by ~ factor 700. Only 100 caches need to be checked for the radius and any other search filters. I think it should be worth to apply such a longitude prefilter up to search radiuses of 100 km.

(Btw, the OKAPI stats records are really nice for such performance evaluations :-)

**Comment by following5** [comment]
I assume that the SQL server is not smart enough to chose the most effective index here. Instead, the search by radius allgorithm could query the relation

    count(caches within longitude +/- radius) / count(caches total)

and then decide if it is worth an optimization, e.g. <= 0.3. If so, it could add the condition

    and cache_id in (<list of cache_ids within the longitude range>)

**Comment by wrygiel** [comment]
I was toying with this approach in the past. However, I concluded it won't give much of a boost. Perhaps you will have more luck.

However, keep in mind that bounding box is not so easily calculated, especially when you're getting near the polar regions or the 180 meridian. You might need to make this optimization work only in Poland & Germany.

**Comment by following5** [comment]
For my geocaching homezone, which has an above average cache density, I found that a latitude prefilter gives the following performance boosts, with all other search params set to default (or with archived caches added);

radius 0.1 km:  factor 90 (90)
radius 1 km:  factor 50 (50)
radius 10 km:  factor 2 (5)
radius 50 km:  factor 0.9 (1.0)
radius 100 km:  factor 0.65 (1.3)

In Berlin (higher density) the numbers from 10-100 km go a bit up, while in Croatia (few caches) they go _strongly_ up for 1-100 km. This is all old development data; production data has higher densities in Poland and much more archived caches in Germany.

Overall, I think that an optimization radius of 30 km will be fine in all cases and environments.

**Comment by following5** [comment]
Btw, the "cmanager" application, which is responsible for the heavy use of search_nearest at OC.de, applies radiuses <= 1 km.

OCPL also has a latitude index on the caches table, so the optimization should work the same there.

**Comment by following5** [comment]
100 km optimzation limit is fine also for the OC.de production system. I guess it will also produce acceptable results on the other nodes.
