### ISSUE TITLE
Long-term recording of user activity needs to be removed for OC.de

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#364]
OKAPI currently records user activity in the tables `okapi_stats_hourly` and `okapi_stats_monthly`. However the Opencaching.de data privacy policy only allows such recordings for a short period, usually 14 days, or a maximum of 30 days. This requires changes to both tables' contents.

I suggest this solution:
* The `user_id` is dropped from `okapi_stats_monthly`, which also reduces the data amount to be stored (see #361).
* A cron function is added which nulls the `user_id`s in `okapi_stats_hourly`, as far as the records exceed an age which is configured for the node. (default is infinite)

**Comment by wrygiel** [comment]
I would like to keep user_id in OCPL for now, even in monthly stats.

**Comment by following5** [comment]
It would be nive to have a short-time record (2 weeks) of user stats available, but it's too complicated for me to implement that. So I just discard the OCDE user_ids.

**Comment by following5** [comment]
I will crunch the user_ids in Opencaching.de tables manually.
