### ISSUE TITLE
Allow OC site to use OKAPI cronjobs engine

### ISSUE THREAD

**Issue by wrygiel** [opencaching/okapi#371]
OCPL uses tons of ugly crontab entries in order to run their cronjobs. We could allow the OC site to register their cronjobs in OKAPI's `cron-5` engine.

**Comment by following5** [comment]
Alternatively, OCPL could adopt the OCDE [modular cronjobs](https://github.com/OpencachingDeutschland/oc-server3/tree/master/htdocs/util2/cron). This would avoid to mix data interface (OKAPI) functionality with OC core functionality.

**Comment by wrygiel** [comment]
OKAPI's Facade class is backwards-compatible too, so this type of "mixing" is safe enough. But I guess OCPL developers will do as they wish :)

**Comment by following5** [comment]
I was thinking in terms of overall program structure. OKAPI is an interface layer upon the OC database, which can be used by the OC code alternatively to a direct database access. Providing other services to the OC code would be a whole new thing. But maybe the overall structure of OC(PL) code is already so fubar that it won't make a difference. ;)

**Comment by wrygiel** [comment]
> Providing other services to the OC code would be a whole new thing.

Why? Providing an ability to run cronjobs is just yet another type of service. OKAPI provides various types of services, in a backward-compatible manner, for any OC server to use, via the Facade class. This would be similar.

**Comment by wrygiel** [comment]
There are many such services already exposed there, e.g. caching functions etc.

https://github.com/opencaching/okapi/blob/9c24b5fb56087b553cfc711f9a18e2b3df06ac8b/okapi/facade.php#L87

**Comment by following5** [comment]
Okay, I was not aware of that OKAPI is more than a geocache-database interface.

**Comment by following5** [comment]
I think it would be easier to implement this directly at OCPL than via Okapi. Will make a proposal there.

**Comment by following5** [comment]
This will be implemented in native OCPL code, see https://github.com/opencaching/opencaching-pl/issues/1254.
