### ISSUE TITLE
move english strings to gettext LC_MESSAGES

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#375]
Currently OKAPI has international support for several languages, except english, which are probably hardcoded. 
If the project uses internationalization support as such, then strings in ALL supported languages must be done in a uniform way. 

This is a feature request to move all english strings into LC_MESSAGES using the same internationalization infrastructure as DE, PL, NL, IT.

Thank you.

**Comment by wrygiel** [comment]
But this is just how gettext works, as far as I know. One language is always selected as the default one. And this default language can be edited only by editing the source code.

If we added LC_MESSAGES for English, then it would just be redundant.

**Comment by andrixnet** [comment]
Then how can one translate using english as source language, other then reading through the entire code?

**Comment by wrygiel** [comment]
You use a tool for that. Poedit scans all the source files and extracts all the source content from them.

**Comment by wrygiel** [comment]
You just hit the "update" button, and all the changes from the source code get imported to your current `.po` workspace:

![image](https://cloud.githubusercontent.com/assets/2168535/13551068/933cde18-e32d-11e5-99e6-9942e66869a4.png)

**Comment by following5** [comment]
I think this can be closed with #379.
