### ISSUE TITLE
OKAPI changelog

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#377]
A developer has asked where he can see what features have been added to OKAPI recently. I refered him to the list of closed issues and commits, but well ...

What about adding a changelog, which is linked in the left-hand menu below "Examples"? I could scan the commits of the past years and initialize it.

**Comment by wrygiel** [comment]
Currently the only kind-of-changelog I keep is this one: http://opencaching-api.blogspot.com/

**Comment by wrygiel** [comment]
We could either update the blog page more often, or start keeping a full-featured "changelog / release notes" page. However, I'm not sure if this should be published via OKAPI web interface, or via GitHub. I guess it would be better if there was only one URL people could read it.

**Comment by following5** [comment]
I think the OKAPI documentation is the natural place where developers search for a changelog.

**Comment by wrygiel** [comment]
> I think the OKAPI documentation is the natural place where developers search for a changelog.

Search for - yes. But perhaps we may post a link there (instead of a changelog copy). Changelog is a version-agnostic and installation-agnostic entity. Wouldn't this be a little weird if two OKAPIs would serve two slightly different versions of OKAPI changelog (because changelogs may change, depending on OKAPI version)?

**Comment by following5** [comment]
The changelog may be stored in the 'etc' directory on Github and fetched on demand, so it would be the same everywhere. AND it could be made version- and installation-aware by including version numbers in the raw file (which may be computed from commit IDs by some script). Then it could be presented in two sections: Changes which are not available yet on this site, and changes which are available.

I think this would be a nice feature, giving more transparency about the different installations and enabling developers to kick the site's administrators ass if the installation is too outdated.

**Comment by wrygiel** [comment]
> The changelog may be stored in the 'etc' directory on Github and fetched on demand, so it would be the same everywhere. AND it could be made version- and installation-aware by including version numbers in the raw file (which may be computed from commit IDs by some script). Then it could be presented in two sections: Changes which are not available yet on this site, and changes which are available.

Okay. When you put it this way, I'm starting to like it ;)

**Comment by following5** [comment]
[This script](http://stackoverflow.com/questions/32405922/in-my-repo-how-long-must-the-longest-hash-prefix-be-to-prevent-any-overlap/32406103#32406103) says that currently the left 7 chars of commit IDs are unique in the OKAPI project. Given the explanations [here](http://stackoverflow.com/questions/18134627/how-much-of-a-git-sha-is-generally-considered-necessary-to-uniquely-identify-a), it guess it will be safe for all times to use 8-char IDs in the OKAPI changelog.

**Comment by wrygiel** [comment]
I think we should also refer to `okapi_version_number` (not only `git_revision`).

Version numbers are integers and developers will be able to test if existing OKAPI installations are "older" or "younger" than any particular version number. (E.g. if `version >= 1238` then allow sending images, etc.)

**Comment by following5** [comment]
> I think we should also refer to okapi_version_number (not only git_revision).

Sure. Enter commit IDs, have version numbers calculated - that's what I meant four posts above. ;)

**Comment by wrygiel** [comment]
http://opencaching.pl/okapi/changelog_feed

**Comment by wrygiel** [comment]
[Sat Apr 09 19:26:33 2016] [error] [client 91.42.94.215] PHP Parse error:  syntax error, unexpected T_STRING in /var/www/ocpl/okapi/views/changelog_feed.tpl.php on line 1

**Comment by following5** [comment]
No idea what's going on there - it works fine on OCDE systems. I will disable the feed for OCPL sites.

**Comment by following5** [comment]
Also, the SVG-format RSS icon was broken on http://www.opencaching.nl/okapi/changelog.html. I chose it because it's free (public domain) and scales without blurring. SVG works fine on all relevant browsers, except for MSIE < version 7 which surely no OKAPI developer uses.

**Comment by following5** [comment]
> http://opencaching.pl/okapi/changelog_feed

fixed

**Comment by wrygiel** [comment]
Thanks!

**Comment by following5** [comment]
> http://opencaching.pl/okapi/changelog_feed

It's the short open tags. When they are enabled, this ...

`<?xml version="1.0" encoding="UTF-8"?>`

will be parsed as PHP code. That's exactly the reason why short open tags are deprecated.

**Comment by wrygiel** [comment]
> That's exactly the reason why short open tags are deprecated.

AFAIK, they won't be allowed on our new server.
