### ISSUE TITLE
replication of log entry 'was_recommended' changes does not work

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#382]
The OKAPI replication mechanism will not notice if a user adds or withdraws a recommendation by editing a log entry, because this only changes the contents of the cache_rating table. cache_logs.okapi_syncbase needs to be updated. I will do this via trigger in OCDE code.

**Comment by following5** [comment]
Note: The replication of the geocache's recommendation count works properly on both OCPL and OCDE; it's just the cache_logs entry which is not affected by the rating change, in both code branches.

**Comment by following5** [comment]
@wrygiel 
Can you verify if OCPL docs/sql/stored-proc/triggers-create.sql is up-to-date? There may be new triggers for updating some modification date fields. (If not, the OKAPI replication changelog is very incomplete at OCPL sites, e.g. not tracking changed description texts).

**Comment by wrygiel** [comment]
Note that OKAPI performs a full checkup daily. I am unable to keep all of external code at bay regarding proper handling of `okapi_syncbase`, so I did this instead.

**Comment by wrygiel** [comment]
This daily checkup is quite expensive, but necessary.

**Comment by wrygiel** [comment]
As to the triggers, you can review the exact code of the currently installed ones here: http://opencaching.pl/okapi/devel/dbstruct

**Comment by wrygiel** [comment]
However, I'm not sure if cache logs are also checked during this checkup... If not, then indeed, something would need to be fixed...

**Comment by wrygiel** [comment]
BTW, we have just one `replicate` consumer in OCPL. This module doesn't get much of developers' attention.

**Comment by following5** [comment]
> However, I'm not sure if cache logs are also checked during this checkup... If not, then indeed, something would need to be fixed...

It is not done for the log entries.

(Regarding the geocache records, I will open a separate issue.)

**Comment by following5** [comment]
Oh dear, I should fully test it instead of just reading parts of the source code. :/

There is no problem at all - the fix for OCDE has already been implemented years ago, and OCPL will always update cache_logs.last_modified when editing a log entry, even if nothing is changed.

I will document this thing now in OKAPI, OCDE and OCPL source code and think we then can leave it this way.

**Comment by following5** [comment]
Doing a full verification for 1 Mio. log entries would make OKAPI independent from the OC implementations, also be quite expensive. Do you agree that for now, we can leave it this way?

**Comment by wrygiel** [comment]
I agree. Full verification would also require OKAPI to keep a copy of all log entries (or at least a hash for each), so it would be also expensive in regard to disk-space. I don't think we need to care for this now.
