### ISSUE TITLE
replicate/changelog delivers inconsistent geocache data for OCPL sites

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#383]
The OCPL field `caches`.`okapi_syncbase` currently is not updated, if

* the short description, long description or hint is edited,
* a picture entry is edited,
* additional waypoints (OKAPI `alt_wpts`) are added, edited or removed,  [change: additional waypoints are ok, see below]
* the administrative location is updated (OKAPI fields `country` and `state`),
* the nature protection areas information is updated,
* the trackables in the geocache change.

Therefore it will take up to 24 hours until these changes pop up in OKAPIs changelog, while all other changes are updated within 5 minutes. That is no problem for trackables, and for admin locations and NPAs. But consider this:

* The geocache is moved; coordinates, description and hint are updated. Then the changelog delivers the new coordinates with outdated description and hints. 

* A traditional cache is converted into a mystery. Then the changelog delivers the new cache type, but the instructions on how to find the cache are missing.

* A "Temporarily unavailable" multicache is activated with changed information about the stages. The changelog will deliver the _old_ stage description with the state "Avaliable".

A quick workaround would be to disable the 5-minute-updates for OCPL and just run the full check once a day (or even multiple times a day). For OCDE, the database triggers take care of all this and update `okapi_syncbase`.

**Comment by wrygiel** [comment]
I think that some level of inconsistency if acceptable for some time. This SHOULD be solved by triggers in OCPL too, but I currently don't have the time to set them up.

**Comment by following5** [comment]
This may also be considered as an OCPL bug, because the geocache's last_modified date - as displayed in the listings and delivered through OKAPI - is not updated. I will open an OCPL issue for this.

**Comment by following5** [comment]
> additional waypoints (OKAPI alt_wpts) are added, edited or removed

alt_wpts are fine, I was wrong on that.

**Comment by wrygiel** [comment]
> geocache's last_modified date (...) is not updated

You're right, fixing that on OCPL would solve the issue!

**Comment by following5** [comment]
For the same reasons, the OKAPI geocache(s) methods will output an outdated `last_modified` date after description changes or editing pictures, as the OCPL websites do.
