### ISSUE TITLE
Register date in user info

### ISSUE THREAD

**Issue by mzylowski** [opencaching/okapi#384]
I prepare new RR/COG election site for OC.pl. We also want to disconnect with OC database (https://github.com/opencaching/opencaching-pl/issues/322). I need to get information about register date of the user, because only users register more than one month before elections can vote.
Maybe somebody can add this field into :: services/users/user (http://opencaching.pl/okapi/services/users/user.html) ?
Polish RR team need this election script in April, so this field should be add in next two weeks. There is any chance to do it?

**Comment by wrygiel** [comment]
Should be very easy to add.

**Comment by wrygiel** [comment]
Done.

**Comment by following5** [comment]
For privacy reasons, I would like to restrict this field to date only. It's of no public intererest at which time of day the user registered.

**Comment by wrygiel** [comment]
Ok. What format do you propose in this case? We've been using these ISO strings everywhere else so far.

**Comment by following5** [comment]
ISO date would be fine. yyyy-mm-dd
