### ISSUE TITLE
Revoking a consumer key

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#387]
Together with an application developer, I am thinking about revoking a consumer key so that all users of the application are forced to update to a new version. Generally I think this should be possible, for the case that some OKAPI client runs mad.

As far as I understand, this is currently only possible by altering this `consumer_key` in all OKAPI tables in the same way - so the histories would stay intact. Am I right with this? If yes: What do you think about adding a flag FLAG_REVOKED which is set in `okapi_consumers`.`bflags`, and then OKAPI will output a proper error message when this key is used?

**Comment by wrygiel** [comment]
> and then OKAPI will output a proper error message when this key is used

Hmm... the proper error message in this case would be "This key has been revoked". Such error messages are aimed at developers. In general, they should not be even displayed to the users. And even this app displayed this error message to the user, it wouldn't suggest much (how would the user know that his app needs updating?).

**Comment by following5** [comment]
The message might be: "Your application was denied access to the Opencaching.XX site (OKAPI consumer key was revoked)." The user would then naturally contact either the OC site or the developer for further information. Yes, the application may not display the error message - then the user will still contact the developer or the OC site to find out what's going on.

**Comment by wrygiel** [comment]
I'm not sure if this is "user friendly" :) But the ability of revoking consumer keys is a good feature to have either way, so I won't object. ;)

**Comment by wrygiel** [comment]
It's not so easy ;) I think you have just revoked it in a single place, but consumers are used in many other places. For example, your change will still allow the consumer to call services with OAuth. Or to acquire new request tokens. Etc.

**Comment by following5** [comment]
> For example, your change will still allow the consumer to call services with OAuth. 

This is fixed now. I don't know how to do the rest, but this should already effectively block a disabled consumer.

**Comment by wrygiel** [comment]
Yes, I think it's okay now.

**Comment by andrixnet** [comment]
Where can one find instructions for an administrator on how to perform such a revocation ?

**Comment by following5** [comment]
Use this SQL to revoke a consumer key:

```
update okapi_consumers set bflags = bflags | 4 where okapi_consumers.`key` = 'insert-key-here'
```
and this to reenable it:

```
update okapi_consumers set bflags = bflags & ~4 where okapi_consumers.`key` = 'insert-key-here'
```

**Comment by wrygiel** [comment]
Later on, we may probably add a command line script to aid with such things. Currently, I don't think it's necessary.

**Comment by andrixnet** [comment]
Please add the instructions above to  /okapi/introduction.html (or the corresponding page)
