### ISSUE TITLE
interactivity=confirm_user doesn't work? 

### ISSUE THREAD

**Issue by mzylowski** [opencaching/okapi#389]
I made something like that in my php code:
header('Location: http://opencaching.pl/okapi/services/oauth/authorize?interactivity=confirm_user&oauth_token='.$request_token_info['oauth_token']);

I don't have to relog in oc.p after redirection.
Also in application accept page URL is:
http://opencaching.pl/okapi/apps/authorize?oauth_token=GTNJBVeYrZ... (without interactivity field).

It is OKAPI problem or I made something wrong?

**Comment by wrygiel** [comment]
You're right. Something stopped working.

**Comment by wrygiel** [comment]
For OCDE it's even worse!

![image](https://cloud.githubusercontent.com/assets/2168535/13843151/46deee90-ec32-11e5-9a7c-7a3244bade83.png)

**Comment by following5** [comment]
This ...

```php
                $past = time() - 86400;
                foreach ($_COOKIE as $key => $value)
                    setcookie($key, $value, $past, '/');

```

... will have bad side effects on OCDE, destroying settings that are stored in cookies. OCDE has a `login.php?action=logout&target=…` facility, which can be used for logging out. Targets can be nested, so that OKAPI can redirect to `login.php?action=logout&target=…`, which redirects to `login.php?target=…`, which redirects to `okapi/apps/authorize`.

Of course that won't solve the problem for OCPL. I also don't understand the OCPL session handling.

**Comment by following5** [comment]
OCPL `logout.php` (meanwhile?) also has a `target` parameter! So this cookie-deleting can be replaced by calling the OC logout script for all sites.

**Comment by wrygiel** [comment]
For the time being, I will commit a solutions for OCPL (aka "destroy everything"), and you can later commit a better solution for OCDE.

> OCPL logout.php (meanwhile?) also has a target parameter!

Which doesn't work ;) Or, it didn't work when I was implementing this.

**Comment by following5** [comment]
> Which doesn't work ;) Or, it didn't work when I was implementing this.

Your're right, OCPL logout.php won't work without supplying some magic code.

**Comment by wrygiel** [comment]
BTW - could you make your OCDE login page automatically redirect to target if the user is already signed in? I think it's a bug to display an error in this case.

**Comment by following5** [comment]
I am not sure if there is any other buggy code which depends on this behaviour. Inside OCDE code, nothing would benefit from changing this. But I can add a parameter for that, for external applications.

**Comment by wrygiel** [comment]
> Inside OCDE code, nothing would benefit from changing this.

E.g. a user opens 20 private-area tabs, closes his browser, his session ends, reopens his browser, all 20 tabs get redirected to the login page, he signs in on the first tab, and then hits F5 on the other one. He might expect to get redirected to the originally open tab, but gets an error.

**Comment by wrygiel** [comment]
Perhaps this seems far fetched, but actually I myself do this quite often ;)
