### ISSUE TITLE
authorize with interactivity=confirm_user destroys OCDE settings

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#390]
The code in views/apps/authorize.php will destroy all cookies if called with 'confirm_user' option. Instead, it should call logout.php for OCDE.

**Comment by wrygiel** [comment]
BTW, why do you keep settings in client-side cookies? Keeping them server-side (or in session) seems a better choice.

**Comment by wrygiel** [comment]
BTW2, in general, `confirm_user` should first ask the user if he's "the proper one", and then offer to sign in as a different user. I simply didn't have time to implement it this way.

**Comment by following5** [comment]
> BTW, why do you keep settings in client-side cookies? Keeping them server-side (or in session) seems a better choice.

Opencaching.de allows much more access for non-logged-in users than OCPL sites. Cookies are the only way to store settings for them - e.g. the settings for the search form. Another example are cookies which shall be discarded when the browser is closed, e.g. the last-entered log entry date.

**Comment by wrygiel** [comment]
Ok, thanks.

**Comment by following5** [comment]
> I simply didn't have time to implement it this way.

me too ;)
