### ISSUE TITLE
search_and_retrieve: Invalid delegation of permissions?

### ISSUE THREAD

**Issue by wrygiel** [opencaching/okapi#391]
## Quote from https://github.com/opencaching/okapi/issues/18#issuecomment-198069376 by @bartekchlebek

Is it possible to use this method in conjunction with a `search_method` configured so it requires **Level 3 authentication**?

e.g.
Say I use `services/caches/search/all` for `search_method`
and set `found_status` to `found_only` which requires **Level 3 authentication**

Even though I sign `services/caches/shortcuts/search_and_retrieve` using Access Token, I receive such response:
```json
{
  "error": {
    "developer_message": "Parameter 'search_params' has invalid value: Search method responded with the following error message: Parameter 'found_status' has invalid value: Might be used only for requests signed with an Access Token.",
    "reason_stack": [
      "bad_request",
      "invalid_parameter"
    ],
    "status": 400,
    "parameter": "search_params",
    "whats_wrong_about_it": "Search method responded with the following error message: Parameter 'found_status' has invalid value: Might be used only for requests signed with an Access Token.",
    "more_info": "http:\/\/opencaching.pl\/okapi\/introduction.html#errors"
  }
}
```

Am I supposed to include oauth parameters for `services/caches/search/all` in `search_params`? The documentation doesn't touch this subject at all.

**Comment by wrygiel** [comment]
Confirmed.

**Comment by wrygiel** [comment]
I wonder how no one noticed this before. Probably developers tried, but never thought to submit an issue. ;)

**Comment by wrygiel** [comment]
Oops. Sorry. Unconfirmed.

Just tested this again and it seems to be working correctly. In my previous tests I didn't use the Access Token correctly...

**Comment by wrygiel** [comment]
![image](https://cloud.githubusercontent.com/assets/2168535/13888702/1cf80bd6-ed43-11e5-8b78-39ab744b7429.png)

**Comment by wrygiel** [comment]
> Even though I sign services/caches/shortcuts/search_and_retrieve using Access Token

Please verify if you really have included the Access Token in this request. If you did, then could you attach the exact dump of your request? Perhaps you're using the (unsupported) `Authorize` header?

**Comment by wrygiel** [comment]
@bartekchlebek

**Comment by bartekchlebek** [comment]
I double checked and guess what, found a bug in my code.

**Works fine** :white_check_mark: 

Thanks for looking into this so quickly @wrygiel

**Comment by wrygiel** [comment]
;)
