### ISSUE TITLE
Reporting geocache codes

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#393]
There is a new API at OCDE to report additional geocache codes, e.g. the GC code of an OC cache which is not included in the cache listing. The reported codes will be reviewed by the OC team and eventually stored in `caches`.`wp_gc_maintained`, which is used for several purposes.

It would be nice to move this API to OKAPI with Level-3 Authentication. Note that it would also be nice to add a method for _reporting geocaches_ to the OC team, i.e. caches wich may need to be disabled. Both features have in common that they report something to the OC team.

What do you think of something like this:
* services/report/geocache
* services/report/external_cache_code
* services/report/other   (will send an email to the OC team)

?

**Comment by wrygiel** [comment]
@opencaching/opencaching-pl-lead-programmers might be interested in this too.

1. @following5, each "OC Team" member in OCPL is bound to one province of the country. Would it be possible to send these reports directly to OCPL Team members, based on the position of the report?

2. @opencaching/opencaching-pl-lead-programmers, do you have any admin interface for your OC Team where you would like such reports to be inserted (rather than sent directly to email box)?

**Comment by following5** [comment]
This issue is just about reporting external geocache codes, e.g. GC codes. That's an OCDE-only feature; the codes are inserted into the table `waypoint_reports` and then will be processed. I just mentioned the other two things because they may considered e.g. when naming the method for cache-code reports.

(For reporting geocaches, both OCPL and OCDE have a well-defined process. They are inserted into the OCDE `cache_reports` / OCPL `reports` table and then will pop up in the admin interface. But that's a separat issue which I currently do not intend to implement).

**Comment by wrygiel** [comment]
> But that's a separat issue which I currently do not intend to implement

So the 3 methods you write above would be all for OCDE only?

**Comment by following5** [comment]
Only one of them - the one this issue is about - would be OCDE only.

(Regarding the "geocache reports", I could do that right away also for OCPL, it's clear how it works. The third one is just a vague idea, that would need further discussion.)

**Comment by following5** [comment]
>  services/report/geocache
>  services/report/external_cache_code
>  services/report/other (will send an email to the OC team)

I think this is better: 

* services/geocache/report_problem
* services/geocache/report_wayoint
* ... and add the site's contact email address to apisrv/installation

**Comment by following5** [comment]
Sry, new try:
* services/caches/report_problem
* services/caches/report_wayoint
* ... and add the site's contact email address to apisrv/installation

**Comment by wrygiel** [comment]
Could you propose it in a commit with XML documentation?

**Comment by following5** [comment]
Yes, later.

**Comment by following5** [comment]
I was too early with my proposal for a report-waypoint-method: There is a related issue at Opencaching.de which must be solved first. So I close this for now, but I will go on with the other proposed method: Reporting problems with geocaches.
