### ISSUE TITLE
Query OC site parameters through OKAPI

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#398]
This is a spin-off from [this issue](https://github.com/opencaching/opencaching-pl/issues/412) in OCPL project.

SammysHP wrote:

> if platforms decide to provide different subsets of the OKAPI functionality, this must be declared in the API interface and signaled to c:geo in some way.

I answered:

> The OKAPI philisophy is to compensate for differences between OC sites as far as possible, so that client developers need not to care about that. 
> ...
> But yes, there are some other differences between OC sites which OKAPI is not able to compensate for, so I agree that the feature of signaling site capabilites to the clients should be added to OKAPI. 

Wrygiel replied:

> I'm afraid adding this would be both very difficult and backward-incompatible.

There are lots of differences in the behaviour of OC sites. OKAPI currently does not explain which site behaves like what, so client software cannot be adjusted to that. E.g. if a was an application developer, I would like to disable or hide the `rating` and `powertrail` search options when searching on an OC site that do not implement these features.

My idea is to create a "site attributes" dictionary - an XML file in the 'etc' directory, which may effectively contain values like these for OCDE

```
service.caches.search.rating = unavailable
service.caches.search.powertrails = unavailable
service.caches.search.cache_types = Traditional,Multi,Quiz,Math/Physics,Virtual,Event,Webcam,Moving,Drive-In,Other
service.logs.submit.needs-maintenance-2logs = false
service.logs.submit.type.plaintext = functional
```

and these for OCPL:

```
service.caches.search.rating = available
service.caches.search.powertrails = available
service.caches.search.cache_types = Traditional,Multi,Quiz,Virtual,Event,Webcam,Moving,Podcast,Other
service.logs.submit.needs-maintenance-2logs = true
service.logs.submit.type.plaintext = dysfunctional
```

The method's docs would document which site attributes can be queried to find out the behaviour for the current site, through a method like 'apisrv/site_parameter'.

Parameters should only be exposed for things where developers will substancially benefit from it, e.g. it should not be exposed if a site provides preview images or alt_wpts.user-coords. Except if OKAPI implements the feature "submit caches", then this would be useful.

**Comment by wrygiel** [comment]
> if a was an application developer, I would like to disable or hide the rating and powertrail search options when searching on an OC site that do not implement these features.

Ok, perhaps you're right and some of these attributes would make sense. But we should not require developers to read them (this should be optional task, only for the most pedantic ones).

> an XML file in the 'etc' directory

Why not fields/methods in `apisrv`? All of these attributes may change in time. If application developers want to differentiate between installations, then we must allow them to easily query for changes.

**Comment by following5** [comment]
> Why not `fields/methods` in apisrv?

Sure. I was thinking of something like the attribute definition file, which is not directly exposed but through a method.

But the method would be somewhat redundant to apisrv/installation. What about just adding the additional site properties there? And add a method to query single values from the apisrv/installation dictionary.

**Comment by andrixnet** [comment]
cc: andrixnet

**Comment by SammysHP** [comment]
In c:geo we request from gc.com which log types are available for a cache. This is done whenever the logging activity is started, so it does not work for quick logging or without Internet. There are rules in the GC connector which predict the available log types in these cases.

For OC we have only a single OKAPI connector that is used for all OC platforms. While it is possible to hardcode the available features, it would be nice to request them somehow.

On the other hand it would be great if OC platforms would be more homogenous.

**Comment by wrygiel** [comment]
> But the method would be somewhat redundant to apisrv/installation. What about just adding the additional site properties there?

Ok! (that's what I meant by "fields")

> And add a method to query single values from the apisrv/installation dictionary.

You mean the "fields" parameter?

**Comment by wrygiel** [comment]
> On the other hand it would be great if OC platforms would be more homogenous.

It would be! But unfortunately we cannot do much about it.

**Comment by following5** [comment]
> You mean the fields parameter?

Yep.

> In c:geo we request from gc.com which log types are available for a cache

This depends on the cache and the logging user, so it cannot be represented by a static field as suggested above. It would need a new oauth-3 method, which is called with the cache type and returns the allowed log types.

Also, it's not just the log type, but there are additional flags like 'needs maintenance' (implemented), 'listing is outdated' and 'is an OC team comment' (not implemented yet) which are site- and user-dependent. It's even more complicated, because the supported flags may depend on the log type. In the future there may be even more dependencies between log parameters.

So it would need some elaborate method for querying such site parameters, which is supplied with params like cache_code etc. Then, to avoid redundancy, the logs/submit method should be rebased onto this site-param-query method. Lots of work.

**Comment by wrygiel** [comment]
> Then, to avoid redundancy, the logs/submit method should be rebased onto this site-param-query method.

I agree. This would the best way to go, but there's lots of weird edge cases involded, and I don't think we want this now.

I believe that external developers don't necessarily need the **exact** set of possible log types. A **superset** would be enough, for starters.

In other words, we could make an `apisrv/installation` field named `possible_log_types`, and it would include **all** possible log types supported by OKAPI in this installation. If would be up to the particular user (not the developer) to determine if a particular log type can be submitted for a particular cache. If the user judges wrong, then OKAPI will respond with `{"success": false, ...}`.

This way, external apps will never miss a log type. Some of these log types will not be valid for particular user and cache of course, but that's not such a big issue (while missing log types are!).

**Comment by wrygiel** [comment]
BTW, I guess that the `possible_log_types` field would also need to include translations in different languages.

**Comment by following5** [comment]
> I believe that external developers don't necessarily need the exact set of possible log types.

They don't necessarily need it, but they still may want to have it. And then start to work around OKAPI and rely on undocumented behaviour, writing their own switch statements for different OC sites, cache types, cache states and so on. Improve the usability of applications by not confusing the users with dysfunctional options. As SammysHP wrote:

> While it is possible to **hardcode** the available features, it would be nice to request them somehow.

But I am reluctant, too, to implement such a complex thing.

**Comment by wrygiel** [comment]
> But I am reluctant, too, to implement such a complex thing.

That was my point ;) Better to implement something simple, than nothing.

**Comment by wrygiel** [comment]
(`possible_log_types` seems simple enough, and would be very useful)

**Comment by following5** [comment]
> (possible_log_types seems simple enough, and would be very useful)

Currently all OKAPI installations can submit the same log types, so I don't think that this would be useful now. Differences in available types arise from cache types, cache states, cache owners and previous logs.

**Comment by following5** [comment]
>>   (possible_log_types seems simple enough, and would be very useful)

> Currently all OKAPI installations can submit the same log types, so I don't think that > this would be useful now. Differences in available types arise from cache types, cache > states, cache owners and previous logs.

I missed that a list of available log types is useful exactly for those differences that arise from complex preconditions. No chance for developers to figure out on their own, what log features are currently available for a cache.

This is solved now by adding the new [services/logs/capabilities](https://opencaching.pl/okapi/services/logs/capabilities.html) method (c288aa0f).
