### ISSUE TITLE
Allow submitting more logs types

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#400]
Ref: https://github.com/cgeo/cgeo/issues/5539#issuecomment-202280968
Ref: https://github.com/opencaching/opencaching-pl/issues/412
Ref: https://github.com/opencaching/okapi/issues/398

According to c:geo developers, some log types cannot be submitted via c:geo to OPENCACHING-PL websites because OKAPI does not support them. 

This is a feature request that OKAPI implement log retrieval and log submission for all log types supported by OPENCACHING-PL (at this time, with changes and addition in the future, as they come).

**Comment by following5** [comment]
There is already the issue #260 for implementing log types which may change the status of the cache.

This issue (#400) probably is about the OCPL log type "Maintenance performed", which does not change the geocache status and therefor may be handled separately.

**Comment by andrixnet** [comment]
Then this is also about log type "maintenance required", which also does not change cache status.

**Comment by following5** [comment]
> Then this is also about log type "maintenance required", which also does not change cache status.

That's already available in OKAPI, and I have already opened an issue in the c:geo project so that it may be implemented there. You have referenced it above.

**Comment by andrixnet** [comment]
```
        if (
            $needs_maintenance2 == 'false'
            && Settings::get('OC_BRANCH') == 'oc.pl'
        ) {
            # If not supported, just ignore it.

            self::$success_message .= " ".sprintf(_(
                "However, your \"does not need maintenance\" flag was ignored, because ".
                "%s does not yet support this feature."
            ), Okapi::get_normalized_site_name());
            $needs_maintenance2 = 'null';
        } 
```

Is this correct? 
Shouldn't the string read: 
> However, your "**needs maintenance**" flag was ignored, because %s does not yet support this feature.

or
> However, your "**maintenance performed**" flag was ignored, because %s does not yet support this feature.

From what I read in submit.php and this issue, this would seem the logical text.

**Comment by following5** [comment]
Did you also read the [docs](http://local5.opencaching.de/okapi/services/logs/submit.html) on 'needs_maintenance2'?

**Comment by wrygiel** [comment]
Broken link ;) This one should work: http://www.opencaching.de/okapi/services/logs/submit.html

@andrixnet - it seems correct to me.

**Comment by andrixnet** [comment]
Then my understanding was incorrect. Thank you for the context clarification.

**Comment by andrixnet** [comment]
RO translations: https://github.com/opencaching/okapi/pull/404

**Comment by following5** [comment]
Split into two issues, #400 for status-changing logs and #548 for OCPL "maintenance performed" logs
