### ISSUE TITLE
attribute-definitions.xml - per URL or per OC code branch?

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#401]
OKAPI holds what seems to be an almost complete collection of attributes in attribute-definitions.xml.
They are divided into 2 main let's say sections: Groundspeak attributes (aka geocaching.com) and Opencaching attributes. The latter are however taken on a per website basis. 

Wouldn't it be more logical to divide them into 3 main sections: 
- Groundspeak
- OC DE branch
- OC PL branch

Since OC DE based websites are actually a single instance on a single server and OC PL websites are in sync with the project master code branch. 
I am not counting US and UK since they are old forks (2009/2010?), AFAIK not updated.

It seems logical for either OC code branch (DE and PL) to define their own set of attributes. And OKAPI has to take this into considerantion. 
It also seems logical for OC PL based websites to use a common set of attributes, as defined by the OPENCACHING-PL project master branch. 

For both of the above it is concievable that maybe a subset of the attributes are disabled at some point in time by administrative decision. This means they are not actively used, but they still exist in the code base. 
Also seems logical that OKAPI, while it knows about all the attributes supported by a certain OC branch, if some of them are disabled for a certain node, OKAPI should remain unaffected, it would simply never return data for those attributes, for they are not assigned to any cache.

I believe this line of thought should also help simplify the management of the attribute-definitions.xml file.

**Comment by following5** [comment]
> and OC PL websites are in sync with the project master code branch

Their code is synced, but the attributes are not defined in the code but inside the database table `cache_attrib`. And this table has other contents at Opencaching.NL than on all other OCPL sites: OC.NL has a mixture of OCPL and OCDE attributes. So Opencaching.NL needs to be handled separately.

**Comment by andrixnet** [comment]
I know there is a tendency for OPENCACHING-PL to move definitions out of the database to the code. AFAIK cache types (at least) have been changed this way already.
Based on this premise, is the above line of thought valid?

**Comment by following5** [comment]
Yes. For the details, see #70.

**Comment by wrygiel** [comment]
> I know there is a tendency for OPENCACHING-PL to move definitions out of the database to the code. AFAIK cache types (at least) have been changed this way already.

My initial thought is: OCPL should use OKAPI's `services/attrs` module internally in this case. And update their attribute definitions directly in OKAPI's `attribute-definitions.xml` file.

If it turns out that all OCPL-based installations will want to use the same set of attributes, then we will change the our schema to support this.

**Comment by andrixnet** [comment]
https://github.com/opencaching/opencaching-pl/issues/462
