### ISSUE TITLE
Romanian translation for attribute-definitions.xml

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#402]
This is an explicit reminder for @andrixnet (me) that attribute-definitions.xml must be also translated into romanian language and have http://www.opencaching.ro schema entries added.

**Comment by following5** [comment]
I don't see any need to introduce a http://www.opencaching.ro schema which would be 100% redundant to the http://www.opencaching.pl schema. This would make sense if Opencaching.RO has a different attribute set than Opencaching.PL.

**Comment by wrygiel** [comment]
There are two separate issues:

1. Adding translations via `<lang>` elements.

2. Binding attributes via `<opencaching>` elements. If OCRO uses exactly the same set of attributes (and other dictionary-like entries), then you can set `ORIGIN_URL` to `http://opencaching.pl/` in OCRO settings. If you do so, OKAPI will "copy" OCPL's attributes to your site (without the need to include new `<opencaching>` entries in the `attribute-definitions.xml` file).

**Comment by andrixnet** [comment]
I will review the attribute list. 
AFAIK there one (a few) attributes extra, that did not exist in the set in 2014.
They may remain so, or be integrated with all OPENCACHING-PL nodes, if they find it useful, relevant.

I also opened this https://github.com/opencaching/opencaching-pl/issues/462

**Comment by wrygiel** [comment]
After https://github.com/opencaching/okapi/issues/417 is merged, attribute definitions will need to contain proper `<opencaching schema="OCRO">` entries. Otherwise OCRO's OKAPI will stop recognizing your attributes. Would you like me to create these elements for you, based on the OCPL ones?

**Comment by wrygiel** [comment]
It seems you have lots of `MISSING A-CODE MAPPING` errors and other notices. Please see "Attribute notices" section here: http://www.opencaching.ro/okapi/devel/attrlist

**Comment by andrixnet** [comment]
will take a look at it this week

**Comment by andrixnet** [comment]
WIP

**Comment by andrixnet** [comment]
Can you help obtain a table (SQL or CSV) with the following info from both OC database and attribute-definitions.xml ? 

`Acode | category | english_name | ocde_id | ocpl_id | ocnl_id | ocro_id | gc_id | gc_inc | gc_name`

**Comment by following5** [comment]
You may want to have another look at http://www.opencaching.ro/okapi/devel/attrlist and check the ro translations which differ in OKAPI and locally.

**Comment by andrixnet** [comment]
Attributes have field size limitations in database (smaller). I've chosen several attributes to be named slightly different for this reason, though they mean the same, or translation improvement will follow.
