### ISSUE TITLE
Return all uuids when submitting a log

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#403]
logs/entry/submit may create two log entries, but returns just one of the uuids. It may be useful for developers to know both of them.

In the future, even three log entries may be created. E.g. if an OCPL team member submits a "temporarily not available" log for a cache that urgently needs maintenance: Log types 'OC team comment', 'temporarily not available', 'needs maintenance'. At OCDE we already have such logs.

What about adding a `log_uuids` return value, as an array which can contain any number of logs? Or is empty in case of an error.

**Comment by wrygiel** [comment]
Sounds good.

Does this mean the `log_uuid` would be deprecated?

**Comment by following5** [comment]
That's an interesting question, which triggers additional questions.

Could we define some 'primary log entry'? The oldest one, oder the one with the comment text? Then I think there is no need to deprecate it.

If yes: would it make sense to put the comment always into the log entry which corresponds to the log type, to get some determinstic behaviour? OKAPI currently handles this inconsistently, and I think it would be fine to change it. I.e. move the comment for DNF + needs maintenance into the DNF log.

I guess you will not like such determinations. :) They help some client developers, but restrict OKAPI development.

**Comment by wrygiel** [comment]
These problems will escalate if we ever decide to introduce `services/logs/edit` method. If a user tried to edit a single log entry, should OKAPI be able to update multiple log entries based on this call?

> OKAPI currently handles this inconsistently, and I think it would be fine to change it. I.e. move the comment for DNF + needs maintenance into the DNF log.

You could change it for OCDE is you prefer it the other way around. For OCPL, I would rather keep the current assignment.

**Comment by following5** [comment]
> These problems will escalate if we ever decide to introduce services/logs/edit method. If a user tried to edit a single log entry, should OKAPI be able to update multiple log entries based on this call?

I don't think so. After submitting, the logs are logically independent on the OC site - they are not connected in the database. So it should be fine to edit them separately.

> You could change it for OCDE is you prefer it the other way around. 

This is an OCPL-only issue! 1 OKAPI log = 1 OCDE log, always.

Then, I think `log_uuid` shoud be deprecated, and it would be nice to add a flag to the 'installation' method: "This site may create multiple log entries from one log submitted via OKAPI".

**Comment by wrygiel** [comment]
> After submitting, the logs are logically independent on the OC site - they are not connected in the database. So it should be fine to edit them separately.

But some of such edits would spawn new entries, or delete existing ones, e.g. adding or removing the "needs maintenance" flag. There is no direct connection in the database, but both entries have the same author and the same date, so there is some room for hacking.

> OKAPI log = 1 OCDE log, always.

In the future too? If this is really OCPL-only, then perhaps we can just leave it as it is for now?

**Comment by following5** [comment]
> But some of such edits would spawn new entries, or delete existing ones, e.g. adding or removing the "needs maintenance" flag.

OCPL completely forbids to change the type of existing logs, so there is no problem.

Besides of that, it is a _fact_ that multiple uuids are generated. We can provide a clean interface to that, or leave it up to developers to retrieve log lists and compare user IDs and dates ...

> In the future too?

I will do my best that it stays this way.

**Comment by following5** [comment]
But I can live with declaring this low-prio now and solving it later.

**Comment by wrygiel** [comment]
We may talk about it via Skype too.

**Comment by following5** [comment]
I think the discussion here has gone off-topic. Returning a list of all generated log uuids will always make sense, independently from the question if `log_uuid` should be deprecated, and how editing logs (#421) will be implemented.

**Comment by following5** [comment]
`log_uuid` needs not to be deprecated. An application which never submits 'needs maintenance' logs dosn't need to evaluate `log_uuids`.

**Comment by wrygiel** [comment]
Ok!
