### ISSUE TITLE
user 'is_admin' flag needs clarification

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#410]
OCPL and OKAPI have a boolean admin flag, while OCDE has a bitflag array with different admin rights, some of them irrelevant for OKAPI and for external applications. The OKAPI flag is nearly meaningless for OCDE.

E.g. an OCPL admin may process geocache reports AND edit other user's geocache listings and logs. At OCDE, there are two different admin flags for processing reports and editing other user's listings, and none at all for editing logs.

logs/submit queries this field, but does not yet use it.

I am not sure if this can be fixed by a documentation update. Maybe this field should just be deprecated ...?

**Comment by wrygiel** [comment]
> I am not sure if this can be fixed by a documentation update. Maybe this field should just be deprecated ...?

Why not. I'm not sure if it is used by anyone anyway.
