### ISSUE TITLE
Support both www and no-www prefix for OAuth access?

### ISSUE THREAD

**Issue by wrygiel** [opencaching/okapi#416]
I'm not yet sure how's that possible, but both www and no-www domains were (are?) accepted when making OAuth requests to OCPL's OKAPI. It wasn't possible when I first designed the system, but [seems to be possible now](https://github.com/opencaching/opencaching-pl/issues/513).

Since some apps (c:geo, for starters) are actually using the www prefix, it should also keep working this way. We need to analyze the code behind this.

**Comment by andrixnet** [comment]
https://github.com/opencaching/opencaching-pl/issues/513#issuecomment-209359393

**Comment by wrygiel** [comment]
I'm swamped with work just now. I'll try to join the discussion as soon as I can (but it still could take a couple of days).

**Comment by following5** [comment]
This may also apply to www.opencaching.it and www.opencaching.fr.

**Comment by wrygiel** [comment]
I see why accessing OKAPI with `www.` works. In `oauth.php` we have this line:

```php
    $http_url = ($http_url) ? $http_url : $scheme .
                              '://' . $_SERVER['SERVER_NAME'] .
                              ':' .
                              $_SERVER['SERVER_PORT'] .
                              $_SERVER['REQUEST_URI'];
```

This means, that OKAPI has been accepting requests on every VirtualHost it could received a request from. We SHOULD have been accepting `okapi_base_url` only, not just any `$_SERVER['SERVER_NAME']`.

This would work properly, if OCPL redirected from `www.` properly. It did redirect properly - a couple of years back, but now it doesn't. And - since some clients began using the `www.` prefix, OCPL cannot add this redirection now without breaking these clients.

I believe that there are two things that need to be changed in OKAPI:

* `okapi_base_urls` field should be added to `apisrv/installation` and `apisrv/installations`. For OCPL it will contain two URLs, for other sites - just one.

* In `OkapiHttpRequest::init_request` method, we must verify if the requested URL matches any of the `okapi_base_urls` for this server.

**Comment by wrygiel** [comment]
BTW, I can see that OCUS also doesn't redirect properly. So `okapi_base_urls` should contain two URLs for OCUS too. (OCUS has not updated OKAPI in a long while, but still.)

**Comment by wrygiel** [comment]
My guess is, that `okapi_base_urls` should also include `http` and `https` variations.

**Comment by wrygiel** [comment]
> This may also apply to www.opencaching.it and www.opencaching.fr.

Then, your `okapi_base_urls` list will be quite long. :) Is there any way for you to verify if there are any clients accessing OKAPI via these domains? (e.g. you have long term access logs)

**Comment by following5** [comment]
Your original design decision was that only the primary domain www.opencaching.de should be used for OKAPI access. If other national domains are used, they would need _different default languages_, which is not implemented in OKAPI - so this feature is broken.

I don't know if anyone actually uses them. (c:geo developer have been testing on these domains, as I recently found out, but they did not enable them in the distributed app). There are no long-term webserver logs, and the logs don't contain the domains anyway.

A good solution may be to redirect them within OKAPI to www.opencaching.de. I.e. return a "Location: http://www.opencaching.de/okapi/...". Note that only www.opencaching.de is https-enabled.

**Comment by following5** [comment]
https://www.opencaching.de/okapi/ _is_ being used, though it is partially broken. I think we may keep this url enabled for now, and then solve the problems via #343. There already is a sample impenentation in the #343 thread waiting for review for > half a year.

**Comment by wrygiel** [comment]
> Your original design decision was that only the primary domain www.opencaching.de should be used for OKAPI access.

True. I would like to be this way, but it cannot be (at least not for OCPL).

**Comment by wrygiel** [comment]
> A good solution may be to redirect them within OKAPI to www.opencaching.de.

Redirection won't work for OAuth calls. I think we can either allow them without redirecting, or strictly prohibit them (also without redirecting).

**Comment by wrygiel** [comment]
(Going offline for a couple of hours, I will be back in the evening.)

**Comment by following5** [comment]
Then I think the .it .fr. .es domains should be omitted, and I will redirect the introduction and installation pages locally. If it breaks something critical, we well notice and still may re-add it.

**Comment by wrygiel** [comment]
> Then I think the .it .fr. .es domains should be omitted

Okay.

**Comment by wrygiel** [comment]
I will try to merge it then. This branch seems complete by itself and unrelated to the origin/node/schema issue we were talking about in different thread.

**Comment by wrygiel** [comment]
> and unrelated to the origin/node/schema issue

It is related only in such way that it uses the `get_node_code` / `get_oc_schema_code` function, but otherwise it doesn't seem related. So we can merge it independently, and then continue our discussion on "what's a node really is" :)

**Comment by wrygiel** [comment]
I have merged #419 and tested it briefly. It seems to be working correctly.

**Comment by following5** [comment]
I have deployed it to Opencaching.de, but can still access OKAPI through the other domains, e.g. http://www.opencaching.it/okapi/services/attrs/attribute_index?consumer_key=oc.de_consumer_key.

**Comment by following5** [comment]
That's because OCDE SITE_URL always reflects the URL of the current request, and get_allowed_base_urls() always includes the SITE_URL. I will change this somehow in okapi_settings.php.

**Comment by following5** [comment]
>  I will change this somehow in okapi_settings.php.

I will postpone this until #343 is completed. The state of the SITE_URL setting is too unclear.

**Comment by following5** [comment]
There is a new dictionary of Opencaching site URLs: https://wiki.opencaching.eu/index.php/Node_IDs#Node_ID_assignments

**Comment by following5** [comment]
> This would work properly, if OCPL redirected from www. properly. It did redirect properly - a couple of years back, but now it doesn't. And - since some clients began using the www. prefix, OCPL cannot add this redirection now without breaking these clients.

Meanwhile, www.opencaching.pl redirects to opencaching.pl (while the US site is still accessable via both, www.opencaching.us or opencaching.us).

Also, http is redirected to https on opencaching.pl, opencache.uk and www.opencaching.de. 

So I think we may remove some entries from the site_urls list ...?

> I have deployed it to Opencaching.de, but can still access OKAPI through the other domains, e.g. http://www.opencaching.it/okapi/services/attrs/attribute_index?consumer_key=oc.de_consumer_key.

This problem still exists.

**Comment by wrygiel** [comment]
> Meanwhile, www.opencaching.pl redirects to opencaching.pl

It doesn't for affected HTTP services, e.g. http://www.opencaching.pl/okapi/services/apisrv/installation. It does for HTTPS, but that's okay, because HTTPS was introduced afterwards. So, for OCPL, there should be three `site_urls` (one with HTTPS, and two with HTTP).

**Comment by following5** [comment]
Okay. It's the same for opencache.uk. OCDE completely redirects from http to https, so http://www.opencaching.de/okapi/ can be removed. 

The opencaching.it/es/fr thing needs to be solved locally.

**Comment by wrygiel** [comment]
> OCDE completely redirects from http to https, so http://www.opencaching.de/okapi/ can be removed.

Hmm.... This means that some apps, like for example the older versions of my own [QuickFind](https://play.google.com/store/apps/details?id=net.rygielski.roadrunner&hl=en), won't work with OCDE then. Note sure how many OCDE users use this app, but still, I would appreciate backward-compatibility... This might have costed me a couple of one-star ratings.

**Comment by wrygiel** [comment]
I have checked, and currently 24% of all users of my app are from Germany. 12% of users still haven't updated to the most recent version.

**Comment by following5** [comment]
Yes, this leaves some apps behind, not only OKAPI apps. On the other hand, it enforces a quick migration to current safety standards. The decision was made by teiling88.

@teiling88 
Would it be an option to temporarily re-enable http://www.opencaching.de/okapi ?

**Comment by teiling88** [comment]
@wrygiel how long does your app support HTTPS?

**Comment by wrygiel** [comment]
> On the other hand, it enforces a quick migration to current safety standards

We have no way of enforcing users to update their apps. If the apps breaks, they will most often blame the app developer, even if the developer did what he could to comply.

But there's a more important fact: The specs promised for the endpoints to work over HTTP, but - in case of OCDE - admins decided to break this promise. Without even sending a notice to apps' developers. These kinds of changes are often preceded by a series of notices, and at least a couple of months of delay (or in case of good APIs, even a couple of years), to give all developers proper lead time to comply. In case of OCDE, there were no such notices (or at least I don't think I have received any). So, this move seems very "unprofessional".

> @wrygiel how long does your app support HTTPS?

About 6 months. But there's no way of knowing if there are other developers, who still don't even know that they should change something.

**Comment by wrygiel** [comment]
Sorry, I'm a backward-compatibility freak. I know I tend to exaggerate in this field sometimes, and probably you are right that 99% users are not affected, but still, I would never do such a thing to my fellow developers without prior notice :)

**Comment by teiling88** [comment]
http://www.opencaching.de/okapi/ :-)

**Comment by following5** [comment]
Agree that it would be more professional to inform developers in advance of such a change. @teiling88: You will find the OKAPI client developers' email adresses in the `okapi_consumers` table.

> The specs promised for the endpoints to work over HTTP

I don't think so. The current specs of the services/apisrv/installation `site_url` and `okapi_base_url` fields just say: _Note, that sites which do not support HTTPS yet, will return HTTP URL here_, while the [original specs](https://github.com/opencaching/okapi/blob/932cf784efcf4ffa2c98eccc6c7c3282e28afbc1/okapi/services/apisrv/installation.xml) just say: _usually this looks like "http://www.opencaching.<i>xx</i>/"_.

**Comment by following5** [comment]
The OKAPI specs _cannot_ promise that OKAPI will be available forever under a certain site URL. Sites may shut down, or they may be forced to move to another domain for some domain rights issue. A government may even decide to pass a data privacy bill which enforces https for all internet services.

It's just in the interest of both OKAPI project and the site operators to stay as backward compatible as possible.

**Comment by wrygiel** [comment]
What I meant is that these URLs (with HTTP) were explicitly mentioned in the pages with the method specifications. Later, they were replaced with HTTPS counterparts, but the developers who have coded their apps earlier, have no way of knowing this happened:

![image](https://user-images.githubusercontent.com/2168535/30513059-59cd80cc-9afd-11e7-8996-1075d479c1b7.png)

In other words, developers might have hardcoded these URLs in their apps, and they haven't used `site_urls` or `okapi_base_url` (in fact, we never actively encouraged such use).

**Comment by following5** [comment]
Yes. OKAPI lacks a mechanism of independently informing about the available site_urls. The output of the 'installations' method should be available on some independent site (https://raw.githubusercontent.com/opencaching/okapi/master/etc/installations.json ?)

**Comment by following5** [comment]
Sure there are OKAPI client developers who are not aware that they may need to support https. They may even still not be aware if they write an app for Opencaching.NL or .RO and look at the method docs there!

Also, so far it is usual that APIs stay dual-protocol http/https while the main site transitions to https. But on the long run, I don't think that http will survive. Eventually users of http-only apps will be cut off, the same way that e.g. users of old MS Internet Explorer versions have been cut off from the web.

**Comment by wrygiel** [comment]
> I don't think that http will survive

I think so too. Browsers have already begun to penalize HTTP. In a couple of years, probably all non-HTTPS sites will show up "in red". I'm perfectly okay with migration to HTTPS, but I still believe proper notices should be sent. We may even have OKAPI itself send them (but the fact that some OC sites don't support HTTPS yet complicates things).

> Yes. OKAPI lacks a mechanism of independently informing about the available site_urls.

Do you suggest, that we should require developers to parse external files, instead of hardcoding the new HTTPS URLs in their apps?

**Comment by following5** [comment]
Do you mean: completely hardcoding the OC site URLs? I think that should never be done for apps that are published. Otherwise, they will need an update to support new OC sites. E.g. if [GeOrg](http://android.ranitos.de/de/) - last release on 13 October 2014 - would be an OKAPI app with completely had hard-coded site URLs, it would still not run with Opencaching.RO. (Actually it uses the old OC "XML interface", same problem.)

If I would release an OKAPI app today which is not Opencaching.de specific, I would hard-code some of the current OC site URLs - but just to be on the safe side when retrieving the [installations list](https://www.opencaching.de/okapi/services/apisrv/installations). I would use the site names from the installations list as IDs of the sites and cache the URLs.

After you suggested that Github URLs last "forever", it came into my mind to simplify this by offering a master installations list (Site names => URLs) on Github. But maybe it's not a good idea. Developers may do a lazy implementation without caching, and then OKAPI apps go offline if Github is down for maintenance ...

**Comment by following5** [comment]
(In the original internal OKAPI design, site URLs were also used as site IDs. It relied on URLs staying forever! I think this was a fundamental flaw, and I tried to fix it with #343 / e97f35e9, which never made it into master. Meanwhile site-URLs-IDs have been eliminated from the attribute definitions table. Am not sure if there is still code left which uses URLs as IDs.)

**Comment by wrygiel** [comment]
> After you suggested that Github URLs last "forever"

What I meant is that URLs to GitHub's **pages** (and only the pages) will last forever. It's almost certain that they will want all existing permalinks to remain permalinks. The layout of these pages may change, so machines cannot parse them. We can use these URLs in XML namespace identifiers, because these URLs are identifiers only. Developers may try to resolve them as actual URLs, and they will be redirected to a proper page with the documentation (but not the actual XSD file).

As to the `https://raw.githubusercontent.com/` links, there are no such guarantees. On the contrary, they will probably limit the excessive usage of this domain. They don't want the developers to treat it as their personal CDN. We can use these raw URLs in our `schemaLocations`, because valid `schemaLocations` are not crucial for the validity of XML files (and can be changed without breaking backward compatibility), but we cannot trust these URLs to remain valid.

**Comment by wrygiel** [comment]
> Otherwise, they will need an update to support new OC sites.

I still need to update to support new OC sites, because I need w Consumer Key :)

**Comment by following5** [comment]
> I still need to update to support new OC sites, because I need a Consumer Key :)

Oops. So the developers would need an own consumer key repository. Then, they already have an own site dictionary which may also contain the URLs.

**Comment by following5** [comment]
> But you have users which have not updated yet so i opend the okapi for http connections once again like @following5 described above.

Now issue #474 is back.
