### ISSUE TITLE
Deprecate ORIGIN_URL

### ISSUE THREAD

**Issue by wrygiel** [opencaching/okapi#417]
Originally, `ORIGIN_URL` served as an identifier of the source of the OC site. `OC_NODE_ID` was supposed to be equal to `4` for all development installations, so it couldn't serve this purpose.

Later, `ORIGIN_URL` also served to identify the set of attributes used by this installation. For example, OCNL used OCPL's `ORIGIN_URL` because it had exactly the same attributes.

However, all this causes much confusion. I propose some changes:

* OKAPI's `OC_NODE_ID` should never equal `4`. It should always refer to the OC NODE from which the database and code has been taken.

* `ORIGIN_URL` will be deprecated. We will use a normalized site name for matching attribute schemas.

**Comment by wrygiel** [comment]
> We will use a normalized site name for matching attribute schemas.

Correction: We will use `OC_NODE_IDs` for this. Or a value derived from `OC_NODE_ID`.

**Comment by following5** [comment]
Attributes on OCDE develsites have been broken - they use node ID 4. Also, it is no longer possible to set up a test site with a new node ID - it will need a modification of OKAPI code.

What about re-adding the former-origin-url-now-node-code to the OKAPI settings?

**Comment by wrygiel** [comment]
We could add `4 => 'DEVEL'` mapping. This would make such sites work, but how should attributes behave in such installations?

> What about re-adding the former-origin-url-now-node-code to the OKAPI settings?

You mean having both? `OC_NODE_ID` and `OC_NODE_CODE`? And `OC_NODE_ID` would be 4, while `OC_NODE_CODE` would be 'OCDE'?

**Comment by following5** [comment]
> You mean having both? OC_NODE_ID and OC_NODE_CODE? And OC_NODE_ID would be 4, while OC_NODE_CODE would be 'OCDE'?

Yes. It may be called `ORIGIN_NODE_CODE`.

**Comment by wrygiel** [comment]
This would work too, I guess. But I'm not sure why we cannot use OC_NODE_ID for that. With the exception of ID=4, this seems to have exactly the same meaning. Do you know why ID=4 has been initially introduced?

**Comment by following5** [comment]
I guess it was introduced for debugging the Node-ID feature (which I described in some other comment here) on devel sites. OCDE devel sites have node-1 data imported from www.opencaching.de and local node-4 data. The `node_id` field of geocaches, logs, images etc. makes only sense at all if the same database can contain data from different nodes.

The other point is, that this change forces to
* create redundant attriubte definitions for sites which share the same attributes. Currently there is attribute chaos on different OCPL sites, but this may be synchronized in the future (like OCDE static database content is synchronized between al OCDE installations),
* change OKAPI code when setting up a test site with a new node ID.

I think the origin-site concept was fine, so why eliminate it?

**Comment by following5** [comment]
> for sites which share the same attributes.
... share the same attribute set

**Comment by wrygiel** [comment]
> I think the origin-site concept was fine, so why eliminate it?

I think that you and me are the only ones who understand this concept... But okay, I'll bring it back. (I thought that you also wanted to get rid of it, as I do.)

**Comment by following5** [comment]
Agree, it's hard to understand (especially when using URLs as IDs).

What about replacing it by purpose-based IDs? E.g. introducing an "attribute set ID", and an "NPA tables ID"? That's currently the only two things the Origin-Thing is used for.

**Comment by wrygiel** [comment]
It's getting too out of hand. I want to make it simpler, not even more complex... I think I'll try some other approach.

> create redundant attriubte definitions for sites which share the same attributes

I tend to think we *need* to make it more redundant. Currently, **every** OC site uses a different set of attributes. It's just how it is. It this changes in the future, we can implement it differently. But for now, we need to make it explicit.

> change OKAPI code when setting up a test site with a new node ID.

I will change the code so that it doesn't throw exception when and unknown ID is encountered.

**Comment by following5** [comment]
Now we have something which works on all sites (see https://github.com/opencaching/okapi/commit/c38f041dc3fd7bd2ad938e77398265ed43957f96#commitcomment-17219341), but is wrongly named and documented:

```
    /**
     * OC "node codes" were introduced in issue #417. These are equivalent to
     * the ORIGIN_URLs used before, but are better to undestand. They are used
     * internally only, they SHOULD NOT be exposed to external developers.
     */
    public static function get_node_code()
    {
```

This is not equivalent to the OC_NODE_IDs, but to the ORIGIN_URL! These node codes _must not_ be used equivalent to OC_NODE_ID anywhere in OKAPI code - that would break OCDE devel and test sites. So I think it should be changed like this, to avoid confusion:

```
    /**
     * OC "node codes" were introduced in issue #417. These are equivalent to
     * the ORIGIN_URLs used before. They are used internally only, they SHOULD
     *  NOT be exposed to external developers.
     */
    public static function get_origin_node_code()
    {
```

I know that this is not what you intended, but I dont's see any alternative. The ORIGIN_URL cannot be dropped; it just as been renamed and internalized.

**Comment by wrygiel** [comment]
I'm unable to understand it. What's a "node" then? I think OCDE has a completely different definition of this term than all other OC sites.

This issue is already taking much more time than I expected... I will try to stop using the term "node" and introduce a new one - schema.

**Comment by following5** [comment]
I am sorry that this causes additional work for you. :(

A "node" is an OC installation which may exchange data with other nodes - therefore the term "node". There is also the term "[Opencaching Network](https://en.wikipedia.org/wiki/Geocaching#Opencaching_Network)" for the to-be-interconnected OC nodes.

All nodes which may exchange data must have a unique ID, including devel and test sites where the data exchange - and related issues - may be tested. Therefore devel and test sites were assigned the node IDs 4 / 5.

The networking feature is not implemented yet, but the OC database and code was prepared for it. And at OCDE I try to keep this design intact.

**Comment by following5** [comment]
OCDE devel sites have ID 4 and are initialized with a node-1-data dump. So all developers are aware of the multiple-nodes thing, and it is less likely that they acidentially break it. Especially, data imported from other nodes must not be edited locally.

**Comment by following5** [comment]
ok

**Comment by wrygiel** [comment]
Does this mean that OCDE started implementing this feature before OCPL branched off OCDE? And you still want to finish implementing it? You want to fetch data from other OC sites via OKAPI and keep a copy of it?

Still, I don't think OCPL developers have a similar plan. For OCPL-based sites, "node id" serves a different purpose. I wouldn't be surprised if it was even dropped in the future.

**Comment by following5** [comment]
I think that `Okapi::fixed get_allowed_base_urls()` should be based on node IDs instead of schema codes. Multiple nodes (with different URLs) may share one schema.

**Comment by following5** [comment]
> Does this mean that OCDE started implementing this feature before OCPL branched off OCDE?

yes

> And you still want to finish implementing it?

We want to show other nodes' caches _at least_ on the OC.de map, and importing data from the other nodes would be the most powerful - but also most expensive - way to do so.

> You want to fetch data from other OC sites via OKAPI and keep a copy of it?

If we go for the powerful and expensive solution, yes. But currently there are no plans _when_ this will be done.

> Still, I don't think OCPL developers have a similar plan.

agree

> For OCPL-based sites, "node id" serves a different purpose. I wouldn't be surprised if it was even dropped in the future.

It has no other purpose at OCPL. And therefore it may be dropped, if OCPL developers decide that OCPL sites will _never_ be part of an Opencaching Network. That would not affect the OCDE data import - node IDs can be added while importing.

**Comment by wrygiel** [comment]
> Multiple nodes (with different URLs) may share one schema.

Currently, there are no such nodes. I can rename `get_oc_schema_code` to `get_site_code` if you want.

**Comment by following5** [comment]
`get_oc_schema_code` is perfectly correct, see the OCDE develsites and your comments in the code. I will add a TODO comment to `get_allowed_base_urls()`.

**Comment by following5** [comment]
> >   Does this mean that OCDE started implementing this feature before OCPL branched off OCDE?

> yes

You can see that in code like [this](https://github.com/opencaching/opencaching-pl/blob/f05fc5a8d63ecd429646eca38bdfa72a7d0fde53/editlog.php#L39). But lots of the node-related OCPL code is broken.

**Comment by andrixnet** [comment]
IMO a future cooperative data exchange between OC sites is a good idea. Of course, an identification would be needed and here comes node_id. 

IMO we should fix node-related code in OCPL.

A major cleanup in attributes in OCPL code is due and we should find a solution on how to make things work until then. 
I will try to work on the attributes.xml this week

**Comment by andrixnet** [comment]
From my understanding, "node" is a unique numeric identified for an opencaching site. (also installation instance? since OCDE handles several national sites from same instance)
