### ISSUE TITLE
Edit and delete log entries

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#421]
Besides of additional log types and geocache reports, I think this is the most important feature to be added to OKAPI.

Note that both OCPL and OCDE restrict editing the log type:
- OCPL log types cannot be edited at all (so the 'needs maintenance' flag also should not be editable).
- OCDE allows any changes between "Found it", "Didn't find it" and "Comment", but geocache-status-changing log-type changes (see #260) are allowed only for the newest log of a cache.

**Comment by wrygiel** [comment]
> Besides of additional log types and geocache reports, I think this is the most important feature to be added to OKAPI.

I agree! This would be very helpful.

We should provide a safe common interface - similar to the one we have for submitting new logs (external apps should display user messages).

**Comment by following5** [comment]
Log deletion by the cache owner generates an email to the logger, so it makes sense to implement #408 before services/logs/delete.

**Comment by following5** [comment]
> *  OCPL log types cannot be edited at all (so the 'needs maintenance' flag also should not be editable).
> *  OCDE allows any changes between "Found it", "Didn't find it" and "Comment", but geocache-status-changing log-type changes (see #260) are allowed only for the newest log of a cache.

Meanwhile, all kind of log type changes are possible at OC sites, except for changes to "Temporarily unavailable" or "Ready to search", which are disabled at OCPL. When changing _from_ "Temporarily unavailable" or "Ready to search", only OCDE will update the geocache status (if it is the latest log).

Type changing is the most complex part of log editing, but it's impotant only for "Found it"/DNF/Comment, because that's easy to get wrong. Apps often have a "Found it" default, and you forget to change it e.g. to DNF. Also, it happens that useds log DNF, then have a last look and find the cache. Other than wrong status logs, these cases cannot be corrected by a second log.
