### ISSUE TITLE
GROUP BY problems after MySQL upgrade

### ISSUE THREAD

**Issue by wrygiel** [opencaching/okapi#425]
MySQL 5.7.12:

```
===== ERROR MESSAGE =====
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ocpl.okapi_stats_temp.datetime' which is not functionally dependent on columns in GROUP
BY clause; this is incompatible with sql_mode=only_full_group_by
=========================

--- Stack trace ---
#0 /srv/ocpl/okapi/core.php(552): PDO->query('\n              ...')
#1 /srv/ocpl/okapi/cronjobs.php(379): okapi\Db::query('\n              ...')
#2 /srv/ocpl/okapi/cronjobs.php(92): okapi\cronjobs\StatsWriterCronJob->execute()
#3 /srv/ocpl/okapi/core.php(1386): okapi\cronjobs\CronJobController::run_jobs('pre-request')
#4 /srv/ocpl/okapi/core.php(1501): okapi\Okapi::execute_prerequest_cronjobs()
#5 /srv/ocpl/okapi/controller.php(61): okapi\Okapi::init_internals(true)
#6 /srv/ocpl/okapi/controller.php(98): okapi\OkapiScriptEntryPointController::dispatch_request('')
#7 {main}
```

**Comment by kojoty** [comment]
this is an issue around mysql mod: ONLY_FULL_GROUP_BY
I've disabled this mod at new production server [https://hackmd.io/GYBhCYCMFME5oLQBMDMB2YCAskvgQByzCYCGwAxikpAdCgGzTBA=#mysql-tuning]

**Comment by wrygiel** [comment]
Is is possible to disable it on a per-query basis?

**Comment by wrygiel** [comment]
BTW - don't publish hackmd links. Everyone with this link is allowed to edit (and remove) this document ;)

**Comment by kojoty** [comment]
> BTW - don't publish hackmd links. Everyone with this link is allowed to edit (and remove) this document 

ups :)

**Comment by wrygiel** [comment]
I think this should do:

```sql
SET SESSION sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
```

I will try to execute this every time OKAPI connects to the database.

**Comment by wrygiel** [comment]
Reverted.

**Comment by wrygiel** [comment]
> but I think the better solution is to globally disable this temporary, next fix all queries and enable it later...

I'm not sure if I really want to "fix" these queries. As long as it will be possible to turn `ONLY_FULL_GROUP_BY` off, I intend for OKAPI to make use of it. But perhaps I can be persuaded ;)

Anyway, this commit will need to wait a little. It is built in #297, and I cannot commit #297 without breaking the old OCPL site.

**Comment by andrixnet** [comment]
I would agree with @wrygiel on this: keep the working code and set MySQL server setting `ONLY_FULL_GROUP_BY` to **off** for installations using MySQL 5.7.5 or later, as long as this option exists. 
According to what I read so far, it should not be an issue with MariaDB, since this is not set by default https://mariadb.com/kb/en/mariadb/sql_mode/

**Comment by wrygiel** [comment]
Oracle purchased MySQL. I guess that they might be aiming to unify differences between different SQL dialects, but I kind of like the "old" MySQL dialect.

**Comment by andrixnet** [comment]
Oracle's business policies towards open-source is what has driven the creation of the MariaDB fork, to preserve and continue the true MySQL legacy.
