### ISSUE TITLE
Disable NO_ZERO_DATE sql_mode?

### ISSUE THREAD

**Issue by wrygiel** [opencaching/okapi#430]
Current implementation of images doesn't work with the current structure of the `pictures` table and the newer version of MySQL. I'm not sure what would be the best way to fix this.

```
===== ERROR MESSAGE =====
SQL Error 1292: Incorrect datetime value: '0000-00-00 00:00:00' for column 'thumb_last_generated' at row 1

The query was:

            insert into pictures (
                uuid, node, local, title, spoiler, url, object_type, object_id,
                unknown_format, display,
                date_created, last_modified, description, desc_html, last_url_check, user_id
            )
            values (
                '89110a25-eaf6-44ea-9f9d-77e577dff6a4',
                '2',
                1,
                'gwiazdka',
                '0',
                'http://opencaching.pl/images/uploads/89110a25-eaf6-44ea-9f9d-77e577dff6a4.gif',
                1,
                '2081637',
                0,
                1,
                NOW(), NOW(), '', 0, NOW(), '7969'
            )
=========================
```

**Comment by following5** [comment]
I don't think this error is OKAPI related; it should also occur when uploading pictures on the OC site.

Looks like there is a default value '0000-00-00 00:00:00' configured for `pictures`.`thumb_last_generated`, but this default value is rejected on insert.

**Comment by wrygiel** [comment]
We have temporarily removed `NO_ZERO_DATE` (and many others) from default sql_mode. This should fix the issue.

**Comment by andrixnet** [comment]
Before modifying the code, since such problems arise from configurable changes in MySQL server, I would suggest setting the SQL_MODE in such a way that MySQL behaves as before those changes were introduced.
And please document those in the project Wiki and notifiy node admins.
Thank you.

**Comment by wrygiel** [comment]
> I would suggest setting the SQL_MODE in such a way that MySQL behaves as before those changes were introduced.

This is exactly what we have done on OCPL.

If the problems surfaces again, we will make OKAPI reconfigure MySQL itself for the session, so there's no need to document it (in OKAPI).
