### ISSUE TITLE
User can log cache even if is already banned

### ISSUE THREAD

**Issue by mzylowski** [opencaching/okapi#432]
Hi!

There was an issue in oc.pl repo:
https://github.com/opencaching/opencaching-pl/issues/646

How I understand architecture of OKAPI, this have to be solved here.

**Comment by following5** [comment]
The user's autorization must be revoked when `user.is_active` has been set to <> 1.

**Comment by following5** [comment]
The problem should be solved now.

**Comment by wrygiel** [comment]
Does it really require us make an extra SQL query for *every* OAuth request? That seems to be a very big performance hit for such a simple feature. Perhaps we can at least wrap it with an additional `if ($this->opt_min_auth_level == 3)`?

**Comment by wrygiel** [comment]
Or, even better, we could expose a Facade method for banning users.

**Comment by wrygiel** [comment]
One more idea: a single check in `services/oauth/request_token` + a daily cronjob to remove existing authorizations. This will make all the banned user to be banned automatically within 24h without the need for a new Facade method.

**Comment by wrygiel** [comment]
There was no need to modify oauth methods - no new access token can be generated, because banned users are not allowed to sign in. (However, OC developers need to make sure that the user is automatically being signed out after he is banned.)

**Comment by following5** [comment]
oops

**Comment by following5** [comment]
The evluation of the user's login stat in OKAPI is flawed. `sys_sessions` must only be evaluated in connection with `user.is_active_flag`.

**Comment by following5** [comment]
Shouldn't `OkapiDataStore::lookup_token()` also verify if the user account has been disabled?

**Comment by wrygiel** [comment]
> The evluation of the user's login stat in OKAPI is flawed.

It is possible, I haven't spent much thought on this topic when I first implemented it. Perhaps we should commit this in a separate issue?

> Shouldn't OkapiDataStore::lookup_token() also verify if the user account has been disabled?

This would make the bans work immediately (compared to 2 hours in the current solution), but it would also require a most lengthy query for all OAuth calls. Is 2 hours too long?

**Comment by wrygiel** [comment]
> Perhaps we should commit this in a separate issue?

Or maybe not. I had a look at your commit and it's clearly related. Looks okay!

**Comment by wrygiel** [comment]
> Is 2 hours too long?

Added a proper Facade method. If you want the ban to work immediately, simply call it after the user gets banned.

**Comment by following5** [comment]
ok, thx
