### ISSUE TITLE
OKAPI installation fails

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#434]
The first database mutation in update.php calls `Okapi::mail_admins()`, and this function calls `Cache::get()`, which tries to access the not-yet-existing table `okapi_cache`.

**Comment by following5** [comment]
It's an exception handling problem related to the PDO migration.

**Comment by following5** [comment]
This code
```php
    public static function query($query)
    {
        if (!self::$connected)
            self::connect();
        try
        {
            $rs = self::$dbh->query($query);
        }
        catch (PDOException $e)
        {
```

will not catch the PDOException for the error "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'opencaching.okapi_cache' doesn't exist". Though it caches e.g. PDOExceptions for SQL syntax errors. If I change it to 

```php
        catch (Exception $e)
```

it works fine, though it IS an PDOException which is thrown (verfied by vardumping $e).

**Comment by following5** [comment]
It's an exception recursion problem. The exception handler for "Table 'opencaching.okapi_vars' doesn't exist" will try to send an admin mail, which triggers another exception because `okapi_cache` does not exist.

**Comment by following5** [comment]
Update mutations 35 and 48 have the same problem, because the field `score` in the `okapi_cache` table is not available yet.

**Comment by following5** [comment]
Please verify if this workaround is ok. At least I was able to install OKAPI now in the new OC.de vagrant VM.

**Comment by following5** [comment]
> It's an exception handling problem related to the PDO migration.

And/or to PHP 5.6.

**Comment by wrygiel** [comment]
Sorry for the delay. I was offline in Slovenian mountains since 28th of May, I'll try to read all the emails tomorrow!
