### ISSUE TITLE
Out of memory when producing GPX output

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#435]
Allowed memory size of 268435456 bytes exhausted (tried to allocate 43071214 bytes)

File: /srv/ocpl/okapi/services/caches/formatters/gpx.php
Line: 512

--- OKAPI method called ---
/okapi/services/caches/shortcuts/search_and_retrieve
?search_method=services/caches/search/nearest
&search_params=%7B%22center%22%3A%2254.35603333%7C18.6527%22%2C%22limit%22%3A500%2C%22radius%22%3A25%2C%22type%22%3A%22Traditional%7CMulti%7CQuiz%7CMoving%7CVirtual%7COther%22%2C%22status%22%3A%22Available%7CTemporarily+unavailable%22%2C%22owner_uuid%22%3A%22-EA057996-7A06-E0B3-D158-2F0D6B849835%22%2C%22exclude_ignored%22%3A%22true%22%2C%22location_source%22%3A%22alt_wpt%3Auser-coords%22%7D
&retr_method=services/caches/formatters/gpx
&retr_params=%7B%22langpref%22%3A%22pl%7Cen%22%2C%22ns_ground%22%3A%22true%22%2C%22ns_gsak%22%3A%22true%22%2C%22ns_ox%22%3A%22true%22%2C%22images%22%3A%22descrefs%3Aall%22%2C%22trackables%22%3A%22desc%3Alist%22%2C%22recommendations%22%3A%22desc%3Acount%22%2C%22attrs%22%3A%22gc%3Aattrs%7Cdesc%3Atext%7Cgc_ocde%3Aattrs%22%2C%22alt_wpts%22%3A%22true%22%2C%22my_notes%22%3A%22desc%3Atext%7Cgc%3Apersonal_note%22%2C%22location_source%22%3A%22alt_wpt%3Auser-coords%22%2C%22location_change_prefix%22%3A%22%5BF%5D+%22%2C%22latest_logs%22%3A%22true%22%2C%22lpc%22%3A%22all%22%2C%22mark_found%22%3A%22true%22%7D
&wrap=false
&oauth_consumer_key=xxx
&oauth_signature_method=HMAC-SHA1
&oauth_timestamp=1464957696
&oauth_nonce=xxx
&oauth_token=xxx
&oauth_version=1.0
&oauth_signature=xxx

--- OKAPI version ---
1315 (8893638ba5c9fb5d42e3f09787fa1b72805b5e45)

--- Request headers ---
Host: opencaching.pl
Connection: Keep-Alive
User-Agent: Apache-HttpClient/AwaryjniejszyGPX 1.4 Jaworzyna (28)
Accept-Encoding: gzip,deflate
Cache-Control: no-cache
Pragma: no-cache
.

**Comment by wrygiel** [comment]
I think that we need some limits. If a request consumes that much memory, then it might be a good idea to respond with HTTP 400 and proper message.

**Comment by wrygiel** [comment]
Or, maybe not. It's not *this* client's fault that some caches in the database are huge. We'll increase the default memory limit to 512M.
