### ISSUE TITLE
Vulnerability credential $_COOKIE['okapi_devel_key']

### ISSUE THREAD

**Issue by Rotzbua** [opencaching/okapi#437]
Vulnerability:
- Hard coded credential
- unsafe md5 for password verification

okapi/Okapi

``` php
    /**
     * Some pages should be visible only to OKAPI developers (e.g. frequent
     * stats generation may reduce OKAPI responsiveness). This method verifies
     * that the requester is a developer. If he isn't, it die()s.
     */
    public static function require_developer_cookie() {
        if (
            (!isset($_COOKIE['okapi_devel_key']))
            || (md5($_COOKIE['okapi_devel_key']) != '5753f318c1495c01637f7f6b7fc9c5db')
        ) {
            header("Content-Type: text/plain; charset=utf-8");
            print "I need a cookie!";
            die();
        }
    }
```

**Comment by wrygiel** [comment]
I guess that you believe it is not a good style, because you should not hardcode such things in the app, right?

Also, probably you think that exposing the hash is not safe, as it allows the hackers to crack it offline?

And, to make it worse, MD5 is used, which allows to crack it much faster than, say, sha512 or bcrypt? Yes?

**Comment by Rotzbua** [comment]
> I guess that you believe it is not a good style, because you should not hardcode such things in the app, right?

Yes, exactly. It would be better placed in a config.

> Also, probably you think that exposing the hash is not safe, as it allows the hackers to crack it offline?

Yes.

> And, to make it worse, MD5 is used, which allows to crack it much faster than, say, sha512 or bcrypt? Yes?

The sha* hashing family is only for integrity check. Bcrypt would be a good choice, because it is designed for authentication tasks and hardening against brute force :).

Maybe have a look to the new password functions in php: https://secure.php.net/manual/en/function.password-verify.php
It uses bcryt in back end and salt.

**Comment by wrygiel** [comment]
In general, I do agree!

However, in this particular case, the resource being protected is not really that important. The page protected by this function was publicly visible for many years, I have added this check just a month ago, and only to avoid accidental database locks by people poking around (long-running SELECT queries on MyISAM storage engine).

You are right that this could be done better (with separate admin accounts with passwords, etc.), but that would be quite a complex solution for such a simple problem.

**Comment by following5** [comment]
Agree that a securty improvement is not important here. Suggest close / wontfix.

**Comment by Rotzbua** [comment]
Ok maybe the protection is sufficient. But I still think that it is not a good solution keeping the credential in the code. 
The hash should be moved to a config file....
