### ISSUE TITLE
dbstruct script error

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#442]
Trying to compare OCNL and OCRO databases using dbstruct from OKAPI, I get the following error : 

http://www.opencaching.ro/okapi/devel/dbstruct?compare_to=http://opencaching.nl/okapi/devel/dbstruct

```json
{
    "error":{
        "developer_message":"The following URL is not on our whitelist: \"http:\/\/opencaching.nl\/okapi\/devel\/dbstruct\".\n\nPlease use one of the following:\n\"http:\/\/opencaching.pl\/okapi\/devel\/dbstruct\",\n\"http:\/\/www.opencaching.de\/okapi\/devel\/dbstruct\",\n\"http:\/\/www.opencaching.us\/okapi\/devel\/dbstruct\",\n\"http:\/\/www.opencaching.nl\/okapi\/devel\/dbstruct\",\n\"http:\/\/www.opencaching.ro\/okapi\/devel\/dbstruct\".",
        "reason_stack":[
            "bad_request"
        ],
        "status":400,
        "more_info":"http:\/\/www.opencaching.ro\/okapi\/introduction.html#errors"
    }
}
```

This seem like JSON. 
I don't know how to call the script in such a way that errors ar shown in a more human-readable form (if it exists)

Second, the error seems to be due to the fact that the script cannot handle redirects. 
This URL works correctly. 
http://www.opencaching.ro/okapi/devel/dbstruct?compare_to=http://www.opencaching.nl/okapi/devel/dbstruct

Also the error "bad request" sounds misleading in this case. Or there is some other fine tuning regarding OKAPI that needs to be done?

**Comment by wrygiel** [comment]
> I don't know how to call the script in such a way that errors ar shown in a more human-readable form (if it exists)

I recommend installing some JSON-viewer browser extension. It will be easier for you to read such messages.

> Second, the error seems to be due to the fact that the script cannot handle redirects.

For security reasons, the script will not even try to process any URL which doesn't match a proper whitelist. See the code here, there's also an issue reference there with explanation of this: https://github.com/opencaching/okapi/blob/master/okapi/views/devel/dbstruct.php#L135

**Comment by wrygiel** [comment]
Alternative: Fix `okapi_base_urls` on OCNL site. You can see [here](http://www.opencaching.nl/okapi/services/apisrv/installation) that currently it doesn't include the URL without the www prefix.

**Comment by wrygiel** [comment]
> Alternative: Fix `okapi_base_urls` on OCNL site.

However, if there's only one domain in use, there really is not reason to add support for another one. Currently it's certain that all OCNL OAuth apps use the "www" prefix. If you extend `okapi_base_urls`, then it will no longer be certain. This means that you will need to keep both domains indefinitely, instead of just one.

**Comment by andrixnet** [comment]
I understand the fine points. Thank you.
