### ISSUE TITLE
New A codes for OCUK

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#443]
OCUK has several unique attributes not seen at any other OC node : 
- Aircraft required
- Rated on Handycaching.com
- Contains a munzee

**Comment by andrixnet** [comment]
- [ ] Aicraft required: A75, OCUK id=156 
- [ ] Rated on Hnadycaching.com: A76, OCUK id=157
- [ ] Contains a munzee: A77, OCUK id=158

**Comment by andrixnet** [comment]
Solved in https://github.com/opencaching/okapi/pull/444

**Comment by wrygiel** [comment]
BTW, what was your source for A75-A77 translations?
