### ISSUE TITLE
OC UK adaptation

### ISSUE THREAD

**Issue by deg-pl** [opencaching/okapi#446]
Please change:

- [x] okapi/core.php line 1393:  change "http://www.opencache.uk/okapi/", to "http://opencache.uk/okapi/",
- [x] etc/installations.xml - add <installation site_url="http://opencache.uk/"/>
- [x] okapi/services/attrs/attribute-definitions.xml - (I hope) @andrixnet will prepare it soon

Thanks in advance!

**Comment by andrixnet** [comment]
working on it

**Comment by andrixnet** [comment]
- [X] okapi/services/attrs/attribute-definitions.xml
solved and ready in okapi/services/attrs/attribute-definitions.xml

**Comment by andrixnet** [comment]
First two points are now solved in https://github.com/opencaching/okapi/pull/447

**Comment by deg-pl** [comment]
@andrixnet Thanks!

**Comment by deg-pl** [comment]
Done in #444
