### ISSUE TITLE
It is possible to log multiple "attended" logs via OKAPI and incorrect counter updates

### ISSUE THREAD

**Issue by deg-pl** [opencaching/okapi#449]
Mail from Volfram (OC PL):

> Testowałem swoją aplikację na żywym organizmie i chciałem sprawdzić jaki błąd zwróci mi przy próbie ponownego dodania logu o uczestnictwie w spotkaniu. Jednak dodanie logu powiodło się i miałem duplikat uczestnictwa. Większy problem się zrobił jak log usunąłem, bo przy dodaniu nie zwiększyło licznika uczestników, ale przy usunięciu już odjęło. Pasowałoby poprawić kod w okapi, aby zwracało błąd podobnie jak przy próbie ponownego znalezienia skrzynki, no i poprawić problem licznika.

**Comment by deg-pl** [comment]
Maybe it is not only related with events, but also with every other cache. See also https://github.com/opencaching/opencaching-pl/issues/706

**Comment by wkopec** [comment]
I tested other possibilities of adding wrong logs types and duplicates, but only in this case success was true. I noticed that we can make duplicates of "will attend" logs, but it is permitted on website too, so probably it was intentional.

**Comment by wrygiel** [comment]
I wasn't aware that only a single "Will attend" log entry was allowed in OCPL. I also wasn't aware that there is a "will attend counter" field in a database. I'll try to fix this ASAP.

BTW, in OCDE they handle this much better, I think. They use caching instead of database counters, and they allow multiple "Found it" entries (but only one of them "counts").

**Comment by wrygiel** [comment]
BTW - is the owner of event also allowed to "Attend" and it counts into his stats?

**Comment by wrygiel** [comment]
I can see the following fields in the `caches` table:

```
  `founds` int(11) DEFAULT NULL,
  `notfounds` int(11) DEFAULT NULL,
  `notes` int(11) DEFAULT NULL,
```

but there are no fields for "will attend counter" nor "attended counter". Do you know which ones should I update?

**Comment by wrygiel** [comment]
Okay, it seems that:

```
mysql> select wp_oc, founds, notfounds, notes from caches where type=6 order by rand() limit 1;
+--------+--------+-----------+-------+
| wp_oc  | founds | notfounds | notes |
+--------+--------+-----------+-------+
| OP8A03 |      7 |        10 |    39 |
+--------+--------+-----------+-------+
1 row in set (0.01 sec)
```

translates to:

![image](https://cloud.githubusercontent.com/assets/2168535/21784316/4544842c-d6bb-11e6-8212-86c83340fa85.png)

Gods, that's weird. :)

**Comment by wrygiel** [comment]
> I noticed that we can make duplicates of "will attend" logs, but it is permitted on website too, so probably it was intentional.

Is the website incrementing the "will attend counter" in this case?

**Comment by following5** [comment]
> BTW - is the owner of event also allowed to "Attend" and it counts into his stats?

Yes.

> Is the website incrementing the "will attend counter" in this case?

Yes.

**Comment by following5** [comment]
The counters are ok now, but OKAPI still allows multiple "Attended" logs, which is not allowed in OCPL code.

(Multiple "Will attend" are allowed at OCPL as well as in OKAPI).

**Comment by following5** [comment]
Btw, OCPL code doesn't trust its per-geocache stats and completely recalculates them after each new log. So the missing OKAPI "Will attend" and "Attended" counts were added after the next on-site log for the cache.
