### ISSUE TITLE
Cache types changing names

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#451]
https://github.com/opencaching/opencaching-pl/issues/853

Do these changes need changes in OKAPI? 
In OKAPI alone, or in OKAPI and all client apps?

**Comment by deg-pl** [comment]
No. OKAPI use "regular" size.

**Comment by andrixnet** [comment]
and the "Puzzle" formerly "Quiz" ?

**Comment by deg-pl** [comment]
No. Is "Quiz" BUT why we should change it in OKAPI???

**Comment by andrixnet** [comment]
Does it mean it will be reported to client apps as "Quiz" although now it is called "Puzzle" ?

**Comment by deg-pl** [comment]
In OKAPI of all OC sites (OC DE also) this type is "Quiz". If we change it, all of 3'rd party application will not work properly. And... this change is absolutely not important for users. OKAPI should be 100% backward compatibile.

**Comment by andrixnet** [comment]
Understood.

**Comment by wrygiel** [comment]
I agree. This is one of the "primary types", and should never change. It might be possible to change some of the "non-primary" ones, but it is still not recommended.

**Comment by andrixnet** [comment]
Do you refer to changing the names or the IDs? 

Does the "not recommended" also apply to adding new types?

**Comment by wrygiel** [comment]
> Do you refer to changing the names or the IDs?

Names, or rather, "code names" - the ones OKAPI uses to uniquely identify the cache type. IDs are not exposed via OKAPI, so - in theory - they can be changed (but it's still a hustle).

> Does the "not recommended" also apply to adding new types?

On the technical level - no. New types can be added freely.

My personal opinion is that we already have too many cache types, and we cannot expect app developers to follow up on this (e.g. they would be required to prepare new icons etc.), but this is my personal opinion only.
