### ISSUE TITLE
Files with execute bit ?

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#454]
Apparently some files get deployed with execute bit set.
Is this intentional or a mishap?

```
./services/caches/search/all.xml -rwxr-xr-x
./services/caches/search/searching.inc.php -rwxr-xr-x

```

**Comment by andrixnet** [comment]
I can fix all permissions under opencaching-pl, but not those under okapi

**Comment by wrygiel** [comment]
Thanks! I'm sure it wasn't intentional. I am using Windows for development, where it's in fact quite hard for me to set (or unset) this bit. I'm not sure how this came to be, but probably some of the developers committed this by mistake.
