### ISSUE TITLE
OKAPI Garmin GPX download - some strings in PL

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#458]
OKAPI generated GPX for Garmin contains the following for waypoints:
`<desc>Punkt wirtualny</desc> `

This seems hardcoded or taken from the wrong translation.

**Comment by wrygiel** [comment]
I guess you means [this line](https://github.com/opencaching/okapi/blob/f56cefa0146496096f748d06e277798b27a0a75b/okapi/services/caches/formatters/gpxfile.tpl.php#L225), yes?

This can be only generated for additional waypoints. The type name is taken from [here](https://github.com/opencaching/okapi/blob/f56cefa0146496096f748d06e277798b27a0a75b/okapi/services/caches/geocaches.php#L1032) and [here](https://github.com/opencaching/okapi/blob/f56cefa0146496096f748d06e277798b27a0a75b/okapi/services/caches/geocaches.php#L929-L938). So it's not hardcoded, but the translation is available only for Polish.

Also, OKAPI should generate English name by default. Are you sure you haven't used any parameter telling OKAPI to use Polish? Can you paste the contents of your `waypoint_type` table?

**Comment by andrixnet** [comment]
Contents of `waypoint_type` table: 

```
"id","pl","en","nl","icon","ro"
1,"Punkt fizyczny","Physical point","","images/waypoints/wp_physical.png","Punct (fizic)"
2,"Punkt wirtualny","Virtual point","","images/waypoints/wp_virtual.png","Punct virtual"
3,"Punkt ko┼äcowy","Final location","","images/waypoints/wp_final.png","Loca┼úia final─â"
4,"Interesuj─àce miejsce","Interesting place","","images/waypoints/wp_reference.png","Loc interesant"
5,"Parking","Parking area","","images/waypoints/wp_parking.png","Parcare"
```

I presume this [line](https://github.com/opencaching/okapi/blob/f56cefa0146496096f748d06e277798b27a0a75b/okapi/services/caches/geocaches.php#L1032) is supposed to obtain a best match for the language in which the response is created. 

However from this [line](https://github.com/opencaching/okapi/blob/f56cefa0146496096f748d06e277798b27a0a75b/okapi/services/caches/geocaches.php#L929-L938) I see that only PL and EN languages are looked up, with priority to PL. 

AFAIK OKAPI gives the user app choice of language (langpref). 
1. If not used, IMO it should fall back to english as the most widely used language in computing.
2. If inconsistent data, it should through an exception of sorts. (inconsistent definitions in the website represent an error)
3. If used, data should be returned in that language.
4. if used, but no data in that language, it should fall back to 1. then 2.

**Comment by wrygiel** [comment]
> However from this [line](https://github.com/opencaching/okapi/blob/f56cefa0146496096f748d06e277798b27a0a75b/okapi/services/caches/geocaches.php#L929-L938) I see that only PL and EN languages are looked up

Yes, only PL and EN languages are looked up (because these are the only columns present in this table at the time). OKAPI cannot explicitly make use of the `ro` column, because other sites don't have this column. But I guess we can do an (implicit) `select *` and search for them.

> with priority to PL. 

Both are picked up as equal, there's no priority here.

> AFAIK OKAPI gives the user app choice of language (langpref). 
> 1. If not used, IMO it should fall back to english as the most widely used language in computing.

[It does](https://github.com/opencaching/okapi/blob/f56cefa0146496096f748d06e277798b27a0a75b/okapi/services/caches/geocaches.php#L58) - English is the default value of `langpref`. That's why I asked you "Are you sure you haven't used any parameter telling OKAPI to use Polish?"

> 2. If inconsistent data, it should through an exception of sorts. (inconsistent definitions in the website represent an error)

What do you mean by inconsistent?

See the code for `Okapi::pick_best_language` and the default value of `langpref`. Currently, I don't see any errors there...

**Comment by wrygiel** [comment]
Quick-added support for more languages in commit https://github.com/opencaching/okapi/commit/a94af853ae0ad150b8e92525a0f90eede961292e. Can you check if it works for you?

**Comment by andrixnet** [comment]
I guess my problem came from lib/search.ggz.inc.php (opencaching-pl)

```
 $okapi_response = \okapi\Facade::service_call('services/caches/formatters/ggz', $usr['userid'], array(
                'cache_codes' => $waypoints,
                'langpref' => $lang, 
```

Strange thing is this uses $lang (current site language, default = 'ro' ), yet I still got those PL strings.

**Comment by andrixnet** [comment]
I'll try to test it later.

**Comment by wrygiel** [comment]
> Strange thing is this uses $lang (current site language, default = 'ro' ), yet I still got those PL strings.

See [here](https://github.com/opencaching/okapi/blob/a94af853ae0ad150b8e92525a0f90eede961292e/okapi/services/caches/geocaches.php#L57-L60). If the value of your `SITELANG` is `ro`, then `$langpref` will default to `en|ro` if not given, or `ro|ro` if given. In the second case, OKAPI's `pick_best_language` will not favor English anymore, it will pick at random.

**Comment by wrygiel** [comment]
In other words, you should use `ro|en` in `$langpref` if you favor English over other languages.

**Comment by wrygiel** [comment]
Ok, I can see that something should be changed. English should still "automatically" come before other languages in this case.

**Comment by andrixnet** [comment]
And it still does not explain that single PL string

**Comment by wrygiel** [comment]
> And it still does not explain that single PL string

It does. You called `ggz` method with `langpref=ro`, replacing the default `en`, and OKAPI couldn't find the `ro` translation, so it used a random one. If you called `ggz` without any langpref (or with `langpref=ro|en`), then it would return English.

I think OKAPI could append "|en" automatically.

**Comment by andrixnet** [comment]
Why couldn't it find `ro` translation, since it exists (evidence is the table dump above) ?

**Comment by wrygiel** [comment]
> Why couldn't it find ro translation, since it exists (evidence is the table dump above) ?

See this quote:

> Yes, only PL and EN languages are looked up (because these are the only columns present in this table at the time). OKAPI cannot explicitly make use of the `ro` column, because other sites don't have this column. But I guess we can do an (implicit) `select *` and search for them.

**Comment by andrixnet** [comment]
Sorry, didn't make the connection. Now I understand. 
However in my mind a question is still lingering: why only that tag contained `pl` string and not any other?

**Comment by wrygiel** [comment]
Because of the non-standard structure of this particular table ("pl", "en", "ro" in columns, instead of separate rows). Maybe there are more tables like this, but this is the first one I added support for in OKAPI.

**Comment by wrygiel** [comment]
A comment from this commit:

```
Now, when no langpref is given, or none of the given langprefs match,
English will always be tried next, and SITELANG will be tried
afterwards. Only after these two a random langdict entry will be
selected.
```

I'm not 100% sure if this is the best way in all cases, but I think we should try it. If it turns out that some existing applications rely on the previously used (undocumented) defaults, then we might need to change this again. But hopefully, it's okay.
