### ISSUE TITLE
Bug in `Okapi::from_human_to_bytes`

### ISSUE THREAD

**Issue by wrygiel** [opencaching/okapi#460]
### Quote from @deg-pl's email

Hej!

Przerzuciłem się na PHP7.1 na moim dev i trochę mi sypnęło błędami (A non well formed numeric value encountered). Z tego co widzę, błędy generowane są (chyba) tylko w jednym miejscu. Zerknij proszę na okapi/core.php - tam masz taki kod:

```php
    /**
     * Convert strings such as "2M" or "50k" to bytes.
     */
    public static function from_human_to_bytes($val) {
        $val = trim($val);
        $last = strtolower($val[strlen($val)-1]);
        switch($last) {
            case 'g':
                return $val * 1024 * 1024 * 1024;
            case 'm':
                return $val * 1024 * 1024;
            case 'k':
                return $val * 1024;
            default:
                if (($last < '0') || ($last > '9')) {
                    throw new Exception("Unknown suffix");
                } else {
                    return $val;
                }
        }
    }
```

Zauważ, że np. przy argumencie 100K występuje mnożenie 100K * 1024, co faktycznie nie jest poprawne. Dorzuć proszę w wolnej chwili obcinanie ostatniego znaku przy return $val*cośtam. (...)

**Comment by wrygiel** [comment]
Powinno być już ok!

**Comment by deg-pl** [comment]
Zerknij na uwagę, którą Ci podesłałem. W nowej formie ostatnie return$val generuje zły wynik. Chodzi o przypadek from_human_to_bytes(123);

**Comment by wrygiel** [comment]
fakt, się pospieszyłem

(ogólnie brakuje mi unittestów w OKAPI mocno, ale nie ma kiedy dodać)

**Comment by wrygiel** [comment]
Tego typu poprawki robię bez żadnych testów, a to jest niebezpieczne... Polecasz może jakiś PHPowy framework do unittestów? Chciałbym wprowadzić je do OKAPI, choć coś czuję, że z braku czasu to może nie wyjść :-/
