### ISSUE TITLE
Add "trailhead" as extra waypoint

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/okapi#462]
I do like to add the extra waypoint "Trailhead" (see also https://github.com/opencaching/opencaching-pl/issues/976) to the code and i see OKAPI also make use of these extra waypoints.
This is in file /okapi/services/caches/geocaches.php from line 969.
There should not be a problem with OKAPI when it first will be committed in the code because there is a line (977 and 985) with "else" in this geocaches.php file.
Could this extra waypoint be added to this file after it has been committed on Github?

BTW, i see some differences in "case type" on line 974 and 975. Should it be?:
- when 3 then 'Circle with X'
- when 4 then 'Flag, Red'

![selectie_031](https://cloud.githubusercontent.com/assets/1060518/25281896/22d96288-26af-11e7-88e9-2b0a3479a92b.jpg)

**Comment by wrygiel** [comment]
> Could this extra waypoint be added to this file after it has been committed on Github?

Sure. If OCPL developers agree that such need waypoint-type needs to be added for OCPL, then - once it has been added - you can also add it to OKAPI.

> BTW, i see some differences in "case type" on line 974 and 975. Should it be?:
> - when 3 then 'Circle with X'
> - when 4 then 'Flag, Red'

Why do you think it's wrong?

**Comment by harrieklomp** [comment]
@wrygiel . I do not say it is wrong, i only see some differences :-)
All sites say X marks the spot with waypoints, so why not here?

**Comment by wrygiel** [comment]
> I do not say it is wrong, i only see some differences :-)

Okay, but I don't understand what differs from what :)

**Comment by andrixnet** [comment]
New waypoint type `Trailhead` at OCPL. See https://github.com/opencaching/opencaching-pl/pull/990
Databse table `waypoint_types` now contains wp_type_id = 6 (Trailhead).

I would recommend OKAPI also designate this as "Trailhead" (also compatible with Groundspeak "Trailhead" waypoint type). 

A Groundspeak GPX contains: 
`<sym>Trailhead</sym>`
`<type>Waypoint|Trailhead</type>`

**Comment by andrixnet** [comment]
Regarding the debate started by @harrieklomp : 

In my GPX rework I used the following: 
```
$wptType[0] = 'Information';        // OC: UNDEFINED
$wptType[1] = 'Flag, Green';        // OC: TYPE_PHYSICAL
$wptType[2] = 'Flag, Blue';         // OC: TYPE_VIRTUAL
$wptType[3] = 'Flag, Red';          // OC: TYPE_FINAL
$wptType[4] = 'Waypoint';           // OC: TYPE_INTERESTING
$wptType[5] = 'Parking Area';       // OC: TYPE_PARKING
$wptType[6] = 'Trailhead';          // OC: TYPE_TRAILHEAD  
```
Reason: I mostly tried to keep the existing designations. 

I would recommend we reconcile both OKAPI and OCPL GPX exports regarding WPT icons.

Here are some arguments: 
- WPT_3 (Final) "Circle with X" represents the idea of "_X marks the spot_". 
- WPT_3 (Final) "Flag, Red" represents a much better highlight visually.
Both are icons found in most GPS devices by default.

- apparently there is no OKAPI distinction between WPT_1 and WPT_2 (both default to "Flag, Green" on the `else` clause). I recommend the blue/green scheme above. (for differenciation, plus green suggest nature / natural, thus physical.)

- WPT_5 (Parking) is ok. 

- WPT_6 (Trailhead) I recommend going with "Trailhead" for compatibility with Groundspeak GPX and apps that know it. 
_Note: I also encountered devices that spell this icon as "Trail head"._

- WPT_4 (Waypoint) "Circle with X" gains contradictory meaning. It does not mean "_X marks the spot_". Nor does a flag suit it. 
Most (if not all) devices have a generic icon for "Waypoint". 
Another equivalent is "POI" (Point Of Interest), though I don't know about device support.
Groundspeak equivalent is called "Reference Point" `<sym>Reference Point</sym>`
I recommend "Waypoint".

Finally, after OKAPI designations are reconsidered and changes (if any) implemented, I will strive to make the necessary updates in OCPL GPX export modules as soon as possible as well.

**Comment by wrygiel** [comment]
> WPT_6 (Trailhead) I recommend going with "Trailhead" for compatibility with Groundspeak GPX and apps that know it.

Do you what symbols Groundspeak uses for all other waypoint types? I think it would be best if we try to be compatible with Groundspeak on this.

(BTW, tomorrow I am disappearing for 10 days.)

**Comment by wrygiel** [comment]
> > I do not say it is wrong, i only see some differences :-)
> 
> Okay, but I don't understand what differs from what :)

Perhaps you meant that OKAPI GPX symbols differ from OCPL GPX symbols?

**Comment by harrieklomp** [comment]
Sorry for my late answer but you are right. That was what i mean.

**Comment by wrygiel** [comment]
Hmm... Perhaps I based OKAPI styles on Groundspeak styles. Or perhaps I made a mistake. Or perhaps OCPL symbols changed since then. I don't know. But I have nothing against changing this. I would vote to mimic Groundspeak (because people might be used to its symbols), but I won't object if OCPL developers decide against it.

**Comment by following5** [comment]
Groundspeak knows these six waypoint types, which are in the &lt;sym>&lt;/sym> tags in GPX files:

* Final Location
* Parking Area
* Physical Stage
* Reference Point
* Trailhead
* Virtual Stage

When GPX was added to the Opencaching code (i.e. to www.opencaching.de), there probably were no applications which undestood these Groundspeak "symbols". But there were Garmin devices which have a nice set of waypoint symbols like red and green flags etc. Therefore these Garmin symbols were implemented in OC.

Before we change this, we should understand what applications we want to support. All the old Garmin devices, which are still in use, only know the "Parking Area". For all other GC symbols, they display some dummy like a black square. The same is true for Garmin applications like "Bascamp", at least up to version 4 (2012).

I guess that current apps like c:geo understand both, all the Garmin and the Groundspeak symbols.

So if we want to stay downward compatible, we would need to stay with the current Garmin symbols, and chose one of them also for "Trailhead". But we could add an option which delivers Groundspeak symbols instead.

On the other hand, if we want to stay compatible to the OC sites - that's what OKAPI currently does - we probably should adopt the OCPL changes.

**Comment by following5** [comment]
Note that these "symbol IDs" are not only in GPX files but also returned by services/caches/geocache(s). So they are also in replication data.

**Comment by andrixnet** [comment]
AFAIK OCPL waypoints map 1<->1 with Groundspeak waypoints, but IDs differ.

**Comment by following5** [comment]
There is no Groundspeak equivalent for OCPL "Interesting place".

**Comment by andrixnet** [comment]
Closest is "Reference point". Both mean a highlighted point without additional meanings, like those already described by other types. 
In fact, OCPL's english string for that could be improved.

**Comment by following5** [comment]
To sum up the discussion:
* OCPL added waypoint type "trailhead", which should be added to OKAPI.
* It needs to be assigned a symbol, but different sets of waypoints symbols exist and we are confused about them.

(Note: When I write symbol, I mean an identifier like "Parking" or "Red Flag". How to present that is up to the client developers.)

**Analysis**

Inspired by [andrixnet's table](https://wiki.opencaching.eu/index.php?title=Waypoint_types), I now have made [another table](https://wiki.opencaching.de/index.php/Waypoint_types). It turns out that there are _four_ different sets of waypoint symbols:
* Groundspeak
* OCDE GPX, using Garmin symbols
* OCPL GPX, mixing Garmin and Groundspeak symbols
* OCPL GPXgc, mixing Garmin and Groundspeak symbols + invented own symbol "Waypoint"

I guess the inconsistent two OCPL GPX symbol are an accident; should be the same.

Groundspeak symbols are type identifiers like in OKAPI, while Garmin symbols are Icon indentifiers, matching the proprietary Icon set of Garmin devices.

@wrygiel 
> Perhaps I based OKAPI styles on Groundspeak styles. Or perhaps I made a mistake. Or perhaps OCPL symbols changed since then. I don't know.

You copied the OCPL GPX symbols for OCPL installations, and I added the OCDE GPX symbols for OCDE installations. :-) So there are consistend GPX files within each OC site, but inconsistencies within OKAPI.

**Comment by following5** [comment]
GPX import tests:
* Garmin software and devices show Garmin symbol icons, and a black dot or box for all non-Garmin symbols.
* c:geo shows Icons for Groundspeak symbols, and a red dot for all non-GS symbols.
* GSAK shows (only) the symbol name and calls it "Type".
* [This map](https://www.j-berkemeier.de/ShowGPX.html) ignores the symbols.

This encourages to offer a setting in OKAPI for either OC/Garmin or Groundspeak symbols.

Now what to make of the OCPL GPX chaos? I think we should just ignore it and choose some Garmin symbol for Trailhead. And then add the Garmin/GS switch to the OCPL OKAPI GPX widget.

**Comment by following5** [comment]
Regarding the waypoints 3 and 4 that @harrieklomp mentioned: I don't see a commutation there between OKAPI and OCPL, see the [table](https://wiki.opencaching.de/index.php/Waypoint_types). Maybe you meant the difference between OCDE and OCPL? _OCDE_ uses "Circle with X" for the final location, while it is Red Flag in all OCPL contexts.

I think we should stay with that in OKAPI: Return the same Garmin symbols as the native OC implementations do. If OCPL decides to switch 3/4, _then_ we would do that in OKAPI, too.

**Comment by following5** [comment]
> I think we should just ignore it and choose some Garmin symbol for Trailhead. 

There even _is_ a Garmin symbol named "Trail Head". :-)

Looks like this:
![garmin-trailhead](https://user-images.githubusercontent.com/1614754/48673250-d7282700-eb3f-11e8-918c-5a5b13a0afc9.png)

**Comment by following5** [comment]
* Added the OCPL trailhead waypoint type and assigned Garmin "Trail Head" symbol;
* put the Groundspeak types instead of Garmin symbols into the GPX `<type>` element;
* Garmin symbol stay in the GPX `<sym>` element.

This way, Garmin _and_ Groundspeak waypoint identifiers can coexist. Will try to have c:geo support this.

**Comment by following5** [comment]
Trailhead is implemented and works fine with

- c:geo / Okapi native
- c:geo / Okapi GPX
- GSAK / Okapi GPX
