### ISSUE TITLE
Composer Package

### ISSUE THREAD

**Issue by teiling88** [opencaching/okapi#465]
Are there any aspirations to make this repository compatible with [composer](https://getcomposer.org/)? If you want I would create an pull request for this :-)

**Comment by wrygiel** [comment]
I have never used composer so far. Primarily because I don't code in PHP that much these days (and when I did, there were no such tools).

Can you explain what would you, or OKAPI, gain by this change?

**Comment by teiling88** [comment]
At this point i didn't have experience with custom installations folder during composer package installation but if this works like described in the documentation - nothing should change for you until a composer.json file. I will create an example pull request for this. 

A profit of an composer integration is that we can get rid of this kind of pull requests: https://github.com/OpencachingDeutschland/oc-server3/pull/499

**Comment by teiling88** [comment]
If we change the Namespace Structure to a correct [PSR-4](http://www.php-fig.org/psr/psr-4/) Standard - we could remove the most require_once statements in the okapi source code.

**Comment by wrygiel** [comment]
> One of the profits of an composer integration is that we can get rid of this kind of pull requests: OpencachingDeutschland/oc-server3#499

In Poland, we don't have those. OCPL is automatically informed (via GitHub notification) that a new version of OKAPI is published, and the new version is merged automatically. If you want, then we can set up a similar deployment for OCDE.

**Comment by teiling88** [comment]
Thank you for your offer but we use composer for dependency management. Composer is so to say the standard tool in the php world for handle dependencies.

**Comment by wrygiel** [comment]
I can understand why ;) Composer would indeed be much more "standard". I simply don't have time to get to know it.

**Comment by teiling88** [comment]
> I can understand why ;) Composer would indeed be much more "standard". I simply don't have time to get to know it.

I found a good solution for both sides. I will create an Pull Request for this so we can discuss about an example implementation. I think this should make it much easier to talk about it :-)

**Comment by wrygiel** [comment]
Sounds good! I guess we should finish that PSR-4 issue first?

**Comment by teiling88** [comment]
:+1:

**Comment by teiling88** [comment]
With: https://github.com/OpencachingDeutschland/oc-server3/pull/623 we integrated okapi via composer. It is deployed and works like a charm :)
