### ISSUE TITLE
Replication produces IP-based URLs

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#474]
replicate/fulldump at www.opencaching.de delivers a mixture of  http://www.opencaching.de and  http://87.230.95.54 URLs in cache data. The following geocache fields contain IP-based URLs:

- url
- owner.profile_url
- images[].thumb_url
- preview_image.thumb_url

while these fields contain domain-based URLs:

- images[].url
- preview_image.url

**Comment by wrygiel** [comment]
Isn't this related to [this issue](https://redmine.opencaching.de/issues/1056)? My guess is that OCDE is supplyinh OKAPI with a "dynamic SITE_URL", and it believes "http://87.230.95.54" (called by cron, possibly?) to be one of the valid ones.

@teiling88 

![image](https://user-images.githubusercontent.com/2168535/28259608-6138c58e-6ad7-11e7-9e46-632dc5a34203.png)

**Comment by teiling88** [comment]
The only dynamic think, as i can see so far, in this case is the http/https switch.

**Comment by following5** [comment]
Btw, fixing this problem will trigger an expensive OKAPI cronjob run (cron5 call in crontab), because OKAPI will create changelog entries for each and every geocache. So it may be wise to do deploy the fix when the server has low load.

**Comment by following5** [comment]
I have opened an Opencaching.de issue for this: https://redmine.opencaching.de/issues/1089

**Comment by following5** [comment]
While the Opencaching.PL OKAPI dump is [broken](https://github.com/opencaching/opencaching-pl/issues/1147), it works fine on .NL and .RO sites. Obviously it's a www.opencaching.de configuration problem, as the URLs are derived from the SITE_URL setting.

**Comment by teiling88** [comment]
FYI: This issue was fixed without doing anything on oc.de site.

**Comment by following5** [comment]
@teiling88 
This problem was very likely caused by the same Opencaching.de configuration issue like https://redmine.opencaching.de/issues/1107. Both problems have disappeared now.

OKAPI just outputs the SITE_URL, which is initialized [here](https://github.com/OpencachingDeutschland/oc-server3/blob/development/htdocs/okapi_settings.php#L42) from `$opt['page']['absolute_url']`. Looks like `$opt['page']['absolute_url']` was set to http://87.230.95.54/ in the OCDE code ([here](https://github.com/OpencachingDeutschland/oc-server3/blob/development/htdocs/config2/settings-dist-common.inc.php#L158)). This would have broken the OCDE function use_current_protocol(), too, which caused the http-in-https image embedding issue (https://redmine.opencaching.de/issues/1107).

https://www.opencaching.de/okapi/services/replicate/fulldump, 11 July 2017:

![old](https://user-images.githubusercontent.com/1614754/30269119-19fda210-96e8-11e7-9d75-a38254a4424b.png)

https://www.opencaching.de/okapi/services/replicate/fulldump, 7 September 2017:

![new](https://user-images.githubusercontent.com/1614754/30269142-2e8b20e0-96e8-11e7-9eaf-80895e36bda8.png)

**Comment by following5** [comment]
> https://www.opencaching.de/okapi/services/replicate/fulldump, 11 July 2017:

Oh, wait. I probably requested this one via http, not https. So this _may_ also have been an issue related to the http settings at Opencaching.de. (http meanwhile was disabled at OC.de, it redirects to https.)

**Comment by following5** [comment]
(But considering Redmine 1107, it's more likely that it was a general settings issue, not http-specific.)

**Comment by teiling88** [comment]
> (But considering Redmine 1107, it's more likely that it was a general settings issue, not http-specific.)

the only thing which changed was the SSL Only Setting. Nothing more.

**Comment by following5** [comment]
> the only thing which changed was the SSL Only Setting. Nothing more.

Yes.

The `$opt['page']['absolute_url']` setting is not entered manually in the OCDE setting files, but it is calculated by [set_absolute_urls()](https://github.com/OpencachingDeutschland/oc-server3/blob/development/htdocs/config2/settings-dist-common.inc.php#L158).  And the Redmine 1107 indicates that this calculation produced something else then "https://www.opencaching.de/" for https requests.

Maybe something is wrong with set_absolute_urls(), whatever. May be my fault, I wrote that function. ;)
