### ISSUE TITLE
Sort search/all results by date_created and date_hidden

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#476]
I would like to add "date_created" and "date_hidden" sorting options to the search/all method. Need "date_created" for an own application, and think it would be logical to add "date_hidden" then, too. Ok?

**Comment by following5** [comment]
Just noticed that sorting by cache code will do well for my purpose, as ist is similar to date_created order.

**Comment by following5** [comment]
Oops, no - cache code sorting is in alphabetical order, so e.g. OC12345 goes before OC3456.

**Comment by wrygiel** [comment]
Sure, go ahead! Just add an index, if no index exists yet.

**Comment by following5** [comment]
I don't think that an index is necessary here. Sorting a maximum of 500 rows is peanuts. ;)

**Comment by following5** [comment]
Btw, there are also no indexes for the all of the existing sorting options.

**Comment by wrygiel** [comment]
> I don't think that an index is necessary here. Sorting a maximum of 500 rows is peanuts. ;)

Nope. Ordering is done first, and limit is applied afterwards. So the sorting is done on *all* matched results.

> Btw, there are also no indexes for the all of the existing sorting options.

There are some - e.g. for `name` and `cache_code`. It all depends on the frequency this new feature will be used. It would be safer to add indexes, I think.

**Comment by following5** [comment]
Oops, it looks like matching is done on sorted results, not vice versa. Then you are right ... I thought it would work the other way round: First matching, then in-memory sorting; then those indexes would have been useless.

An index for date_created is present in both OCDE and OCPL database. Will propose to add date_hidden index at OCDE.
