### ISSUE TITLE
Link to Opencaching.US OKAPI docs is broken

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#479]
When chosing Opencaching.US from the topright menu e.g. of https://opencaching.pl/okapi/introduction.html, something goes wrong. No idea if this is a local configurtion issue.

**Comment by deg-pl** [comment]
See commit 2108af12bb5d68c26f452290f426f75aaeab8eb3
(@teiling88, @wrygiel ping ;))

**Comment by teiling88** [comment]
Oh damn - i see it. I didn't found a quick solution to fix this via .htaccess. I'm on vacation till Wednesday. I will fix it on Wednesday evening.

**Comment by teiling88** [comment]
I created a fix for this issue @deg-pl https://github.com/opencaching/okapi/pull/480/files

it is already online on opencaching.de

**Comment by deg-pl** [comment]
@teiling88 Thanks. I merged it and now seems to be ok now.
@following5 OC US is out of sync with OC PL / OKAPI repo and use very old, broken code. I think we should temporary remove OC US from top menu links.

**Comment by deg-pl** [comment]
UPDATE: Link to OKAPI US has https, but OC UK has incorrect config of OKAPI (. As you wrote - this is a local configuration issue.

**Comment by teiling88** [comment]
I think - we can close this issue or?

**Comment by deg-pl** [comment]
I think so.
@andrixnet - you have contact with OC US admins. Please tell them to check OKAPI section in settings.inc.php.

**Comment by following5** [comment]
Please reopen - the problem is not solved yet. If the US admins won't fix, I think the US site should be removed from the menu.

**Comment by deg-pl** [comment]
OK

**Comment by wrygiel** [comment]
We could also switch it back to http, like OCNL. But removing it also seems a good choice.

**Comment by andrixnet** [comment]
@deg-pl what exactly should I look for at OCUS? 

Second: I was supposed to help OCUS this spring upgrade to OCPL-current, but their site has many tweaks and other functionalities that don't exist or don't work properly in OCPL-current. Unfortunately I've been overloaded at my workplace too much to be able to spare enough time for such significant changes.

But this fall I must somehow do it.

**Comment by deg-pl** [comment]
@andrixnet comment out $OKAPI_server_URI in settings.inc.php and try OKAPI over http and https.

**Comment by andrixnet** [comment]
OCUS does not have a `$OKAPI_server_URI` in settings.inc.php
The only reference I see here:

```
 // OKAPI
 $OKAPI_SETTINGS = array(
 'OC_BRANCH' => 'oc.pl', # opencaching.us is using PL branch
  'SITELANG' => 'en',
   'EXTRA_ADMINS' => array(
     # Additional admins who want to receive email messages from OKAPI (errors,
weekly updates etc.)
    'rygielski@mimuw.edu.pl',
    ),
);
```

**Comment by andrixnet** [comment]
A few days ago at OCUS it didn't show the styles properly.
Today it shows well here: http://www.opencaching.us/okapi/introduction.html however the dropdown list (top-right) is empty.

Anyway, I'll do my best to help them integrate their requirements into OCPL-current this fall

**Comment by following5** [comment]
The style issue is with https://www.opencaching.us/okapi/introduction.html, it's still broken. 

> OCUS does not have a $OKAPI_server_URI in settings.inc.php

So the whole US site is not configured for https but for http. Then I think wrygiel's suggestion is the best solution for now:

> We could also switch it back to http, like OCNL.

**Comment by following5** [comment]
When clicking "API" in the https://www.opencaching.us/ menu, it opens http://www.opencaching.us/okapi.

We could bend all that by some setting changes to be https, but as OKAPI does not behave well in a dual-scheme http/https enviroment (see #343), I think it's really the best to stay with the site default here, which is http.
