### ISSUE TITLE
cronreport page not working

### ISSUE THREAD

**Issue by wrygiel** [opencaching/okapi#485]
I just found one page that seem to have stopped working in all nodes:

https://opencaching.pl/okapi/devel/cronreport
https://www.opencaching.de/okapi/devel/cronreport
http://www.opencaching.nl/okapi/devel/cronreport

Perhaps this has something to do with the recent change in directory structure. @teiling88, what do you think?

**Comment by wrygiel** [comment]
Just found that in error log:

```
PHP Warning:  Uncaught exception 'ErrorException' with message 'require_once(okapi/cronjobs.php): failed to open stream: Nie ma takiego pliku ani katalogu' in /srv/ocpl/okapi/views/devel/cronreport.php:21
Stack trace:
#0 /srv/ocpl/okapi/views/devel/cronreport.php(21): okapi\\OkapiErrorHandler::handle(2, 'require_once(ok...', '/srv/ocpl/okapi...', 21, Array)
#1 /srv/ocpl/okapi/views/devel/cronreport.php(21): okapi\\views\\devel\\cronreport\\View::call()
#2 [internal function]: okapi\\views\\devel\\cronreport\\View::call()
#3 /srv/ocpl/okapi/OkapiScriptEntryPointController.php(82): call_user_func_array(Array, Array)
#4 /srv/ocpl/okapi/OkapiScriptEntryPointController.php(103): okapi\\OkapiScriptEntryPointController::dispatch_request('/okapi/devel/cr...')
#5 {main}
  thrown in /srv/ocpl/okapi/views/devel/cronreport.php on line 21
```

**Comment by teiling88** [comment]
@wrygiel - i have a fix for it https://github.com/opencaching/okapi/pull/486 :-)
I found this issue while debugging the ip url problem. 
I test this pr on oc.de and well inform you if this works fine :-)

**Comment by wrygiel** [comment]
> I test this pr on oc.de and well inform you if this works fine :-)

Okay!

**Comment by teiling88** [comment]
@wrygiel - i tested it locally and deployed it on the live system. I had a big issue with the cronjobs via http. I created for oc.de an [SymfonyCommand](https://github.com/OpencachingDeutschland/oc-server3/blob/misc/fix-okapi-full-dump/htdocs/src/OcBundle/Command/OkapiCronjobsCommand.php) - should i create an small php cli script to execute cronjobs via cli too?

**Comment by deg-pl** [comment]
On OC PL we have also another error related with cron:
```
[Wed Aug 23 23:38:43.412523 2017] [:error] [pid 21471] [client 46.248.162.33:51708] PHP Warning:  Uncaught exception 'ErrorException' with message 'require_once(okapi/cronjobs.php): failed to open stream: Nie ma takiego pliku ani katalogu' in /srv/ocpl/okapi/views/update.php:14\nStack trace:\n#0 /srv/ocpl/okapi/views/update.php(14): okapi\\OkapiErrorHandler::handle(2, 'require_once(ok...', '/srv/ocpl/okapi...', 14, Array)\n#1 /srv/ocpl/okapi/views/update.php(14): require_once()\n#2 /srv/ocpl/okapi/OkapiScriptEntryPointController.php(80): require_once('/srv/ocpl/okapi...')\n#3 /srv/ocpl/okapi/OkapiScriptEntryPointController.php(103): okapi\\OkapiScriptEntryPointController::dispatch_request('/okapi/update')\n#4 {main}\n  thrown in /srv/ocpl/okapi/views/update.php on line 14
[Wed Aug 23 23:38:43.412575 2017] [:error] [pid 21471] [client 46.248.162.33:51708] PHP Fatal error:  main(): Failed opening required 'okapi/cronjobs.php' (include_path='.:/usr/share/php') in /srv/ocpl/okapi/views/update.php on line 14
```

**Comment by teiling88** [comment]
@deg-pl this issue should be fixed too because the cronjob.php includes with the new pr the autoloader.php

**Comment by wrygiel** [comment]
> @wrygiel - i tested it locally and deployed it on the live system.

So it's good to be merged?

> I had a big issue with the cronjobs via http. I created for oc.de an SymfonyCommand - should i create an small php cli script to execute cronjobs via cli too?

I'm not sure what you're asking. What kind of issue did you have? Currently OKAPI's cronjobs are executed by calling https://www.opencaching.de/okapi/cron5 - there no need for additional scripts.

**Comment by wrygiel** [comment]
BTW, I'm leaving tomorrow and will be offline for ~10 days.

**Comment by teiling88** [comment]
> So it's good to be merged?

I think so because it is running on oc.de for several days. 
https://www.opencaching.de/okapi/devel/cronreport

> What kind of issue did you have?

ressource limitations caused of the http call instead of an cli call. But it is fine for me i solved this issue for oc.de with this commit: https://github.com/OpencachingDeutschland/oc-server3/commit/8cb4576150e4551fac9419c231bd94e1fbaf5c6c

**Comment by wrygiel** [comment]
> ressource limitations caused of the http call instead of an cli call.

What kind of limitations?

**Comment by teiling88** [comment]
Execution Time. Our server has hard limitation rule from our admin in case of http calls ;-) so the cronjob via cli works much better for us.
