### ISSUE TITLE
[Feature request] Change password in cache via OKAPI

### ISSUE THREAD

**Issue by mzylowski** [opencaching/okapi#488]
Hello, after long break.

I want to prepare cache with password, but my idea is related with often changing of this password. 
Im looking for idea how to automate this process.

Maybe OKAPI should do things like that?

**Comment by following5** [comment]
I like this idea. Would allow a wealth of new geocache variants with dynamically changing log conditions.  The same is true for changing coordinates, description texts and hints.

What about services/caches/edit, starting with coordinates and password?
