### ISSUE TITLE
Git histories discontinued

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#493]
@teiling88 
Look at this: https://github.com/opencaching/okapi/commits/master/okapi/services/logs/submit/WebService.php

The refactoring has cut the histories of all the method files. We have lost "blame" capability for all commits prior to 6 June 2017.

This should be repaired.

**Comment by teiling88** [comment]
No look at this: https://github.com/opencaching/okapi/blame/ba234cc17b5c71dfd7b37fbac44dc658d2aec3b2/okapi/services/logs/submit/WebService.php 

And sometimes during refactoring you have to leave old things behind you...

**Comment by following5** [comment]
ok :-)

**Comment by following5** [comment]
What about adding a tag for the last pre-refactoring commit? This would allow easy browsing of the old histories on Github.

**Comment by wrygiel** [comment]
Hmm. That would be the first and only tag in OKAPI, and it would probably show up in the "releases" tab. Won't this be a little "ugly"?

**Comment by following5** [comment]
> it would probably show up in the "releases" tab. Won't this be a little "ugly"?

umm, yes.

If noone else needs it, I can live well with https://github.com/following5/okapi/tree/pre-refactoring.
