### ISSUE TITLE
dbstruct fails on OCNL

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#494]
Using dbstruct compare from OKAPI I compared OCRO to OCPL database structure.
http://www.opencaching.ro/okapi/devel/dbstruct?compare_to=https://opencaching.pl/okapi/devel/dbstruct
There are differences, which I have to discuss separately. 

Then I tried to see the differences between OCNL and OCPL: 
http://www.opencaching.nl/okapi/devel/dbstruct?compare_to=https://opencaching.pl/okapi/devel/dbstruct

I get this: 
```
{"error":{"developer_message":"Failed to load https:\/\/opencaching.pl\/okapi\/devel\/dbstruct","reason_stack":["bad_request"],"status":400,"more_info":"http:\/\/www.opencaching.nl\/okapi\/introduction.html#errors"}}
```

I only changed .ro to .nl in the URL. 

OCUK to OCPL comparison worked fine.

**Comment by andrixnet** [comment]
A comparison between OCNL <-> OCRO yeilds strange results with many drop statements.

**Comment by following5** [comment]
http://www.opencaching.nl/okapi/devel/dbstruct does not work properly.

**Comment by following5** [comment]
Looks like two different / independent problems at OC.nl: First the local database dump is empty, and then the access to all https-based OC sites fails.

RO is the only other site running on 'http', therefore it does not produce the 400 error.

**Comment by following5** [comment]
@harrieklomp 
Someone with admin rights at your server needs to debug this. Check the [mysqldump](https://github.com/opencaching/okapi/blob/master/okapi/views/devel/dbstruct.php#L34) output, and why [file_get_contents](https://github.com/opencaching/okapi/blob/master/okapi/views/devel/dbstruct.php#L68) refuses to access https OC sites.

Probably no OKAPI bugs but a local configuration problem.

**Comment by following5** [comment]
Well then ... let's try to remote-debug this, like the OCPL fulldump issue.

**Comment by following5** [comment]
Could not test yet at OC.nl, but the most likely reason is that the DB password contains at least one of the characters `* ? [ ] ' " \ $ ; & ( ) | ^ < > @`. This would break the password [here](https://github.com/opencaching/okapi/blob/5e5cef428a4eae8d43006573199e2a7bb6225457/okapi/views/devel/dbstruct/View.php#L35) when passing it through the shell to `mysqldump`.

**Comment by following5** [comment]
The error message is

``mysqldump: Couldn't execute 'SHOW VARIABLES LIKE 'gtid\_mode'': Table 'performance_schema.session_variables' doesn't exist (1146)``

[Suggested fixes](https://stackoverflow.com/questions/31967527/table-performance-schema-session-variables-doesnt-exist):

`mysql_upgrade -u root -p --force` or `set @@global.show_compatibility_56=ON;`

**Comment by following5** [comment]
@harrieklomp 
Could you please help to fix this?

Maybe you could start with the first command:

* `mysql_upgrade -u root -p --force`

Then restart the mysql server - I guess this is `systemctl restart mariadb.service` or `systemctl restart mysql.service` on your host.

Then I would check if the dump problem ist fixed.

**Comment by harrieklomp** [comment]
@following5 
Andrei explained to me the next.
On ocnl we have the problem that we use a very old distro. The sql version we use now is a version that is save to use within this old distro. To uprade this distro will have his problem too.

In other words, we should start ocnl from scratch with a new distro and that will take some time because i cannot do it myself and depending on other persons who know what to do. Andrei does most of the technical stuff on ocnl but he does not have the time for that because he is very busy.

**Comment by following5** [comment]
@harrieklomp 
It would be great to fix this soon, it helps in many things. Probably both of the above commands would fix the Okapi problem.

**Comment by deg-pl** [comment]
@harrieklomp I can help you, if you want.

**Comment by andrixnet** [comment]
@following5 I have checked and the OC database password does not contain any of the listed problematic characters.

**Comment by andrixnet** [comment]
I have run `mysql_upgrade -u root -p --force` on OCNL
I have restarted MySQL. 

There were many errors reported by mysql_upgrade.
 rerun after restart yielded only a few warnings about triggers missing CREATED attribute. 
```
Warning  : Trigger ocnl.cache_logs.cl_insert does not have CREATED attribute.
```

**Comment by following5** [comment]
> I have run mysql_upgrade -u root -p --force on OCNL

This has fixed the problem Thank you!

**Comment by following5** [comment]
I forgot: There is still the second issue with compare_to. Will do some more tests for that.

**Comment by following5** [comment]
SSL certificate database at opencaching.nl is outdated. Fixed by workaround.

**Comment by andrixnet** [comment]
NL to PL compare_to works: http://www.opencaching.nl/okapi/devel/dbstruct?compare_to=https://opencaching.pl/okapi/devel/dbstruct

PL to NL compare_to does not : https://opencaching.pl/okapi/devel/dbstruct?compare_to=http://opencaching.nl/okapi/devel/dbstruct

```
{"error":{"developer_message":"The following URL is not on our whitelist: \"http:\/\/opencaching.nl\/okapi\/devel\/dbstruct\".\n\nPlease use one of the following:\n\"https:\/\/opencaching.pl\/okapi\/devel\/dbstruct\",\n\"https:\/\/opencaching.pl\/okapi\/devel\/dbstruct\",\n\"https:\/\/www.opencaching.de\/okapi\/devel\/dbstruct\",\n\"https:\/\/www.opencaching.de\/okapi\/devel\/dbstruct\",\n\"http:\/\/www.opencaching.us\/okapi\/devel\/dbstruct\",\n\"https:\/\/www.opencaching.us\/okapi\/devel\/dbstruct\",\n\"http:\/\/www.opencaching.nl\/okapi\/devel\/dbstruct\",\n\"https:\/\/www.opencaching.nl\/okapi\/devel\/dbstruct\",\n\"http:\/\/www.opencaching.ro\/okapi\/devel\/dbstruct\",\n\"https:\/\/www.opencaching.ro\/okapi\/devel\/dbstruct\",\n\"https:\/\/opencache.uk\/okapi\/devel\/dbstruct\",\n\"https:\/\/opencache.uk\/okapi\/devel\/dbstruct\".","reason_stack":["bad_request"],"status":400,"more_info":"https:\/\/opencaching.pl\/okapi\/introduction.html#errors"}}
```

**Comment by following5** [comment]
Try this: https://opencaching.pl/okapi/devel/dbstruct?compare_to=http://www.opencaching.nl/okapi/devel/dbstruct

**Comment by andrixnet** [comment]
It works. 
And the reverse works as well.

Due to old distro, ca-certificates and openssl library can't be updated. 
The quickfix to curl shall be up for removal after OCNL updates.

**Comment by andrixnet** [comment]
Important note: `curl` should be listed as external dependency for OKAPI here: https://github.com/opencaching/okapi/blob/master/README.md

**Comment by following5** [comment]
OKAPI does not depend on curl, if the site configuration is healthy. It uses curl only when file_get_contents(...) does not work.

**Comment by andrixnet** [comment]
If it's in the code, is a dependency. From what I understand, it is not a requirement, but an optional dependency then.

**Comment by following5** [comment]
> it is not a requirement, but an optional dependency then.

Yes. Still I don't think that it's worth to bother anyone with curl in the the installation docs, for these reasons:

1. It is unlikely that there is an SSL issue _and_ curl is not installed.

2. If curl fails, the user (who is an OKAPI developer, OC developer or OC admin) will receive the message "curl: command not found" and may take appropriate action.

3. There is another workaround available if curl fails: By appending "&reverse=true", the reverse comparison can be initiated from the other site. E.g. https://opencaching.pl/okapi/devel/dbstruct?compare_to=http://www.opencaching.nl/okapi/devel/dbstruct&reverse=true is the same as http://www.opencaching.nl/okapi/devel/dbstruct?compare_to=https://opencaching.pl/okapi/devel/dbstruct.

4. The SSL issue can probably be solved [without curl](https://stackoverflow.com/questions/26148701/file-get-contents-ssl-operation-failed-with-code-1-and-more).

**Comment by following5** [comment]
> The SSL issue can probably be solved without curl.

[Done](https://github.com/opencaching/okapi/commit/02e9cbf7bcb7378fe691362e8086ee7003dd4aba), but I could not test yet because (as often) the Okapi deployment to NL did not work. Will try again later.

**Comment by following5** [comment]
Works fine now at OC.NL without curl.

**Comment by andrixnet** [comment]
OCNL currently has an issue with automatic updates, so testing can be resumed after it is sovled

**Comment by following5** [comment]
I did already test yesterday, everything works fine. Deployment to OCNL sometimes fails, but eventually it works.

**Comment by andrixnet** [comment]
automatic updates at OCNL is now solved.
