### ISSUE TITLE
Release dates

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#497]
I have learned [here](https://github.com/opencaching/opencaching-pl/pull/1163) from @deg-pl that in the opencaching.pl project, changes are commited to master only from Monday to Thursday, except for critical fixes. I guess this is to avoid introducing bugs while developers and admins are offline for the weekend.

As OKAPI updates are automatically committed to the OCPL repo: Should this rule also apply to OKAPI commits, or is it ok to commit OKAPI changes asynchronously?

As for myself, I will generelly only commit changes if I am available to fix bugs in the following hours and days.

**Comment by following5** [comment]
> I guess this is to avoid introducing bugs while developers and admins are offline for the weekend.

and/or because of high user activity on the weekend?

**Comment by wrygiel** [comment]
> As for myself, I will generelly only commit changes if I am available to fix bugs in the following hours and days.

I use the same rule. I'm fine in committing during weekends, but only if I will be online during this weekend.

**Comment by following5** [comment]
Then let's keep it this way.
