### ISSUE TITLE
State confusion

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#498]
The `state` field returned by the geocache(s) methods currently depends on the code branch:
* for OCDE it gives the [NUTS](https://en.wikipedia.org/wiki/Nomenclature_of_Territorial_Units_for_Statistics) level 1 entity
* for OCPL gives the NUTS level 2 entity.

Depending of the size of a country, level 1 may be states* or larger regions, while level 2 may be states* or smaller regions.

(* or something similar - it's not called "state" everywhere)

The inconsistency between PL and DE branch was created by me, because when implementing the `state` field for OCDE, I derived it from Germany, where level 1 is the state (but e.g. for Austria level 2 is the state!)

How to solve this mess? OCPL database only stores the NUTS 2 data of geocaches, and it is entered by the users - so there is no way to improve the OCPL "state" information in OKAPI. We cannot replace it by OKAPI-calulated states  (calculated via `nuts_layer` table), because they could be insonsistent with user supplied NUTS 2 entities!

But for OCDE, OKAPI could for each EU country return the NUTS data which most closely resembles "states", either level 1 or level 2. Would need a simple mapping table EU country => Nuts level.

**Comment by following5** [comment]
From [this table](https://en.wikipedia.org/wiki/Nomenclature_of_Territorial_Units_for_Statistics#Levels), I think that for Germany and UK level 1 the best choice for the subnational entity field which is called "state" in OKAPI.

**Comment by andrixnet** [comment]
OCPL code does not support it at this point, but Romania would require level 3 to properly represent it's administrative subunits. Level 2 only shows macro-regions which are of little relevance.

**Comment by andrixnet** [comment]
OCPL code does not support it at this point, but Romania would require level 3 to properly represent it's administrative subunits. Level 2 only shows macro-regions which are of little relevance.
