### ISSUE TITLE
Tidy directory structure

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#502]
Due to #489, the okapi directory structure now looks like this:

* Consumer
* CronJob
* Exception
* lib
* locale
* OAuth
* Request
* Response
* services
* static
* Token
* vendor
* views

I suggest to clean it up by inserting a "core" subnamespace:

* core
  * Consumer
  * CronJob
  * Exception
  * OAuth
  * Request
  * Response
  * Token
* lib
* locale
* services
* static
* vendor
* views

All the class files in the toplevel directory except for "Facade.php" (and "Settings.php" ?) would also be moved to "core".

**Comment by teiling88** [comment]
good idea - i created a pull request for that: https://github.com/opencaching/okapi/pull/503
