### ISSUE TITLE
path to classes after dir structure cleanup

### ISSUE THREAD

**Issue by kojoty** [opencaching/okapi#504]
After last changes in okapi directory structure I see such errors in the log:

[Fri Sep 08 19:44:26.338759 2017] [:error] [pid 13034] [client 89.64.35.201:21464] PHP Fatal error:  Uncaught exception 'ErrorException' with message 'include_once(/srv/ocpl/lib/../okapi/OkapiZIPHttpResponse.php): failed to open stream: Nie ma takiego pliku ani katalogu' in /srv/ocpl/lib/ClassPathDictionary.php:86\n
Stack trace:\n

#0 /srv/ocpl/lib/ClassPathDictionary.php(86): okapi\\OkapiErrorHandler::handle(2, 'include_once(/s...', '/srv/ocpl/lib/C...', 86, Array)\n

#1 /srv/ocpl/lib/ClassPathDictionary.php(86): {closure}()\n#2 [internal function]: {closure}('okapi\\\\OkapiZIPH...')\n

#3 /srv/ocpl/okapi/services/caches/formatters/garmin/WebService.php(49): spl_autoload_call('okapi\\\\OkapiZIPH...')\n

#4 [internal function]: okapi\\services\\caches\\formatters\\garmin\\WebService::call(Object(okapi\\Request\\OkapiInternalRequest))\n

#5 /srv/ocpl/okapi/OkapiServiceRunner.php(137): call_user_func(Array, Object(okapi\\Request\\OkapiInternalRequest))\n

#6 /srv/ocpl/okapi/Facade.php(69): okapi\\OkapiServiceRunner::call('services/caches...', Object(okapi\\Request\\OkapiInternalRequest))\n

#7 /srv/ocpl/lib/search.zip.inc.php(10): okapi\\Facade::servi in /srv/ocpl/lib/ClassPathDictionary.php on line 86, referer: https://opencaching.pl/ocpl9970709.zip?startat=0&count=max

It seems this is because OkapiZIPHttpResponse.php is located in okapi/Reponse/ not in okapi/  - I guess "use" paths should be fixed...

 @following5, could I ask you to look at this?

**Comment by following5** [comment]
I should have received notification emails for those exceptions. Looks like something is wrong with OKAPI admin error reporting.

**Comment by kojoty** [comment]
@following5 - thanks for fix
