### ISSUE TITLE
Admin error reporting not working

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#506]
No admin emails were sent for #504. Can be an Opencaching.PL configuration problem or an OKAPI bug.

**Comment by following5** [comment]
Test were ok. So why no notification for those ErrorExceptions in services/caches/formatters/garmin and services/caches/formatters/ggz?

**Comment by teiling88** [comment]
I don't think that with an PHP Fatal Error a notification is possible.

**Comment by following5** [comment]
On my develsite the error condition of #504 correctly produces an admin email.

@deg-pl 
Could you look into the email sending protocol of opencaching.pl, if there were emails sent by OKAPI to the admins (including my email address, see `okapi_settings.php`) on last Friday, 8 September, at 19:44 server time?

**Comment by deg-pl** [comment]
@following5 mails for you are send without problems:
```
Sep 11 15:06:01 opencaching2 postfix/smtp[18031]: 6849F6E03BF7: to=<following@online.de>, relay=mx01.emig.kundenserver.de[217.72.192.66]:25, delay=0.88, delays=0.08/0/0.32/0.48, dsn=2.0.0, status=sent (250 Requested mail action okay, completed: id=1MjRPw-1dAvqM48JG-00kvLX)
Sep 11 15:15:12 opencaching2 postfix/smtp[19135]: B832F6E01683: to=<following@online.de>, relay=mx00.emig.kundenserver.de[212.227.15.40]:25, delay=1.1, delays=0.15/0/0.27/0.63, dsn=2.0.0, status=sent (250 Requested mail action okay, completed: id=1MC3PJ-1djzcz1InF-00Cyfy)
Sep 12 07:12:49 opencaching2 postfix/smtp[22217]: 741616E007FE: to=<following@online.de>, relay=mx00.emig.kundenserver.de[212.227.15.40]:25, delay=1.3, delays=0.11/0.01/0.28/0.89, dsn=2.0.0, status=sent (250 Requested mail action okay, completed: id=1Mt6Hh-1dc1Sj4AeH-00tS5z)
Sep 12 13:00:42 opencaching2 postfix/smtp[6014]: C74476E007FE: to=<following@online.de>, relay=mx01.emig.kundenserver.de[217.72.192.66]:25, delay=0.92, delays=0.13/0.01/0.32/0.46, dsn=2.0.0, status=sent (250 Requested mail action okay, completed: id=1MMn8U-1e8HqY1MKS-00ImNS)
Sep 13 12:12:31 opencaching2 postfix/smtp[839]: 68A286E007FE: to=<following@online.de>, relay=mx01.emig.kundenserver.de[217.72.192.66]:25, delay=1.2, delays=0.1/0.01/0.37/0.71, dsn=2.0.0, status=sent (250 Requested mail action okay, completed: id=1MasqT-1dH6H60GcN-00cMgX)
```

**Comment by following5** [comment]
I know, the mails of September 11 to 13 reached me. But I want to find out what happened on September 8, with the #504 problem. Lots of OKAPI notification should have been sent on that day, one of them around 19:44. But it looks like none of them reached destination. (Therefore it took us one day until the bug was detected, instead of detecting it immediately.)

Is it an OKAPI problem, or was there just a temporary email problem at OC.pl?

**Comment by deg-pl** [comment]
Mails sent for you between 4'th September (3:33) and 10'th September (3:40):
```
Sep  5 11:07:23 opencaching2 postfix/smtp[13039]: 374B36E0044D: to=<following@online.de>, relay=mx01.emig.kundenserver.de[217.72.192.66]:25, delay=1, delays=0.1/0.01/0.33/0.59, dsn=2.0.0, status=sent (250 Requested mail action okay, completed: id=1MtvUw-1dUK7a37me-00ujCC)
Sep  6 23:06:37 opencaching2 postfix/smtp[26692]: D936F6E00561: to=<following@online.de>, relay=mx01.emig.kundenserver.de[217.72.192.66]:25, delay=0.95, delays=0.1/0/0.3/0.55, dsn=2.0.0, status=sent (250 Requested mail action okay, completed: id=1MWSdx-1dx2qE1gWR-00Xwq4)
Sep  7 12:25:15 opencaching2 postfix/smtp[21472]: 309B46E0109D: to=<following@online.de>, relay=mx01.emig.kundenserver.de[217.72.192.66]:25, delay=1.2, delays=0.11/0.01/0.26/0.79, dsn=2.0.0, status=sent (250 Requested mail action okay, completed: id=1Mj9qV-1dDFKZ3KxJ-00fXkv)
Sep  9 01:43:01 opencaching2 postfix/smtp[32147]: E59346E0044B: to=<following@online.de>, relay=mx00.emig.kundenserver.de[212.227.15.40]:25, delay=1.2, delays=0.12/0.01/0.38/0.68, dsn=2.0.0, status=sent (250 Requested mail action okay, completed: id=1N96Vr-1dM8LT2eMJ-015X7E)
Sep  9 01:44:21 opencaching2 postfix/smtp[32148]: AD5486E00430: to=<following@online.de>, relay=mx00.emig.kundenserver.de[212.227.15.40]:25, delay=0.88, delays=0.08/0/0.23/0.57, dsn=2.0.0, status=sent (250 Requested mail action okay, completed: id=1MhmfQ-1dD1WP0iBs-00dr2U)
```

We have no other mails for you in mentioned period

**Comment by following5** [comment]
Okay, thanks!

So it's very likely that OKAPI did not deliver the emails to the MTA on September 8, i.e. some flaw in OKAPI errorhandling.

**Comment by following5** [comment]
It cannot be due to OKAPI spam protection, because then I should have got 5 error emails for the same OKAPI method in the 24 hours before. But I didn't.

It could have been caused by a temporary defect of the okapi_cache table, but that's very unlikely.

**Comment by following5** [comment]
Same again with #550.

**Comment by following5** [comment]
Both were Facade calls. Error reporting does not work with Facade.

**Comment by following5** [comment]
Facade error and exception handling was broken with commit 23e4d322.
