### ISSUE TITLE
OCPL deployment script doesn't remove old files

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#507]
It looks like [this](https://github.com/opencaching/okapi/blob/master/etc/webhooks/postcommit.py#L167) does not work. Meanwhile there were three OKAPI deployments to OCPL that did not properly move renamed files, but the files were duplicated.

**Comment by following5** [comment]
(Have set high prio, because in one case a leftover file had rendered the Git repo unsuable on case-insensitive file systems, and the last time a leftover class file killed search_and_replace.)

**Comment by wrygiel** [comment]
I think the line you mentioned works fine, but [this one](https://github.com/opencaching/okapi/blob/fce31c683c7843821b35fb7f97e118a5bfbf3218/etc/webhooks/postcommit.py#L174) doesn't.

This is a quote of what we currently get in the output of this script:

```
Commiting and pushing to OCPL repo...
warning: You ran 'git add' with neither '-A (--all)' or '--ignore-removal',
whose behaviour will change in Git 2.0 with respect to paths you removed.
Paths like 'okapi/Okapi.php' that are
removed from your working tree are ignored with this version of Git.

* 'git add --ignore-removal <pathspec>', which is the current default,
  ignores paths you removed from your working tree.

* 'git add --all <pathspec>' will let you also record the removals.

Run 'git status' to check the paths you removed from your working tree.
```

**Comment by wrygiel** [comment]
So, I guess we should change this:

```python
my_call(["git", "add", "."], cwd=ocpl_working_dir)
```

to this?

```python
my_call(["git", "add", ".", "-A", "."], cwd=ocpl_working_dir)
```

**Comment by wrygiel** [comment]
One dot too much, I think.

```python
my_call(["git", "add", "-A", "."], cwd=ocpl_working_dir)
```
