### ISSUE TITLE
http URLs are returned for https OC sites

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#508]
* [This workaround](https://github.com/opencaching/okapi/commit/c7a4d3a3223d318a21695e48ce07b1cb2ba9fd8b) is still active and returns http URLs for alle geocaches. Is this still needed?
* services/caches/geocaches returns image and thumb URLs as stored in the OC database. For sites that switched from http to https, these URLs are still http-based for old data. OCDE code ignores the scheme of these URLs and inserts the scheme of the current request instead. I think OKAPI should do the same. (I also think I implemented that in #343, which never made it into the master code).
* For embedded images in geocache descriptions and log entries there is a similar problem. OCDE code does some str_replace 'http://www.opencachen.de/' => 'https://www.opencaching.de/' for the descriptions when requested via https. This may also make sense for OKAPI.

**Comment by wrygiel** [comment]
> This workaround is still active and returns http URLs for alle geocaches. Is this still needed?

Hopefully not that much. We can try removing it and see if users complain.
