### ISSUE TITLE
A-Code 61 "Historic site" vs. NL "Lost place"

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#515]
OKAPI currently maps the OC.NL attribute 61 to "Historic site", but at OC.NL it is called "Lost place". This is not the same: A historic side needs not to be abandoned, and a lost place needs not to be historic.

I suggest to add a new attribute A77 for the lost places, which maps to Groundspeak 54 "Abandoned structure". We may also name it this way.

**Comment by following5** [comment]
@harrieklomp 
Do you agree? Or would you rather want to rename your "Lost place" to "Historic site", to make it the same as the RO, PL and US attribute?

**Comment by harrieklomp** [comment]
Yes, i do agree to make a new attribute for "Lost place". I can change the name back to Historic site" and add the new "Lost place" in the DB. I do not know what ID to use at this moment.

**Comment by following5** [comment]
You can use ID 62 for "Lost place", it is free. But then don't forget to change 61 to 62 for the existing caches, in `caches_attributes` table!

**Comment by following5** [comment]
This problem still exists.

**Comment by harrieklomp** [comment]
Should be solved now.

**Comment by following5** [comment]
Ok, thanks!
