### ISSUE TITLE
Missing file at Opencaching.NL

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#526]
@harrieklomp @andrixnet 
There are daily error messages from the Opencaching.NL Okapi installation:

`SQL Error 1017: Can't find file: 'okapi_cache_reads' (errno: 2 - No such file or directory)`

Could you check this and eventually re-create the file?

```
CREATE TABLE `okapi_cache_reads` (
  `cache_key` varchar(64) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

**Comment by andrixnet** [comment]
I corrected the problem.

**Comment by harrieklomp** [comment]
Thank you Andrixnet.
It did also solve not showing all caches on the map. (Not all tiles of the map where loading).
