### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by deg-pl** [opencaching/okapi#527]
OKAPI on site with PHP 7.2 generates a lot of PHP warnings like:

```
ErrorException:
count(): Parameter must be an array or an object that implements Countable
=========================

--- Stack trace ---
#0 [internal function]: okapi\core\OkapiErrorHandler::handle(2, 'count(): Parame...', '/srv/ocuk/okapi...', 274, Array)
#1 /srv/ocuk/okapi/Settings.php(274): count(e-mail address here)
#2 /srv/ocuk/okapi/Settings.php(263): okapi\Settings::verify(Array)
#3 /srv/ocuk/okapi/Settings.php(316): okapi\Settings::load_settings()
#4 /srv/ocuk/okapi/core/Okapi.php(472): okapi\Settings::get('SITELANG')
#5 /srv/ocuk/okapi/index.php(49): okapi\core\Okapi::gettext_domain_init()
#6 {main}

--- OKAPI method called ---
/okapi/cron5
```

**Comment by following5** [comment]
This is looks like an error in your local settings. Check for this ...

`$config['okapi']['admin_emails'] = 'email address here';`

in your setting files and change it to

`$config['okapi']['admin_emails'] = array('root@localhost');`

I will also improve the error message; it should not throw an exception.

**Comment by deg-pl** [comment]
Thanks @following5 .
Shouldn't we change okapi_settings.php line 39 from:
`'ADMINS' => ($config['okapi']['admin_emails'] ? $config['okapi']['admin_emails'] : array($sql_errormail, 'rygielski@mimuw.edu.pl', 'following@online.de')),`
to:
`'ADMINS' => (is_array($config['okapi']['admin_emails']) ? $config['okapi']['admin_emails'] : array($sql_errormail, 'rygielski@mimuw.edu.pl', 'following@online.de')),`

**Comment by following5** [comment]
Then if you acidentally enter a plain email address string instead of an array, it would be silently discarded. I think it's safer to produce some error message instead.

**Comment by following5** [comment]
The default in the settings template file may be changed from `'email address here'` to `[]` or `array()`, then it's fine.

**Comment by deg-pl** [comment]
OK. Thanks.
