### ISSUE TITLE
Cache not shown on Google satellite map in tilted view [OKAPI]

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#528]
This has been reported at opencaching-pl: https://github.com/opencaching/opencaching-pl/issues/1411

A quickfix was made such that maps do not automatically switch to tilted view on zoom-in actions.
However according to https://github.com/opencaching/opencaching-pl/issues/1411#issuecomment-365753487 display of cache icons when tilted view is manually selected is only fixable in OKAPI.

**Comment by following5** [comment]
Google satellite map is no longer in use at OCPL sites. OCDE does not use Okapi map tiles yet.
