### ISSUE TITLE
Incorrect links in /services/caches/geocache description

### ISSUE THREAD

**Issue by deg-pl** [opencaching/okapi#531]
If user inserts YouTube film into cache description, we have following record in DB (example):
```<iframe src="//www.youtube.com/embed/VxTfMm74ur0" width="560" height="314"></iframe>```
But in /services/caches/geocache it looks like:
```<iframe src=\"https:\/\/opencaching.pl\/\/\/www.youtube.com\/embed\/VxTfMm74ur0\" width=\"560\" height=\"314\"><\/iframe>```
(https://opencaching.pl/ is added)

**Comment by bubski** [comment]
Isn't that because it starts with `//` in `src="//www.youtube`?
It should be `<iframe src="https://www.youtube.com/embed/VxTfMm74ur0"`, shouldn't it?

**Comment by deg-pl** [comment]
But form with //host/resource is correct url. Hostname should be added to /resource not to //host/resource.

**Comment by bubski** [comment]
ah I see your point

**Comment by following5** [comment]
I could fix this, but as automatic OKAPI updates are broken and my manual pull requests are not merged (see https://github.com/opencaching/opencaching-pl/pull/1451), it would be pointless.

**Comment by kojoty** [comment]
@following5, I'll resolve problem with automatic updates soon - so don't worry :) - Updates from OKAPI will work as before.
