### ISSUE TITLE
Float formatting must be independent from current locale

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#536]
For some time now we are getting error messages like this from search/bbox at Opencaching.NL:

```
okapi\core\Exception\DbException:
SQL Error 1241: Operand should contain 1 column(s)

The query was:

            select caches.wp_oc
            from caches  
            where caches.wp_oc is not null and (
            caches.latitude >= '50,124925'
            and caches.latitude < '50,162417'
        ) and (
                caches.longitude >= '7,14275'
                and caches.longitude < '7,179828'
            ) and (true) and (caches.status in ('1','2'))
            order by acos(least(1, cos((90-50,143671) * 3.14159 / 180) *
cos((90-caches.latitude) * 3.14159 / 180) + sin((90-50,143671) * 3.14159 / 180) *
sin((90-caches.latitude) * 3.14159 / 180) * cos((7,161289-caches.longitude) * 3.14159 / 180)))
* 6371000
            limit 0, 101;
=========================

--- Stack trace ---
#0 /serve/www/oc_www/oc_www/okapi/core/Db.php(266):
okapi\core\Db::throwProperDbException(Object(PDOException), '\n            se...')
#1 /serve/www/oc_www/oc_www/okapi/core/Db.php(146): okapi\core\Db::query('\n           
se...')
#2 /serve/www/oc_www/oc_www/okapi/services/caches/search/SearchAssistant.php(746):
okapi\core\Db::select_column('\n            se...')
#3 /serve/www/oc_www/oc_www/okapi/services/caches/search/bbox/WebService.php(99):
okapi\services\caches\search\SearchAssistant->get_common_search_result()
```

All the coordinate values have `,` instead of `.` decimal points. But why? Those commas are not from user input. User input is fully validated, and then the supplied `.` somehow turn into `,`.  Other coordinated values are are calculated in PHP code:

```
        $center_lat = ($bbsouth + $bbnorth) / 2.0;
        $center_lon = ($bbwest + $bbeast) / 2.0;
...
        $search_params['order_by'][] = Okapi::get_distance_sql($center_lat, $center_lon,
            $search_assistant->get_latitude_expr(),
            $search_assistant->get_longitude_expr()); # not replaced; added to the end!
...
    public static function get_distance_sql($lat1, $lon1, $lat2, $lon2)
    {
        $x1 = "(90-$lat1) * 3.14159 / 180";
        $x2 = "(90-$lat2) * 3.14159 / 180";
        #
        # least(1, ...) was added below to prevent getting values greater than 1 due
        # to floating point precision limits. See issue #351 for details.
        #
        $d = "acos(least(1, cos($x1) * cos($x2) + sin($x1) * sin($x2) * cos(($lon1-$lon2) * 3.14159 / 180))) * 6371000";
        return $d;
    }
```

How can this produce `,` decimal separators for $center_lat and $center_log?

**Comment by following5** [comment]
This was the request:

/okapi/services/caches/shortcuts/search_and_retrieve?search_method=services/caches/search/bbox&search_params={%22bbox%22:%2250.124925|7.142750|50.162417|7.179828%22,%22status%22:%22Available|Temporarily%20unavailable%22}&retr_method=services/caches/geocaches&retr_params={%22fields%22:%20%22code|name|location|type|status|difficulty|terrain|size|size2|date_hidden|trackables_count%22}&wrap=true&langpref=de|en&consumer_key=...

I am not able to reproduce the problem, though it occured multiple times over the past months. Problems started in June 2018, always bbox via search_and_retrieve, same consumer key, different coordinates.

@harrieklomp @andrixnet 
Just for your information. I have no clue how to solve this.

**Comment by following5** [comment]
This is already set:

> setlocale(LC_NUMERIC, "POSIX");

**Comment by bacza** [comment]
How about this issue:
[https://stackoverflow.com/questions/20686211/how-should-i-use-setlocale-setting-lc-numeric-only-works-sometimes](https://stackoverflow.com/questions/20686211/how-should-i-use-setlocale-setting-lc-numeric-only-works-sometimes)

**Comment by following5** [comment]
As I mentioned above:
> I am not able to reproduce the problem, though it occured multiple times over the past months. 

A settings issue should be reproducible, right? So far we had only ~5 of these error messages from OC.NL since June.

**Comment by bacza** [comment]
In multi-threaded environment the best solution would be to set proper locale in the OS level and not touch it in the application level.

**Comment by following5** [comment]
OKAPI must be independent from OS locale settings. It is an English-only interface which should only produce `.` decimal dots, no matter what the OS setting is or what other PHP scripts in other threads do.

So I think we need to do explicitely specify the dot here for all float to string conversions, independently from PHP LC_NUMERIC settings.

**Comment by following5** [comment]
> OKAPI must be independent from OS locale settings. It is an English-only interface which should only produce . decimal dots, no matter what the OS setting is or what other PHP scripts in other threads do.

To correct myself here: Okapi of course is not English only (English decimal seps even would be `,`); user messages are localized. But SQL statements and API data output always must have the same, locale-independent format.

**Comment by following5** [comment]
This also applies to the runtime numbers in OKAPI usage statistics. I guess there are even more cases of locale-dependent float output.

**Comment by teiling88** [comment]
I think the behaviour of the usage statistics should be influenced from the lokal system settings. It delivers what you prefer then.

**Comment by following5** [comment]
Float => string conversions fixed for ...

* coordinates ("lat|lon" generation, search for nearest & bbox)
* distance calculation
* cache estimates (difficulty, terrain, trip time and trip distance in GPX)
* OCPL ratings (submitting, searching and GPX)
* % recommendations (searching)
* runtime statistics (method calls; tile map; Okapi-cache score)

Searching for trip time and distance would also need proper float conversion, if implemented.
