### ISSUE TITLE
Differences in okapi-messages

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/okapi#538]
There are some differences between the okapi-messages in different languages.
The German version looks as the most complete but i am not sure about it.
Is it possible to use one main language that is up to date so other languages can be updated from there? I mean remove translations that are not used anymore and make it complete with actual translations.
From there i can offer to update other languages with source strings and update it to https://crowdin.com/project/oc-polish-code-translations.

**Comment by harrieklomp** [comment]
BTW.
Because there was no French translation this all showed up. There is some one who would like to translate it to French.

**Comment by following5** [comment]
OKAPI translations are done with Poedit. You install Poedit, load the .po file and then see the English original texts and missing translations. Add the text, save the file (which also updates the .mo file) and issue a pull request.

For adding French, it would be added to okapi/locale/Locales.php and then I think copied and edited from one of the existing language files.

**Comment by harrieklomp** [comment]
Thanks,
I know that it should be translated with Poedit. 
The actual problem is that for example the German .po file has 68 strings to translate and all other translations  have 64 strings.
When i open for example the German.po file with texteditor i see some text that is not in translation anymore. Perhaps not used any more?
My idea is to make one (perhaps the German version) up to date and i work it out on all other translations with use of Crowdin.

**Comment by following5** [comment]
Noe there are 68 localized strings in the source code, and the German and French translation files are complete. All unused translations are cleaned up. PL, RO, NL and IT translations are incomplete.

**Comment by following5** [comment]
Ah... finally now I understand:
> Is it possible to use one main language that is up to date so other languages can be updated from there?

There is no English translation file in Okapi, which could be uploaded to Crowdin as reference for all the other languages.

Ok, this will need some change in translation workflow. Will have a look at other gettext-based projects that use Crowdin, and derive some solution from that which allows both: translating via Crowdin or directly to Github (see https://github.com/opencaching/opencaching-pl/issues/1798#issuecomment-450505696).

**Comment by following5** [comment]
As far as I undestand the Crowdin settings, it is not possible to integreate one Crowdin project with multiple Github repositories. So we need to set up a separate Crowdin project for Okapi.

**Comment by following5** [comment]
Have done some experiments [here](https://crowdin.com/project/okapi) (crowdin granted free open source access for Okapi within minutes!), but the Okapi Crowdin<->Github integration is way more complicated than for OCPL or OCDE. And on my shared webserver at 1&1 there are no gettext tools available, so I can't put any webhooks there that handle the .po and .mo files.

Workflow could be like this:

1. New code is pushed or merged to master branch.
2. Github webhook extracts all the English texts from source code via xgettext => .po, extracts English texts from attribute-definitions.xml, adds the [todo] country and language names, and pushes all that to Crowdin via Crowdin API.
3. Translation are made
4. Crowdin webhook generates .mo from .po files, merges attribute translations to attribute-definitions.xml, stores country and language names and pushes that via Github API to Github.

:-S

**Comment by following5** [comment]
OKAPI attribute texts now can be translated in https://crowdin.com/project/oc-polish-code-translations. Okapi export/import is done manually via [etc/crowdin/attr.php](https://github.com/opencaching/okapi/blob/master/etc/crowdin/attr.php), but will try to set up automatic webhooks for that.

**Comment by following5** [comment]
@harrieklomp 
We will stay with your manual workflow for now for the Okapi messages. The master file for English texts is the German okapi_messages.po. Developers must update that when they add new texts in the source code.

Can you care about the Crowdin upload/downloads, as you did before (for all translations except German)?

**Comment by harrieklomp** [comment]
@following5 
Yes, sure i will do that.

**Comment by following5** [comment]
Thanks!

The attribute translation import from crowdin now is automatic. It pushes new translations every 4..6 hours to the branch "crowdin-update" and sends me an email notification; then it can be merged with a few clicks.

**Comment by following5** [comment]
The original issue is solved. Crowdin integration discussion continues in #532.
