### ISSUE TITLE
OKAPI hides status-2 waypoints

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#572]
At OCPL there are three statuses of additional geocache waypoints, like at GC.com:
* 1 = everything visible
* 2 = coordinates hidden
* 3 = private waypoint, not displayed

OKAPI only returns the status 1 waypoints. Is there any reason why status-2 WP are hidden? Otherwise, we could return them with 0/0 coordinates.

**Comment by kojoty** [comment]
@following5, I can't see any problem with presenting it if coordinates are hidden.

**Comment by following5** [comment]
Okay, these waypoints are now returned with 0/0 coordinates.

Have opened c:geo issue https://github.com/cgeo/cgeo/pull/7204 on hiding the null coordinate values.
