### ISSUE TITLE
different use of services/apisrv/installation value registration_url

### ISSUE THREAD

**Issue by bekuno** [opencaching/okapi#589]
There is a different value registration_url used in the parameter services/apisrv/installatvalue between different installation, but this is not documented.

We have in:
  https://www.opencaching.de/okapi/services/apisrv/installation
    * okapi_version_number | 1908
    * registration_url | "https://www.opencaching.de/register.php"

But in:
  https://www.opencaching.pl/okapi/services/apisrv/installation ,
  https://www.opencaching.nl/okapi/services/apisrv/installation ,
  https://www.opencaching.ro/okapi/services/apisrv/installation ,
  https://opencache.uk/okapi/services/apisrv/installation 
    * okapi_version_number | 1917
    * registration_url | "/UserRegistration"

I couldn't find any information about this change in the API documentation. So neither in the description of this function nor in the changelog.

The API documentation says:
registration_url - URL of the Opencaching site's general page for registering a new user account. 
After that, a complete URL would still have to be returned.

**Comment by following5** [comment]
This is a wrong Okapi configuration in OCPL code. Will fix it there.
