### ISSUE TITLE
ACODE duplicates

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#590]
How would be the best recommended way to resolve the following ACODE duplicates? 

- [ ] A40 and A73 both represent the same attribute: Not available 24/7.
Both are equivalent to <groundspeak id="13" inc="false" name="Available at all times" />.

A40 references
```
        <opencaching schema="OCDE" id="39" />
        <opencaching schema="OCNL" id="39" />
        <opencaching schema="OCRO" id="39" />
        <opencaching schema="OCUK" id="39" />
```
A73 references
```
        <opencaching schema="OCPL" id="80" />
        <opencaching schema="OCRO" id="80" />
```
References in A73 are wrong. OCPL and OCRO id=80 is a different attribute.
**Hence this ACODE remains empty. How is this to be handled?** 
1. leave empty?
2. delete it? 
3. reassign it to other attribute?

------------------------------
- [ ] ACODE A70 and A71 both point to the same attribute.
Both are equivalent to the same         <groundspeak id="6" inc="true" name="Recommended for kids" />

A70 references 
```
        <opencaching schema="OCPL" id="41" />
        <opencaching schema="OCNL" id="41" />
```
A71 references 
```
        <opencaching schema="OCDE" id="59" />
        <opencaching schema="OCRO" id="59" />
        <opencaching schema="OCUK" id="59" />
```
While the name and description vary slightly, the meaning is the same. 
**How should this be handled?**
4. merge into A70 and handle A71 same as A40/73
5. other ?

Thank you.

**Comment by harrieklomp** [comment]
- For A40 and A73 i can suggest to make a sqlalter for Polish database and remove the A73.
- For A70 and A71 i can suggest to make a sqlalter for Polish and Dutch database and remove the A70.

My suggestions are based on the number of databases that need to be updated. Also there is a chance that OCDE does not change their database.

**Comment by following5** [comment]
Yes, A73 now seems to be obsolete, since I did some cleanup of OCPL attributes.

> Hence this ACODE remains empty. How is this to be handled?

Reassign ID #80 in OKAPI attribute-definitions.xml to A40, but keep A73 for backward compatibility. OKAPI will then mark A73 as "discontinued".

A70 and A71 are different:
* A70 = Suited for small children.
* A71 = Suited for 10-12 years old children.

We map both the the same GC attribute, because there is no better way to map it.

**Comment by following5** [comment]
@harrieklomp 
This can only be changed in OKAPI code; OCPL code or database does not know about A40 or A73. It's just ID #80 there.

**Comment by following5** [comment]
> A70 = Suited for small children.
> A71 = Suited for 10-12 years old children.

... theoretically. Practically, many user's wont care about this detail and just assign the attribute to anything they associate with "children". But that's nothing we can do about at OKAPI project; we just reflect the attribute definitions chosen by OCDE and OCPL developers.

**Comment by harrieklomp** [comment]
@following5 

> This can only be changed in OKAPI code; OCPL code or database does not know about A40 or A73. It's just ID 80 there.

For the changing the code and/or database we need to open a issue on https://github.com/opencaching/opencaching-pl

**Comment by andrixnet** [comment]
see also https://github.com/opencaching/opencaching-pl/issues/1251

**Comment by andrixnet** [comment]
As part of https://github.com/opencaching/opencaching-pl/issues/1251 I will also update attributes.xml in OKAPI and make a pull request.

**Comment by andrixnet** [comment]
Question: is this distinction  important / significant for both OC node operators (rules) and geocachers?
> A70 = Suited for small children.
> A71 = Suited for 10-12 years old children.
I mean, is this age range significant in any practical sense or was it some intent at some time in the past and remained as such in the translation? 

Let me put it another way: 
How does OCDE consider caches with this attribute regardign children 9 years or 13 years old?

**Comment by following5** [comment]
> I mean, is this age range significant in any practical sense

The 10-12 years range was defined on purpose this way by OCDE developers (long time ago), after discussing which attribute definition would be most useful. It is defined this way on the OCDE website. We would break OCDE semantics if we redefine it in Okapi, therefore we should not do that.

**Comment by following5** [comment]
FYI, I am no member of OCDE team for a while now, and OCDE development is almost dead. From the Okapi side, I think we can consider OCDE as a static legacy which we need to stay backward compatible to.

**Comment by andrixnet** [comment]
Understood, thank you.

**Comment by andrixnet** [comment]
Sovled by https://github.com/opencaching/okapi/pull/591

**Comment by andrixnet** [comment]
This issue has been solved and can be closed.
