### ISSUE TITLE
Cache attribute in native language returned by OKAPI 

### ISSUE THREAD

**Issue by bekuno** [opencaching/okapi#592]
see https://github.com/cgeo/cgeo/issues/7671

The result from the okapi call for cache OR00C1 gives 4 attributes, one of them in german (native language here).
Is this a okapi error, or an error in the OR database ore something other problem?

![ocrstro_attributes](https://user-images.githubusercontent.com/32555742/60219073-8d3fb600-9871-11e9-83da-73a8f3006880.PNG)

**Comment by following5** [comment]
"Unauffällig vorgehen" actually is the only OKAPI attribute name in the screenshot. The other three do not exist in OKAPI and must have been produced by c:geo.

The `services/caches/geocache(s)` methods do not return attribute names, but just A-codes. How does c:geo map those A-codes to names?

OR00C1 has the A-codes A39, A42, A71 and A74. When I request the names for that via OKAPI

https://www.opencaching.ro/okapi/services/attrs/attributes?consumer_key=xxx&acodes=A39|A42|A71|A72

I get this output:

```
{
    "A39": {
        "name": "Available 24/7"
    },
    "A42": {
        "name": "Recommended at night"
    },
    "A71": {
        "name": "Suitable for children (10-12 years)"
    },
    "A72": {
        "name": "Reverse Cache"
    }
}
```

**Comment by bekuno** [comment]
The A74 was the "problematic" attribute. Does okapi gives the result also in native language?

**Comment by bekuno** [comment]
I found the solution in c:geo - the acode 74 was not mapped in the internal configufation.

**Comment by following5** [comment]
You can use the `langpref` argument to chose the language of Attribute names returned by OKAPI. Romanian however is not fully translated, so you may receive a mixture of Romanian and English.

**Comment by bekuno** [comment]
Yes, the langpref argument was set for the okapi call.
