### ISSUE TITLE
PHP 7.4+ and 8.0 support

### ISSUE THREAD

**Issue by deg-pl** [opencaching/okapi#602]
From PHP 7.4 array and string offset access syntax with curly braces is deprecated.
In PHP8.0 it gives an fatal error:

```
okapi\core\Exception\FatalError:
Array and string offset access syntax with curly braces is no longer supported

File: /okapi/core/OAuth/OAuthSignatureMethod.php
Line: 52
```

**Comment by teiling88** [comment]
With this gist: https://gist.github.com/mathiasverraes/3096500 I checked all files. Only OAUthSignatureMethod was using curly braces.

**Comment by deg-pl** [comment]
One more issue:
create_function() has been deprecated as of PHP 7.2, and removed as of PHP 8.0

**Comment by deg-pl** [comment]
Problems fixed. I hope I can close this issue.
