### ISSUE TITLE
imagegd2(): GD2 image support has been disabled

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#619]
After a recent GD library debacle where some errors were being generated due to a bug in libgd-2.3.0 I managed to upgrade to libgd-2.3.3 on OCRO/NL/US. 

After the upgrade I started getting the following in error.log:
```imagegd2(): GD2 image support has been disabled\n, referer: https://www.opencaching.us/MainMap/fullScreen?lat=32.55035&lon=-92.165183333333&openPopup```

According to https://github.com/libgd/libgd/issues/428 GD2 format has been designated for development and testing purposes only and disabled by default. 

Obviously my upgrade was built according to default settings. 

Since this has been slated for being phased out of production anyway. 

AFAIK it seems to be used in TileRenderer.php for caching purposes. Perhaps something different could be used?

**Comment by deg-pl** [comment]
@BonEchoGeocacher @TermiteHunter let's continue discussion from https://github.com/opencaching/opencaching-pl/issues/2344 here, because this is an OKAPI problem.

With @kojoty we done research, and this issue we'll fix next week.

**Comment by kojoty** [comment]
The fix seems to be ready. I'm going to deliver it early on Monday.

**Comment by BonEchoGeocacher** [comment]
The cache map is working again on OCNA. Many thanks to [kojoty](https://github.com/kojoty) and [deg-pl](https://github.com/deg-pl) for fixing this issue - very much appreciated!

**Comment by andrixnet** [comment]
Many thanks.
